### ISSUE TITLE
Bazel test failed

### ISSUE THREAD

**Issue by waldstein1983** [tensorflow/ranking#10]
Hi,
After I installed tensforflow_ranking successfully, I ran the test script but found following errors:
INFO: Invocation ID: e63b1cdf-a900-4899-b2e2-b85de852fa6b
INFO: Analysed 21 targets (8 packages loaded, 192 targets configured).
INFO: Found 13 targets and 8 test targets...
FAIL: //tensorflow_ranking/python:model_test (see /root/.cache/bazel/_bazel_root/197a28263a16f7d64afd921c986f3c1b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/python/model_test/test.log)
FAIL: //tensorflow_ranking/python:head_test (see /root/.cache/bazel/_bazel_root/197a28263a16f7d64afd921c986f3c1b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/python/head_test/test.log)
FAIL: //tensorflow_ranking/python:losses_test (see /root/.cache/bazel/_bazel_root/197a28263a16f7d64afd921c986f3c1b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/python/losses_test/test.log)
FAIL: //tensorflow_ranking/python:data_test (see /root/.cache/bazel/_bazel_root/197a28263a16f7d64afd921c986f3c1b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/python/data_test/test.log)
FAIL: //tensorflow_ranking/python:feature_test (see /root/.cache/bazel/_bazel_root/197a28263a16f7d64afd921c986f3c1b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/python/feature_test/test.log)
FAIL: //tensorflow_ranking/python:metrics_test (see /root/.cache/bazel/_bazel_root/197a28263a16f7d64afd921c986f3c1b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/python/metrics_test/test.log)
FAIL: //tensorflow_ranking/python:utils_test (see /root/.cache/bazel/_bazel_root/197a28263a16f7d64afd921c986f3c1b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/python/utils_test/test.log)
FAIL: //tensorflow_ranking/examples:tf_ranking_libsvm_test (see /root/.cache/bazel/_bazel_root/197a28263a16f7d64afd921c986f3c1b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/examples/tf_ranking_libsvm_test/test.log)

Can you please help to identify root cause?

**Comment by AllenShow** [comment]
I encountered the same problem...

**Comment by ramakumar1729** [comment]
Can you please share the OS, and the bazel version you are running these tests on? I've checked on Ubuntu, and these are working fine.

**Comment by waldstein1983** [comment]
I use CentOS. Afterwards I used Ubuntu Docker and it works

**Comment by zenogantner** [comment]
I have a very similar problem on Ubuntu 18.04 with Python 3.

The example also does not work for me:
```
>>> rm -rf $OUTPUT_DIR && bazel build -c opt tensorflow_ranking/examples/tf_ranking_libsvm_py_binary && ./bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary --train_path=$TRAIN --vali_path=$VALI --test_path=$TEST --output_dir=$OUTPUT_DIR --num_features=136 --num_train_steps=100
INFO: Invocation ID: 83e6095d-454e-4694-b275-542a66ecf2ce
INFO: Analysed target //tensorflow_ranking/examples:tf_ranking_libsvm_py_binary (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Target //tensorflow_ranking/examples:tf_ranking_libsvm_py_binary up-to-date:
  bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary
INFO: Elapsed time: 0.093s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/home/zgantner/src/ranking/./bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary.runfiles/org_tensorflow_ranking/tensorflow_ranking/examples/tf_ranking_libsvm.py", line 64, in <module>
    from absl import flags
ImportError: No module named absl
```

Is this a Python 2 vs. Python 3 issue?

>>> head -1 bazel-bin/tensorflow_ranking/examples/tf_ranking_libsvm_py_binary
#!/usr/bin/env python

The "python" interpreter on Ubuntu is Python 2:
>>> /usr/bin/env python --version
Python 2.7.15rc1

**Comment by zenogantner** [comment]
Python 2 works flawlessly.
How can I run TF-Ranking from Python 3?
Is it possible to run things without Bazel?

**Comment by zenogantner** [comment]
This here works, btw: `python3 -c "import tensorflow_ranking"`.

So I guess I have only problems running things from Bazel with Python 3 ...

**Comment by ramakumar1729** [comment]
@zenogantner : This error: `ImportError: No module named absl` is not dependent on python 2 vs 3. You can install absl separately, or use the instructions to build the pip .whl file, which has absl dependency. I would suggest using virtualenv to isolate the version of python being used. Our bazel tests work for both python 2 and 3.
