### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by MiladShahidi** [tensorflow/ranking#100]
I cannot find the documentation for TFR. I have seen the GitHub Readme and the tutorials on the Colab. But is there documentation for the API? i.e. a list of classes and functions with their signatures and what they exactly do?

Update: I can see the docstrings in the source code. I'm just wondering if these have been gathered in one place on the tensorflow.org or elsewhere.

**Comment by ramakumar1729** [comment]
Hi MIlad, all the list of symbols/operations are available [here](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/g3doc/api_docs/python/index.md). You can browse the autogenerated documentation from docstrings [here](https://github.com/tensorflow/ranking/tree/master/tensorflow_ranking/g3doc/api_docs/python).

**Comment by MiladShahidi** [comment]
Were these pages moved elsewhere? The links were fine initially, but the are broken now.

**Comment by ramakumar1729** [comment]
The links are back online. Please take a look.

**Comment by ramakumar1729** [comment]
Closing this for now.
