### ISSUE TITLE
How to use the saved_model.pb to make prediction on python ?

### ISSUE THREAD

**Issue by mayank953** [tensorflow/ranking#101]
On running the code through the method provided in Running Script, saved_model.pb & variables folder is obtained. I was able to make a prediction using 
```
saved_model_cli run \
    --dir ./ \
    --tag_set serve \
    --signature_def predict \
    --input_examples 'examples=[{"2":[0.5348837209302325],"3":[0.75],"4":[33.68298368298368],"5":[14.4054],"6":[1707.0],"8":[1.0],"11":[1.0],"14":[1.0],"15":[1.0]},{"2":[0.3409090909090909],"4":[50.0],"5":[0.8047000000000001],"6":[833.0],"12":[1.0]}]'
```
The above CLI command contains 2 test cases provides me with 2 scores. 
I want to know a method wherein I could load the saved model on python or host it using docker on tf-serving & then make predictions on multiple inputs. My data is of the form of LibSVM with multiple features on each entry as shown below.
 ```
1 qid:0 2:0.6842105263157895 4:29.1951604418727 5:1.4356 6:1346 8:1 11:1 14:1 15:1
0 qid:0 2:0.8125 3:0.8571428571428571 4:32.55459624174708 5:35.69730000000001 6:1328 8:1 11:1 14:1 15:1
```

**Comment by vabhishekprdxn** [comment]
Hi @mayank953 , I too want to know this but I am stuck at one step behind you as I am not able to save the model and calling it for predict. I am working on Jupyter Notebook, would you be able to help me with the line of code to save the model and then call it again to predict.

Thanks in advance!

**Comment by ramakumar1729** [comment]
Hi @mayank953, you can refer to tensorflow serving tutorial: https://www.tensorflow.org/tfx/tutorials/serving/rest_simple.

**Comment by mayank953** [comment]
@vabhishekprdxn request you to reach me on my mail: mayank953@gmail.com & I will definitely assist you.
@ramakumar1729  So i used docker to host my model. The half_plus_two name can be ignored as I have copy pasted my model files instead of them. .
```
docker run -p 8500:8500 --mount type=bind,source=/tmp/tfserving/serving/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu,target=/models/half_plus_two -e MODEL_NAME=half_plus_two -t TensorFlow/serving &
```
I was following the solution provided in #46 . My input is of the form in LibSVM data 
`
2 qid:1040 2:0.5443037974683544 3:0.625 4:84.56539398862714 5:1.7103 6:760 8:1 12:1
0 qid:1040 2:0.3333333333333333 4:50 5:1.9323 6:800 12:1
0 qid:1040 2:0.8584615384615385 3:0.9130434782608695 4:50 5:2.0581 6:999 10:1 12:1
0 qid:1040 2:0.6785714285714286 3:0.8 4:50 5:2.7594 6:823 12:1
`
where I'm passing it by removing qid & the first column i.e. relevance_flag. While using the saved_model_api  function I was able to predict using
```
saved_model_cli run \
    --dir ./ \
    --tag_set serve \
    --signature_def predict \
    --input_examples 'examples=[{"2":[0.5348837209302325],"3":[0.75],"4":[33.68298368298368],"5":[14.4054],"6":[1707.0],"8":[1.0],"11":[1.0],"14":[1.0],"15":[1.0]},{"2":[0.3409090909090909],"4":[50.0],"5":[0.8047000000000001],"6":[833.0],"12":[1.0]}]'
```

Then I used this [link](https://github.com/tensorflow/ranking/issues/46#issuecomment-517894649) suggested method to call my hosted image but I wasn't able to get what format should my test_data be. Neither was I able to get the response using curl command when calling through CLI.
Request you to kindly help me through that. 

My model signature using `saved_model_cli show --dir . --tag_set serve --signature_def predict`
```
The given SavedModel SignatureDef contains the following input(s):
  inputs['examples'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: input_example_tensor:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['output'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1)
      name: groupwise_dnn_v2/accumulate_scores/truediv:0
Method name is: tensorflow/serving/predict
```

**Comment by hdatteln** [comment]
I am also a bit stuck on this. However, I am using TFRecords as training/test input data; 
It would be great to have a bit more information in this example notebook on how to save  & load the trained model and make predictions: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb

**Comment by mayank953** [comment]
@ramakumar1729  @xuanhuiwang  Can you please help us with the problem so that the model can be used for prediction after loading from the saved file. 
@vabhishekprdxn  I have replied to your query on mail. 

Thanks.

**Comment by ramakumar1729** [comment]
@mayank953 : You will need to send serialized tf.Example protos to the server. Also, the examples need to be sent via a client-server style mechanism. See this mnist client [example](https://github.com/tensorflow/serving/blob/master/tensorflow_serving/example/mnist_client.py) from Tensorflow Serving repository on how to create PredictRequests.

This is a demo on how to create serialized tf.Example protos:

```

from google.protobuf import text_format
import tensorflow as tf

EXAMPLE_PROTO = text_format.Parse(
"""
 features {
      feature {
        key: "query_tokens"
        value { bytes_list { value: ["this", "is", "a", "relevant", "question"] } }
      }
    }""", tf.train.Example())
```

**Comment by ramakumar1729** [comment]
> I am also a bit stuck on this. However, I am using TFRecords as training/test input data;
> It would be great to have a bit more information in this example notebook on how to save & load the trained model and make predictions: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb

@hdatteln : Created a separate issue for this. #104

**Comment by mbw314** [comment]
@ramakumar1729 To add on to the [above comment](https://github.com/tensorflow/ranking/issues/101#issuecomment-522336703), I'm also interested in creating a `SavedModel` in the case of sparse data. I see that there is a helper function [`make_serving_input_fn`](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py#L227) for this purpose, in the case of libSVM data, but how would this look in the case of sparse data?

**Comment by ramakumar1729** [comment]
@mbw314 : For sparse data, I would recommend using the EIE format shown in the [demo](git.io/tf-ranking-demo). The [serving input_fn builder](https://github.com/tensorflow/ranking/blob/67fae555425ee75e5aa07b74100fbff2057ce9ae/tensorflow_ranking/python/data.py#L670) works for any generic parsing function, including EIE parser, tf.Example and tf.SequenceExample parsers.

**Comment by mbw314** [comment]
@ramakumar1729  I used `build_ranking_serving_input_receiver_fn_with_parsing_fn` with the parsing function `parse_from_example_in_example` and it works. Thanks!

**Comment by ramakumar1729** [comment]
> @ramakumar1729 I used `build_ranking_serving_input_receiver_fn_with_parsing_fn` with the parsing function `parse_from_example_in_example` and it works. Thanks!

That's great to hear!

**Comment by ramakumar1729** [comment]
Closing this issue as this discussion is continued in #46 .

**Comment by anirbanblackbuck** [comment]
> [mayank953@gmail.com](mailto:mayank953@gmail.com)

Hi Mayank, I mailed you regarding the same issue. Would you please help.
