### ISSUE TITLE
[Feature Request] Add demo code for predictions using ranking estimator.

### ISSUE THREAD

**Issue by ramakumar1729** [tensorflow/ranking#104]
The [demo](git.io/tf-ranking-demo) code on handling sparse features shows how to train and evaluate a ranking estimator. Update the demo code for predictions of label given the features. 

Note that this is not the same as predictions during serving using TensorFlow Serving or using the saved model. This enhancement would use the [tf.estimator.Estimator.predict()](https://github.com/tensorflow/estimator/blob/0a9292fea19abe4b1a37531e1ed59229ced71738/tensorflow_estimator/python/estimator/estimator.py#L550) function in Python for prediction.

**Comment by mbw314** [comment]
This would be very helpful! The only way I've been able to make predictions so far has been to create EIE objects from features, either in memory or on disk, and modify the `input_fn` in the example to feed them to the model.

This solution seems very cumbersome and inefficient, so a more direct method would be greatly appreciated.

> Note that this is not the same as predictions during serving using TensorFlow Serving or using the saved model.

I think an example of how to correctly serialize a model would be helpful as well. Other questions, such as [this one](https://github.com/tensorflow/ranking/issues/101), focus on the case of models with non-sparse data. I believe the issue is to define the correct `serving_input_receiver_fn` to use in `ranker.export_savedmodel` but it isn't clear to me how this should look.

**Comment by ramakumar1729** [comment]
@mbw314 : Thanks for your interest! The solution I was proposing does exactly what you already pointed out: modifies the `input_fn` to read only features. 

I'm not sure what you mean by a more direct method, but this solution will not be any more complex than using the exported SavedModel in a client-server architecture. TF serving is designed to be used to serve at scale: using a Python client on a single machine would be as good as running a `ranker.predict`, but with additional boilerplate code for creating PredictResponses and parsing PredictRequests. 

TF Serving is appropriate if you are doing inference at scale or in production, or you care about fault tolerance etc. TF-Ranking is well integrated with TF Serving via TF Serving's Predict API. In most of these cases, your client would be in C++ or JAVA or some low level language for efficiency. 

If you are running inference on a single machine, I would recommend to use `ranker.predict` for inference running on a single machine. 

Does this make sense?

**Comment by ramakumar1729** [comment]
Note: This feature has been implemented and is available in the [demo](git.io/tf-ranking-demo).

**Comment by mbw314** [comment]
Thanks for the quick updates. I see what you mean regarding production vs. single-machine inference, and I see your comment on [this issue](https://github.com/tensorflow/ranking/issues/101). I'll move my followup questions there.

**Comment by ramakumar1729** [comment]
Thanks @mbw314 . Closing this issue.

**Comment by MathildaSu** [comment]
> Thanks for the quick updates. I see what you mean regarding production vs. single-machine inference, and I see your comment on [this issue](https://github.com/tensorflow/ranking/issues/101). I'll post any followup questions there.

Hi, this demo link is broken.

**Comment by MathildaSu** [comment]
> Note: This feature has been implemented and is available in the [demo](git.io/tf-ranking-demo).

Hi, the demo link is broken

**Comment by ramakumar1729** [comment]
@MathildaSu The link is available at (http://git.io/tf-ranking-demo). The link in the previous comment was broken. It looks like Markdown in github issues expects http(s).

**Comment by ramakumar1729** [comment]
Closing this issue. Please reopen if there are any pending concerns.
