### ISSUE TITLE
Handling query id and document id

### ISSUE THREAD

**Issue by mulangonando** [tensorflow/ranking#105]
Is it possible to represent the query ID : ALPHA_NUMERIC and document ID and retrieve both in results? For the sparse data case.

Or it possible to get your dev set predictions in the order they are in the file?

**Comment by mulangonando** [comment]
For Example, am trying to create a Features column as follows

def context_feature_columns():
  """Returns context feature names to column definitions."""
  context_features = {}
  query_column = tf.feature_column.categorical_column_with_vocabulary_file(
      key="query_tokens",
      vocabulary_file=_VOCAB_PATH)
  query_embedding_column = tf.feature_column.embedding_column(
      query_column, _EMBEDDING_DIMENSION)

  answ_column = tf.feature_column.categorical_column_with_vocabulary_file(
      key="answer_tokens",
      vocabulary_file=_VOCAB_PATH)
  answ_embedding_column = tf.feature_column.embedding_column(
      answ_column, _EMBEDDING_DIMENSION)

  qid = tf.feature_column.numeric_column(key="qid",dtype=tf.int64)
  # actual_qid = tf.feature_column.numeric_column(key="query_qid", dtype=tf.int64)

  # Embedding Columns

  query_bert_encoding_column = tf.feature_column.numeric_column(key="query_bert_encoding_out",
                                                                shape=768)

  answ_bert_encoding_column = tf.feature_column.numeric_column(key="answer_bert_encoding_out",
                                                           shape=768)

  overall_bert_encoding_column = tf.feature_column.numeric_column(key="overal_bert_context_encoding_out", shape=768)

  context_features = {"query_tokens": query_embedding_column, "answer_tokens": answ_embedding_column, "qid":qid,
                      "query_bert_encoding_out":query_bert_encoding_column, "answer_bert_encoding_out": answ_bert_encoding_column,
                      "overal_bert_context_encoding_out":overall_bert_encoding_column}
  # context['query_qid'] = tf.train.Feature(bytes_list=tf.train.BytesList(value=[actual_idsdata[0].encode()]))

  return context_features

The feature actual_query _id in this line :
# actual_qid = tf.feature_column.numeric_column(key="query_qid", dtype=tf.int64) takes values such as : "MERC_124_HIEV"
Am not sure how to represent this.
Is it retrievable after prediction?

Or it possible to get your dev set predictions in the order they are in the file?

**Comment by HongleiZhuang** [comment]
Hi Isaiah, 

I would suggest you to use `predict` function of the `Estimator`.  See

https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#predict

Suppose you got an estimator called `ranker`.  You can retrieve the results by iterating over `ranker.predict(input_fn=YOUR_DEV_SET_INPUT_FN)`, which would yield a numpy array each time containing the ranking scores of all docs in a single query.  The scores would be yielded in the order they are in the file for both queries and documents.  

Let me know if you have more questions.

**Comment by mulangonando** [comment]
Thanks, apparently still not able to get the model to save my results.

**Comment by HongleiZhuang** [comment]
Do you mean the `predict` function does not work?  Or do you want to get a "coupled" prediction results with their original query_id/doc_id?  

To do the latter, you can always read the data you want to predict and couple them together, where ids are not necessarily in features.  If the former, do you have more details?

If you do want to store ids as features, you don't necessarily need to use a feature column for it.  You can always directly add something like `{"query_qid": tf.FixedLenFeature([], dtype=tf.string)}` into `context_feature_spec`?

**Comment by mulangonando** [comment]
Aaaha, @HongleiZhuang I think both situations are formidable answers, while I sought the latter, I see the solution you've given here for the former may come in handy down the line for me too. Thanks.

I think this would be it, so I'l simply close the isse
