### ISSUE TITLE
function_utils does not exist in tensorflow.python.util

### ISSUE THREAD

**Issue by nkg114mc** [tensorflow/ranking#11]
mc@prec:~/workplace/newsp/$ python -c "import tensorflow_ranking"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/workplace/newsp/tensorflow_ranking/__init__.py", line 20, in <module>
    from tensorflow_ranking.python import *  # pylint: disable=wildcard-import
  File "/workplace/newsp/tensorflow_ranking/python/__init__.py", line 26, in <module>
    from tensorflow_ranking.python import model
  File "/workplace/newsp/tensorflow_ranking/python/model.py", line 32, in <module>
    from tensorflow.python.util import function_utils
ImportError: cannot import name 'function_utils'

Could you double check about this?

**Comment by ramakumar1729** [comment]
Which version of tensorflow are you using? `function_utils` is available under tensorflow [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/function_utils.py).

**Comment by nkg114mc** [comment]
> Which version of tensorflow are you using? `function_utils` is available under tensorflow [here](https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/util/function_utils.py).

Thank you for the response. I am using 1.8.0. Probably the issue is because my tensorflow is not up-to-date. I will upgrade to the latest the version and try again.

**Comment by ramakumar1729** [comment]
Closing this issue for now.
