### ISSUE TITLE
Trouble with SharedEmbeddings

### ISSUE THREAD

**Issue by MiladShahidi** [tensorflow/ranking#114]
I have been trying to use a shared embedding for two categorical columns using `tf.compat.v2.feature_column.shared_mebedding`. When I run my code locally (on TF 1.14) it runs fine. When I submit the very same code for training on GCP ML-Engine, I get the following error message:

> "SharedEmbeddingColumns are not supported in `linear_model` or `input_layer`. Please use `DenseFeatures` or `LinearModel` instead."

I have no idea why I should get different outcomes when running locally and on GCP. Can you please explain what this error is trying to say?

I believe the exception is raised when I send the shared embedding feature column to `make_parse_example_spec`.

**Comment by xuanhuiwang** [comment]
Sorry for the late reply. It looks to be a problem of tensorflow version. The error indicates that the GCP used the v1 feature_columns, but your local one has a v2 feature_columns.

Let us know if this is still an issue if you upgrade your tensorflow version.

**Comment by bendersky** [comment]
Closing this for now, as there hasn't been any activity on this issue for a while. @MiladShahidi let us know if the proposed solution didn't work.
