### ISSUE TITLE
Fail to parse SequenceExample with `FixedLenSequenceFeature`

### ISSUE THREAD

**Issue by FroilanYue** [tensorflow/ranking#116]
When I use `tfr.data.read_batched_sequence_example_dataset` with example_feature_spec containing `tf.FixedLenSequenceFeature`, it raises a KeyError.

In `_SequenceExampleParser.parse`,  it convert `FixedLenFeature` to `FixedLenSequenceFeature` and setting dict `padding_values` at the same time.

But when I pass FixedLenSequenceFeature directly, `padding_values` is not set, which remains empty. And in the following code calling `pad_fn` it raises KeyError.

Changing `FixedLenSequenceFeature ` to `FixedLenFeature ` is OK, but I think it's counter-intuitive. It should be compatible with `FixedLenSequenceFeature ` .

I've write a fix for this.

**Comment by xuanhuiwang** [comment]
I commented in the PR. Please take a look.

**Comment by bendersky** [comment]
Closing this for now.
