### ISSUE TITLE
Error reading the tfrecords EIE 

### ISSUE THREAD

**Issue by mulangonando** [tensorflow/ranking#125]
Can someone help troubleshoot this error (I used the exact EIE converter provided in one of the issues here) :

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: Name: <unknown>, Feature: serialized_context (data type: string) is required but could not be found.
	 [[{{node ParseExample/ParseExample}}]]
	 [[IteratorGetNext]]
	 [[transform/encoding_layer/qery_tokens_embedding/hash_table_Lookup/LookupTableFindV2/_275]]
  (1) Invalid argument: Name: <unknown>, Feature: serialized_context (data type: string) is required but could not be found.
	 [[{{node ParseExample/ParseExample}}]]
	 [[IteratorGetNext]]
0 successful operations.
0 derived errors ignored.

**Comment by ramakumar1729** [comment]
@mulangonando You can try to read it by setting a default value in tf.feature_column, so that it can deal with cases when the feature is missing.

**Comment by rickyyue** [comment]
Yep, I had the same issues and assigning default value solves the problem. 

@ramakumar1729, is this step necessary because all padded examples need a default value? For my use cases, all nulls in dense features were imputed before input to model. However I still had that issue until I assigned a default value to dense features.

**Comment by ramakumar1729** [comment]
@rickyyue : Correct, we need them for the padded examples, though we do not use any information from padded examples.

**Comment by mulangonando** [comment]
Actually for me, I had serialized the the EIE the the Example so there was actually a key in the Example called: "serialized_context". Corrected this (Reconstructed the EIE tfrecords), seems to red just fine even train to 1k Step but fails to evaluate: says unrecognized key "then", expected a vector but [] found. sill not sure what it means. Since I use the same input function for train and dev set.

**Comment by mulangonando** [comment]
The error is here, would you think it's related to the default values issue?
Because it only comes up when evaluating during training.

InvalidArgumentError: 2 root error(s) found.
  (0) Invalid argument: 'then' must be at least a vector, but saw shape: []
	 [[{{node head/approx_ndcg_loss/Select_3}}]]
	 [[head/approx_ndcg_loss/weighted_loss/assert_broadcastable/is_valid_shape/has_valid_nonscalar_shape/has_invalid_dims/ExpandDims_1/_327]]
  (1) Invalid argument: 'then' must be at least a vector, but saw shape: []
	 [[{{node head/approx_ndcg_loss/Select_3}}]]
0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

**Comment by ramakumar1729** [comment]
@mulangonando : This seems like a different issue. Can you share more details? I'm not sure what is causing this.

**Comment by mulangonando** [comment]
The code is very similar to the demo code for sparse features.  I've only tweeked the input function to fit my data and a few other parameters.  The demo code works on the demo data. I thought just changing the data would be seamless. Here is the sections of code that I have changed

**Comment by mulangonando** [comment]
def context_feature_columns():
  """Returns context feature names to column definitions."""
  context_features = {}

  qid = tf.feature_column.numeric_column(key="qid", dtype=tf.int64)
  query_bert_encoding_column = tf.feature_column.numeric_column(key="query_bert_encoding", shape=768,
                                                                default_value=np.zeros(768))

  answ_bert_encoding_column = tf.feature_column.numeric_column(key="answer_bert_encoding", shape=768,
                                                               default_value=np.zeros(768))
  context_features = {"qid": qid, "query_bert_encoding": query_bert_encoding_column,
                      "answer_bert_encoding": answ_bert_encoding_column}

  return context_features


def example_feature_columns():
  """Returns the example feature columns."""

  relevance = tf.feature_column.numeric_column(key="relevance",dtype=tf.int64,default_value=_PADDING_LABEL)
  expl_bert_encoding_column = tf.feature_column.numeric_column(key="expl_bert_encoding_out",
                                                                shape=768,default_value=np.zeros(768))

  examples_features = {"expl_bert_encoding":expl_bert_encoding_column}#,"relevance":relevance}

  return examples_features


def input_fn(path, num_epochs=None):
    context_feature_spec = tf.feature_column.make_parse_example_spec(
        context_feature_columns().values())

    label_column = tf.feature_column.numeric_column(
        _LABEL_FEATURE, dtype=tf.int64, default_value=_PADDING_LABEL)
    example_feature_spec = tf.feature_column.make_parse_example_spec(
        list(example_feature_columns().values()) + [label_column])

    dataset = tfr.data.build_ranking_dataset(
        file_pattern=path,
        data_format=tfr.data.EIE,
        batch_size=_BATCH_SIZE,
        list_size=_LIST_SIZE,
        context_feature_spec=context_feature_spec,
        example_feature_spec=example_feature_spec,
        reader=tf.data.TFRecordDataset,
        shuffle=False,
        num_epochs=num_epochs)
    features = tf.data.make_one_shot_iterator(dataset).get_next()
    label = tf.squeeze(features.pop(_LABEL_FEATURE), axis=2)
    label = tf.cast(label, tf.float32)
    return features, label

**Comment by xuanhuiwang** [comment]
@mulangonando, we recently released a script version here: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_tfrecord.py.

Let me know if you have the same problem when trying on the above example.

For your example, can you try to make 

`shape=[768]` instead of `shape=768`.

Also, can you try to make the name `expl_bert_encoding` in the example_feature_columns the same as the key `expl_bert_encoding_out` inside the feature_column definition.

**Comment by mulangonando** [comment]
Thanks @xuanhuiwang , indeed I tried the new script and it ran without this error, only that I ran into -ve losses which keeps fluctuating without decreasing. Looking into how to solve that. Can anyone share with me code n how to unpack the EIE to view what's encoded in it (without passing it through, the ranking code). Just a small code snippet to unpack the EIE from a file back to the original string r dictionary.

**Comment by xuanhuiwang** [comment]
@mulangonando, EIE is not very user-friendly. We recently released the ExampleListWithContext data format: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/data.py#L45. You can find an example in https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/data_test.py#L32. 

ELWC has the same data logically as the EIE, but ELWC is in the standard proto format. You can use the tools to view proto to view it. Let me know if this helps.

**Comment by ramakumar1729** [comment]
@mulangonando Are you still facing an issue? If so, please share more details.

**Comment by ramakumar1729** [comment]
Closing this for now, as there hasn't been any activity for a while. Feel free to reopen with the current state of this issue, or a new issue if needed. Thanks.
