### ISSUE TITLE
Errors in handling_sparse_features.ipynb demo file

### ISSUE THREAD

**Issue by SushantChatufale** [tensorflow/ranking#129]
Hi,

The following give errors w.r.t. running handling_sparse_features.ipynb with TF 2.0 on Google Colab with GPU:
1) tf.enable_eager_execution()
I removed this directly as eager_execution is enabled by default in TF 2.0
2) tf.set_random_seed(1234) 
I replaced the above with _tf.random.set_seed(1234)_
3) tf.logging.set_verbosity(tf.logging.INFO)
Replaced with _tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.INFO)_. Not sure if this is correct?
4) tf.estimator.train_and_evaluate(ranker, train_spec, eval_spec)
AttributeError: module 'tensorflow_core._api.v2.data' has no attribute 'make_one_shot_iterator'

I am not able to resolve error 4. 
I used the tf_upgrade_v2 tool for converting this file to v2, but it doesn't seem to do the changes.
Is there a possibility to roll out this file with full compatibility with TF2.0 along with the Keras APIs in the near future??

I appreciate any help on this. Thanks.

**Comment by ramakumar1729** [comment]
@SushantChatufale : Thanks for pointing this out. Can you shared the converted code?

**Comment by ramakumar1729** [comment]
@SushantChatufale : The [demo](https://git.io/tf-ranking-demo) code is now TF2.0 compatible.

**Comment by SushantChatufale** [comment]
@ramakumar1729 Thanks a lot for the update.
I had to do 2 things to get it running:

1) Update tensorflow_ranking to 0.2.0.dev
2) In predict_input_fn(), replace **tf.data.make_one_shot_iterator(dataset).get_next()** with **tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()**
 
I will now update it for Keras layers, will let you know how it goes. 
I will be able to share the running code after I make a few custom changes, get a decent output for pairwise ranking and successfully update it for Keras integration.

**Comment by ramakumar1729** [comment]
Sounds great, thanks for letting us know! If you run into any issues updating to Keras layers, I'd recommend opening a new bug on keras layers for demo code. Closing this for now.
