### ISSUE TITLE
Contrib References no Longer function

### ISSUE THREAD

**Issue by smith6cr** [tensorflow/ranking#130]
There are multiple references to "contrib" in the examples.  For example, tf.contrib.layers.optimize_loss.  This no longer functions with the latest version of Tensorflow 2.0 and TF LTR.

Is it possible for updated examples to help those who are still learning to use LTR?  It would be greatly appreciated.

**Comment by xuanhuiwang** [comment]
It looks that there is only one reference to tf.contrib in the notebook: https://github.com/tensorflow/ranking/search?q=tf.contrib.layers.&unscoped_q=tf.contrib.layers.

This notebook is deprecated and will be removed soon. 

Please refer to other examples such as https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_tfrecord.py in the future.
