### ISSUE TITLE
TF-Ranking with Pandas DataFrame

### ISSUE THREAD

**Issue by virattt** [tensorflow/ranking#135]
Is there a tutorial / example of how to input a DataFrame into the TF-Ranking workflow?  I am sure many folks who are planning to use TF-Ranking may appreciate it!  Thank you

**Comment by ramakumar1729** [comment]
@virattt : This would involve creating a tf.data based dataset iterator that reads from a DataFrame and generated 2-D tensors for context features and 3-D tensors for example features. We currently support datasets stored in several [formats](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/data.py).

One design challenge is how to represent ranking data in the DataFrame: would each row correspond to context or an example? How do we support varying number of examples?

On a related note, we welcome contributions! Please feel to suggest ideas and Pull Requests.

**Comment by virattt** [comment]
@ramakumar1729, in our case, I do not think we have any **separate** context features (features related to query, user, session, etc.).  In my team's DataFrame, each row represents an item with a target label of whether or not the item was "clicked" (0 or 1).   The contextual features that are related to query are "baked into" each row.

Is it necessary to have separate context features?  As mentioned, in our use case, the pair of example (item features) <-> context (query features) is baked into each row in the DataFrame

**Comment by ramakumar1729** [comment]
You can take a look at [tutorial](https://www.tensorflow.org/tutorials/load_data/pandas_dataframe) on loading a DataFrame using tf.data. For variable number of examples, padding and truncation should be handled by the input parser.

**Comment by ramakumar1729** [comment]
Closing this for now. Please feel free to open a feature request or a pull request if you have something that is working.

**Comment by korosig** [comment]
Have you solved the issue? Do you have a simple example with DataFrame and 2 target label?  I want to create a ranking model for ranking students by their achievements (in each class), where each class contains 20 students.
