### ISSUE TITLE
Predictions using model

### ISSUE THREAD

**Issue by kshitij91** [tensorflow/ranking#139]
how can i use model to predict the re ranking? example i want to input the context say a query "example query" and a list of answers or features say 10 answers as features.

I want the model to return re ranked answers in text format.?
how can i achieve this?
i am able to predict but not able to convert embeddings to text, is there any function to achieve this?

**Comment by kshitij91** [comment]
using example elwc data i am getting prediction as :
[ 3.8683624 -3.9490862 -2.2340047 -2.2340047 -2.2340047 -2.2340047
 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047
 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047
 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047
 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047
 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047
 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047
 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047 -2.2340047
 -2.2340047 -2.2340047]

How can i convert the same to text and se actual re ranked list of documents? Is there any function for the same , can you please share how to achieve it?

**Comment by ramakumar1729** [comment]
Hi @kshitij91, can you add more details on the data and code you used? If you are using a colab, please share it.

**Comment by ramakumar1729** [comment]
@kshitij91 : Any updates on this? Let me know if you have any questions.

**Comment by kshitij91** [comment]
@ramakumar1729 output of the model is the score, I was thinking it as something else. Thanks
