### ISSUE TITLE
TFR in the case of Image Similarity 

### ISSUE THREAD

**Issue by youcefjd** [tensorflow/ranking#143]
Hi,
I started using Tensorflow a couple of days ago when I first heard about TFR (I exclusively used PyTorch previously), so pardon my amateurism. Is there any concrete example that shows, from scratch, how to implement a pertinent ranking system using a query provided by users (particularly an image)? 

I am working on a similarity search problem, where users submit an image of their product + a brief text description to get their product estimated. I have a dataset containing images + specifications of certain products, and I am trying to map the users' submissions with the most similar product in the dataset. I've tried extracting embedding vectors from both images and text from the submitted data and compared them with the dataset using either cosine similarity or euclidean distance but I didn't get good results. I am thinking perhaps I should treat my problem as a LTR paradigm. Do you think TFR can help? If yes, how?

Thank you!

**Comment by bendersky** [comment]
See [this colab](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb) for an end-to-end example of building a QA system with TF-Ranking over a small dataset. 

The quality of your end system will depend greatly on the quality of your image and text embeddings, as well as the amount of training data you have. However, in general learning-to-rank should produce better results than a simple cosine similarity (at least this is normally the case for textual ranking problems).

I am closing this issue for now, but please let us know if you run into any specific issues while using TF-Ranking.
