### ISSUE TITLE
The meaning of list_size, group_size, num_groups

### ISSUE THREAD

**Issue by fly12357** [tensorflow/ranking#144]
I was confused by the meaning of list_size, group_size, num_groups in model.py
![image](https://user-images.githubusercontent.com/40494145/69963544-5f128080-154b-11ea-8b08-8da7370f3169.png)
In my opinion, The list_size is the numbers of examples for one query. The batch_size is the numbers of the query. group_size has the same meaning of list_size? Is that right?

What is the meaning of "num_groups" and

**Comment by bendersky** [comment]
Please see [this issue](https://github.com/tensorflow/ranking/issues/51) for more explanation on the difference between the various *size parameters. The notion of groups is introduced in [this paper](https://arxiv.org/pdf/1811.04415.pdf) that you can read for a better background.
