### ISSUE TITLE
TF_Ranking bansed on keras model_fn.

### ISSUE THREAD

**Issue by fly12357** [tensorflow/ranking#145]
I use a keras model as the model_fn for TF_ranking. Reference the solution from #97 ,  but I meet the follwing bug.

![image](https://user-images.githubusercontent.com/40494145/70062648-65732c00-1621-11ea-9152-d3073cfa72e1.png)

I guess this probelm might be caused by the "update_ops" of keras model.

Should I pass the 
update_ops = net.get_updates_for(inputs)
in keras model to the estimator?

**Comment by ramakumar1729** [comment]
@fly12357 : Can you share a minimal reproducible code snippet? Not adding update_ops will still run, but not have the effect of batch normalization.

This can also be an issue caused by tf.data based data reader. Take a look at this StackOverflow [issue](https://stackoverflow.com/questions/56612386/defining-the-input-function-for-tensorflow-pre-made-estimator/56615591#56615591).

**Comment by fly12357** [comment]
> @fly12357 : Can you share a minimal reproducible code snippet? Not adding update_ops will still run, but not have the effect of batch normalization.
> 
> This can also be an issue caused by tf.data based data reader. Take a look at this StackOverflow [issue](https://stackoverflow.com/questions/56612386/defining-the-input-function-for-tensorflow-pre-made-estimator/56615591#56615591).

`"""
  Step1: Input_fn
"""

def context_feature_columns():
    CONTENT_FC = {
        'L_c1_his': tf.io.FixedLenFeature(shape=(), dtype=tf.string),
        # shape
        'L_c1_his_shape': tf.io.FixedLenFeature(shape=(2,), dtype=tf.int64),

    }
    return CONTENT_FC

def example_feature_columns():
    feature_columns = {
        'id': tf.compat.v1.FixedLenFeature(shape=(), dtype=tf.float32, default_value=0.0),
        'label': tf.compat.v1.FixedLenFeature(shape=(), dtype=tf.float32, default_value=0),
    }
    return feature_columns

example_feature_spec = example_feature_columns()
context_feature_spec = context_feature_columns()

def _get_descriptor_set():
  """Returns a FileDescriptorSet proto to be used by tf.io.decode_proto."""
  proto = pb.FileDescriptorSet()

  # The FileDescriptor for tensorflow.ranking.internal.ExampleListWithContext.
  file_proto = proto.file.add(
      name=_FILE_NAME, package=_PACKAGE, syntax="proto3")
  message_proto = file_proto.message_type.add(name=_MESSAGE_NAME)
  message_proto.field.add(
      name=_EXAMPLES_FIELD_NAME,
      number=1,
      type=pb.FieldDescriptorProto.TYPE_BYTES,
      label=pb.FieldDescriptorProto.LABEL_REPEATED)
  message_proto.field.add(
      name=_CONTEXT_FIELD_NAME,
      number=2,
      type=pb.FieldDescriptorProto.TYPE_BYTES)

  return proto

def parsing_fn(serialized):
    serialized = tf.convert_to_tensor(value=serialized)
    _, (serialized_context, serialized_list) = tf.io.decode_proto(
      serialized,
      message_type="{}.{}".format(_PACKAGE, _MESSAGE_NAME),
      field_names=[_CONTEXT_FIELD_NAME, _EXAMPLES_FIELD_NAME],
      output_types=[tf.string, tf.string],
      descriptor_source=(b"bytes://" +
                         _get_descriptor_set().SerializeToString()))

    batch_size = serialized_context.get_shape().as_list()[0] or tf.shape(
        input=serialized_list)[0]
    cur_list_size = tf.shape(input=serialized_list)[1]
    list_size = None

    # Apply truncation or padding to align tensor shape.
    if list_size:

      def truncate_fn():
        return tf.slice(serialized_list, [0, 0], [batch_size, list_size])

      def pad_fn():
        return tf.pad(
            tensor=serialized_list,
            paddings=[[0, 0], [0, list_size - cur_list_size]],
            constant_values="")

      serialized_list = tf.cond(
          pred=cur_list_size > list_size, true_fn=truncate_fn, false_fn=pad_fn)
      cur_list_size = list_size

    features = {}
    example_features = tf.compat.v1.io.parse_example(tf.reshape(serialized_list, [-1]), example_feature_spec)

    for k, v in six.iteritems(example_features):
      features[k] = utils.reshape_first_ndims(v, 1, [batch_size, cur_list_size])

    if context_feature_spec:
      parsed_example = tf.compat.v1.io.parse_example(tf.reshape(serialized_context, [batch_size]), context_feature_spec)
      parsed_example['L_c1_his'] = tf.compat.v1.decode_raw(parsed_example['L_c1_his'], tf.float32)
      parsed_example['L_c1_his'] = tf.compat.v1.reshape(parsed_example['L_c1_his'], [batch_size,100,2])

      features.update(parsed_example)
    return features

def build_ranking_dataset_with_parsing_fn(file_pattern,
                                          parsing_fn,
                                          batch_size,
                                          reader=tf.data.TFRecordDataset,
                                          reader_args=None,
                                          num_epochs=None,
                                          shuffle=True,
                                          shuffle_buffer_size=1000,
                                          shuffle_seed=None,
                                          prefetch_buffer_size=32,
                                          reader_num_threads=10,
                                          sloppy_ordering=True,
                                          drop_final_batch=False,
                                          num_parser_threads=None):
  files = tf.data.Dataset.list_files(
      file_pattern, shuffle=shuffle, seed=shuffle_seed)

  reader_args = reader_args or []
  dataset = files.apply(
      tf.data.experimental.parallel_interleave(
          lambda filename: reader(filename, *reader_args),
          cycle_length=reader_num_threads,
          sloppy=sloppy_ordering))

  # Extract values if tensors are stored as key-value tuples. This happens when
  # the reader is tf.data.SSTableDataset.
  if dataset.output_types == (tf.string, tf.string):
    dataset = dataset.map(lambda _, v: v)

  # Repeat and shuffle, if needed.
  if num_epochs != 1:
    dataset = dataset.repeat(num_epochs)
  if shuffle:
    dataset = dataset.shuffle(
        buffer_size=shuffle_buffer_size, seed=shuffle_seed)
  # The drop_remainder=True allows for static inference of batch size.
  dataset = dataset.batch(
      batch_size, drop_remainder=drop_final_batch or num_epochs is None)

  # Parse a batch.
  dataset = dataset.map(parsing_fn, num_parallel_calls=num_parser_threads)

  # Prefetching allows for data fetching to happen on host while model runs
  # on the accelerator. When run on CPU, makes data fecthing asynchronous.
  dataset = dataset.prefetch(buffer_size=prefetch_buffer_size)

  return dataset


def make_input_fn(file_pattern,
                  batch_size,
                  parsing_fn,
                  randomize_input=True,
                  num_epochs=None):

  def _input_fn():
    """Defines the input_fn."""

    dataset = build_ranking_dataset_with_parsing_fn(file_pattern=file_pattern, parsing_fn=parsing_fn,
                                                    batch_size=batch_size, reader=tf.data.TFRecordDataset,
                                                    num_epochs=num_epochs)

    features = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
    label = features.pop('label')
    label = tf.cast(label, tf.float32)
    return features, label

  return _input_fn





"""

  Step2 Transform_fn

"""

# reference  https://github.com/shenweichen/DeepCTR
class SparseFeat(namedtuple('SparseFeat', ['name', 'dimension', 'use_hash', 'dtype','embedding_name','embedding'])):
    __slots__ = ()

    def __new__(cls, name, dimension, use_hash=False, dtype="int32", embedding_name=None,embedding=True):
        if embedding and embedding_name is None:
            embedding_name = name
        return super(SparseFeat, cls).__new__(cls, name, dimension, use_hash, dtype, embedding_name,embedding)


class VarLenSparseFeat(namedtuple('VarLenFeat', ['name', 'dimension', 'maxlen', 'combiner', 'use_hash', 'dtype','embedding_name','embedding'])):
    __slots__ = ()

    def __new__(cls, name, dimension, maxlen, combiner="mean", use_hash=False, dtype="float32", embedding_name=None,embedding=True):
        if embedding_name is None:
            embedding_name = name
        return super(VarLenSparseFeat, cls).__new__(cls, name, dimension, maxlen, combiner, use_hash, dtype, embedding_name,embedding)



context_fc = [VarLenSparseFeat('L_bid_his', 41192 + 1, maxlen=100, embedding_name='bid'),
            VarLenSparseFeat('L_inter_time', 41192 + 1, maxlen=100, embedding=False)]



context_fc_name = ['L_c1_his']

example_fc_name = ['id']


example_fc = [SparseFeat('id', 41192 + 1, embedding_name="id"),]


def build_input_features(feature_columns, mask_zero=True, prefix='', postfix='', fc_type='context'):
    input_features = OrderedDict()
    if fc_type == 'context':
        for fc in feature_columns:
            fc_name = fc.name + postfix
            if isinstance(fc,SparseFeat):
                input_features[fc_name] = Input(
                    shape=(1,), name=prefix+fc_name, dtype=fc.dtype)
            elif isinstance(fc,DenseFeat):
                input_features[fc_name] = Input(
                    shape=(fc.dimension,), name=prefix + fc_name, dtype=fc.dtype)
            elif isinstance(fc,VarLenSparseFeat):
                input_features[fc_name] = Input(shape=(fc.maxlen,), name=prefix + fc_name,
                                                dtype=fc.dtype)
                if not mask_zero:
                    input_features[fc_name + "_seq_length"] = Input(shape=(
                        1,), name=prefix + 'seq_length_' + fc_name)
                    input_features[fc_name + "_seq_max_length"] = fc.maxlen
            elif isinstance(fc,VarLenSparseMultiFeat):
                input_features[fc_name] = Input(shape=fc.dimension, name=prefix + fc_name,
                                                dtype=fc.dtype)
            else:
                raise TypeError("Invalid feature column type,got",type(fc))
    elif fc_type == 'examples':
        # [batch_size, list_size, feature_size]; keras Input Layer 
        for fc in feature_columns:
            fc_name = fc.name + postfix
            if isinstance(fc,SparseFeat):
                input_features[fc_name] = Input(
                    shape=(None,1,), name=prefix+fc_name, dtype=fc.dtype)
            elif isinstance(fc,DenseFeat):
                input_features[fc_name] = Input(
                    shape=(None, fc.dimension,), name=prefix + fc_name, dtype=fc.dtype)
            elif isinstance(fc,VarLenSparseFeat):
                input_features[fc_name] = Input(shape=(None, fc.maxlen,), name=prefix + fc_name,
                                                dtype=fc.dtype)
                if not mask_zero:
                    input_features[fc_name + "_seq_length"] = Input(shape=(
                        1,), name=prefix + 'seq_length_' + fc_name)
                    input_features[fc_name + "_seq_max_length"] = fc.maxlen
            elif isinstance(fc,VarLenSparseMultiFeat):
                input_features[fc_name] = Input(shape=tuple([None]+list(fc.dimension)), name=prefix + fc_name,
                                                dtype=fc.dtype)
            else:
                raise TypeError("Invalid feature column type,got",type(fc))
    else:
        raise TypeError("Invalid fc_type")
    return input_features



def encode_features(features, feature_columns,
                    mode=tf.estimator.ModeKeys.TRAIN,
                    scope=None, fc_type='context'):

  cols_to_tensors = OrderedDict()
  for fc in feature_columns:
    cols_to_tensors[fc] = features[fc]
  return cols_to_tensors


def encode_listwise_features(features,
                             context_feature_columns,
                             example_feature_columns,
                             input_size=None,
                             mode=tf.estimator.ModeKeys.TRAIN,
                             scope=None):

  context_features = {}
  if context_feature_columns:
      context_features = encode_features(features, context_feature_columns)

  example_features = {}
  if example_feature_columns:
    example_features = encode_features(features, example_feature_columns)

  return context_features, example_features


def make_transform_fn():
    """Returns a transform_fn that converts features to dense Tensors."""
    def _transform_fn(features, mode):
        """Defines transform_fn."""
        context_features, example_features = encode_listwise_features(
        features,
        context_feature_columns=context_fc_name,
        example_feature_columns=example_fc_name,
        mode=mode,
        scope="transform_layer")
        return context_features, example_features
    return _transform_fn




"""

  Step3: Score_fn

"""

def make_score_fn():
  """Returns a scoring function to build `EstimatorSpec`."""
  model = DIN(example_fc+context_fc, hist_len_max=100, dnn_use_bn=True,
              l2_reg_dnn=1e-5, l2_reg_embedding=1e-5, dnn_dropout=0.7)
  model.load_weights('./DIN_weights.h5')
  score = Model(inputs=model.input, outputs=model.get_layer("DENSE_logit").output)

  def _score_fn(context_features, group_features, mode, params, config):
    """Defines the network to score a group of documents."""
    # context_features: [batch_size, ....]
    # group_features: [batch_size, group_size, ...]

    for example_fea in group_features:
        group_features[example_fea] = tf.compat.v1.layers.flatten(group_features[example_fea])

    inputs_list = list(group_features.values()) + list(context_features.values())

    logits = score(inputs_list, training=(mode == tf.estimator.ModeKeys.TRAIN))
    update_ops = score.get_updates_for(inputs_list)
    # Hack to add BatchNorm update ops to graph
    for op in score.get_updates_for(inputs_list):
        if "batch_normalization" in op.name:
            tf.compat.v1.add_to_collection(name=tf.compat.v1.GraphKeys.UPDATE_OPS, value=op)
    return logits
  return _score_fn




"""
  Step4: Train & Evaluate
"""

def train_and_eval():
  """Train and Evaluate."""
  Train_data_path = './DATA'
  train_file_list = os.listdir(Train_data_path)
  train_file_list = [Train_data_path + '/' + i for i in train_file_list]

  train_input_fn = make_input_fn(train_file_list, batch_size=32, parsing_fn=parsing_fn)

  eval_input_fn = make_input_fn(train_file_list, batch_size=32, parsing_fn=parsing_fn,
                                randomize_input=False, num_epochs=1)
  
  optimizer = tf.compat.v1.train.AdagradOptimizer(
      learning_rate=0.00001)

  def _train_op_fn(loss):
    """Defines train op used in ranking head."""
    update_ops = tf.compat.v1.get_collection(tf.compat.v1.GraphKeys.UPDATE_OPS)
    minimize_op = optimizer.minimize(
        loss=loss, global_step=tf.compat.v1.train.get_global_step())
    train_op = tf.group([minimize_op, update_ops])
    return train_op

  ranking_head = tfr.head.create_ranking_head(
      loss_fn=tfr.losses.make_loss_fn("pairwise_logistic_loss",
          weights_feature_name="",
          lambda_weight=tfr.losses.create_ndcg_lambda_weight()),
      eval_metric_fns=eval_metric_fns(),
      train_op_fn=_train_op_fn)

  estimator = tf.estimator.Estimator(
      model_fn=tfr.model.make_groupwise_ranking_fn(
          group_score_fn=make_score_fn(),
          group_size=1,
          transform_fn=make_transform_fn(),
          ranking_head=ranking_head),
      model_dir="./out",
      config=tf.estimator.RunConfig(save_checkpoints_steps=1000).replace(session_config=session_config))

  train_spec = tf.estimator.TrainSpec(
      input_fn=train_input_fn, max_steps=100000)

  # exporters = tf.estimator.LatestExporter(
  #     "saved_model_exporter", serving_input_receiver_fn=make_serving_input_fn())

  eval_spec = tf.estimator.EvalSpec(
      name="eval",
      input_fn=eval_input_fn,
      steps=1,
      # exporters=exporters,
      start_delay_secs=0,
      throttle_secs=15)

  # Train and validate.
  tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)

`

**Comment by fly12357** [comment]
> @fly12357 : Can you share a minimal reproducible code snippet? Not adding update_ops will still run, but not have the effect of batch normalization.
> 
> This can also be an issue caused by tf.data based data reader. Take a look at this StackOverflow [issue](https://stackoverflow.com/questions/56612386/defining-the-input-function-for-tensorflow-pre-made-estimator/56615591#56615591).
`
"""
  Step1: Input_fn
"""

def context_feature_columns():
    CONTENT_FC = {
        'L_c1_his': tf.io.FixedLenFeature(shape=(), dtype=tf.string),
        # shape
        'L_c1_his_shape': tf.io.FixedLenFeature(shape=(2,), dtype=tf.int64),

    }
    return CONTENT_FC

def example_feature_columns():
    feature_columns = {
        'id': tf.compat.v1.FixedLenFeature(shape=(), dtype=tf.float32, default_value=0.0),
        'label': tf.compat.v1.FixedLenFeature(shape=(), dtype=tf.float32, default_value=0),
    }
    return feature_columns

example_feature_spec = example_feature_columns()
context_feature_spec = context_feature_columns()

def _get_descriptor_set():
  """Returns a FileDescriptorSet proto to be used by tf.io.decode_proto."""
  proto = pb.FileDescriptorSet()

  # The FileDescriptor for tensorflow.ranking.internal.ExampleListWithContext.
  file_proto = proto.file.add(
      name=_FILE_NAME, package=_PACKAGE, syntax="proto3")
  message_proto = file_proto.message_type.add(name=_MESSAGE_NAME)
  message_proto.field.add(
      name=_EXAMPLES_FIELD_NAME,
      number=1,
      type=pb.FieldDescriptorProto.TYPE_BYTES,
      label=pb.FieldDescriptorProto.LABEL_REPEATED)
  message_proto.field.add(
      name=_CONTEXT_FIELD_NAME,
      number=2,
      type=pb.FieldDescriptorProto.TYPE_BYTES)

  return proto

def parsing_fn(serialized):
    serialized = tf.convert_to_tensor(value=serialized)
    _, (serialized_context, serialized_list) = tf.io.decode_proto(
      serialized,
      message_type="{}.{}".format(_PACKAGE, _MESSAGE_NAME),
      field_names=[_CONTEXT_FIELD_NAME, _EXAMPLES_FIELD_NAME],
      output_types=[tf.string, tf.string],
      descriptor_source=(b"bytes://" +
                         _get_descriptor_set().SerializeToString()))

    batch_size = serialized_context.get_shape().as_list()[0] or tf.shape(
        input=serialized_list)[0]
    cur_list_size = tf.shape(input=serialized_list)[1]
    list_size = None

    # Apply truncation or padding to align tensor shape.
    if list_size:

      def truncate_fn():
        return tf.slice(serialized_list, [0, 0], [batch_size, list_size])

      def pad_fn():
        return tf.pad(
            tensor=serialized_list,
            paddings=[[0, 0], [0, list_size - cur_list_size]],
            constant_values="")

      serialized_list = tf.cond(
          pred=cur_list_size > list_size, true_fn=truncate_fn, false_fn=pad_fn)
      cur_list_size = list_size

    features = {}
    example_features = tf.compat.v1.io.parse_example(tf.reshape(serialized_list, [-1]), example_feature_spec)

    for k, v in six.iteritems(example_features):
      features[k] = utils.reshape_first_ndims(v, 1, [batch_size, cur_list_size])

    if context_feature_spec:
      parsed_example = tf.compat.v1.io.parse_example(tf.reshape(serialized_context, [batch_size]), context_feature_spec)
      parsed_example['L_c1_his'] = tf.compat.v1.decode_raw(parsed_example['L_c1_his'], tf.float32)
      parsed_example['L_c1_his'] = tf.compat.v1.reshape(parsed_example['L_c1_his'], [batch_size,100,2])

      features.update(parsed_example)
    return features

def build_ranking_dataset_with_parsing_fn(file_pattern,
                                          parsing_fn,
                                          batch_size,
                                          reader=tf.data.TFRecordDataset,
                                          reader_args=None,
                                          num_epochs=None,
                                          shuffle=True,
                                          shuffle_buffer_size=1000,
                                          shuffle_seed=None,
                                          prefetch_buffer_size=32,
                                          reader_num_threads=10,
                                          sloppy_ordering=True,
                                          drop_final_batch=False,
                                          num_parser_threads=None):
  files = tf.data.Dataset.list_files(
      file_pattern, shuffle=shuffle, seed=shuffle_seed)

  reader_args = reader_args or []
  dataset = files.apply(
      tf.data.experimental.parallel_interleave(
          lambda filename: reader(filename, *reader_args),
          cycle_length=reader_num_threads,
          sloppy=sloppy_ordering))

  # Extract values if tensors are stored as key-value tuples. This happens when
  # the reader is tf.data.SSTableDataset.
  if dataset.output_types == (tf.string, tf.string):
    dataset = dataset.map(lambda _, v: v)

  # Repeat and shuffle, if needed.
  if num_epochs != 1:
    dataset = dataset.repeat(num_epochs)
  if shuffle:
    dataset = dataset.shuffle(
        buffer_size=shuffle_buffer_size, seed=shuffle_seed)
  # The drop_remainder=True allows for static inference of batch size.
  dataset = dataset.batch(
      batch_size, drop_remainder=drop_final_batch or num_epochs is None)

  # Parse a batch.
  dataset = dataset.map(parsing_fn, num_parallel_calls=num_parser_threads)

  # Prefetching allows for data fetching to happen on host while model runs
  # on the accelerator. When run on CPU, makes data fecthing asynchronous.
  dataset = dataset.prefetch(buffer_size=prefetch_buffer_size)

  return dataset


def make_input_fn(file_pattern,
                  batch_size,
                  parsing_fn,
                  randomize_input=True,
                  num_epochs=None):

  def _input_fn():
    """Defines the input_fn."""

    dataset = build_ranking_dataset_with_parsing_fn(file_pattern=file_pattern, parsing_fn=parsing_fn,
                                                    batch_size=batch_size, reader=tf.data.TFRecordDataset,
                                                    num_epochs=num_epochs)

    features = tf.compat.v1.data.make_one_shot_iterator(dataset).get_next()
    label = features.pop('label')
    label = tf.cast(label, tf.float32)
    return features, label

  return _input_fn




"""

  Step2 Transform_fn

"""

# reference  https://github.com/shenweichen/DeepCTR
class SparseFeat(namedtuple('SparseFeat', ['name', 'dimension', 'use_hash', 'dtype','embedding_name','embedding'])):
    __slots__ = ()

    def __new__(cls, name, dimension, use_hash=False, dtype="int32", embedding_name=None,embedding=True):
        if embedding and embedding_name is None:
            embedding_name = name
        return super(SparseFeat, cls).__new__(cls, name, dimension, use_hash, dtype, embedding_name,embedding)


class VarLenSparseFeat(namedtuple('VarLenFeat', ['name', 'dimension', 'maxlen', 'combiner', 'use_hash', 'dtype','embedding_name','embedding'])):
    __slots__ = ()

    def __new__(cls, name, dimension, maxlen, combiner="mean", use_hash=False, dtype="float32", embedding_name=None,embedding=True):
        if embedding_name is None:
            embedding_name = name
        return super(VarLenSparseFeat, cls).__new__(cls, name, dimension, maxlen, combiner, use_hash, dtype, embedding_name,embedding)



context_fc = [VarLenSparseFeat('L_bid_his', 41192 + 1, maxlen=100, embedding_name='bid'),
            VarLenSparseFeat('L_inter_time', 41192 + 1, maxlen=100, embedding=False)]



context_fc_name = ['L_c1_his']

example_fc_name = ['id']


example_fc = [SparseFeat('id', 41192 + 1, embedding_name="id"),]


def build_input_features(feature_columns, mask_zero=True, prefix='', postfix='', fc_type='context'):
    input_features = OrderedDict()
    if fc_type == 'context':
        for fc in feature_columns:
            fc_name = fc.name + postfix
            if isinstance(fc,SparseFeat):
                input_features[fc_name] = Input(
                    shape=(1,), name=prefix+fc_name, dtype=fc.dtype)
            elif isinstance(fc,DenseFeat):
                input_features[fc_name] = Input(
                    shape=(fc.dimension,), name=prefix + fc_name, dtype=fc.dtype)
            elif isinstance(fc,VarLenSparseFeat):
                input_features[fc_name] = Input(shape=(fc.maxlen,), name=prefix + fc_name,
                                                dtype=fc.dtype)
                if not mask_zero:
                    input_features[fc_name + "_seq_length"] = Input(shape=(
                        1,), name=prefix + 'seq_length_' + fc_name)
                    input_features[fc_name + "_seq_max_length"] = fc.maxlen
            elif isinstance(fc,VarLenSparseMultiFeat):
                input_features[fc_name] = Input(shape=fc.dimension, name=prefix + fc_name,
                                                dtype=fc.dtype)
            else:
                raise TypeError("Invalid feature column type,got",type(fc))
    elif fc_type == 'examples':
        # [batch_size, list_size, feature_size]; keras Input Layer 
        for fc in feature_columns:
            fc_name = fc.name + postfix
            if isinstance(fc,SparseFeat):
                input_features[fc_name] = Input(
                    shape=(None,1,), name=prefix+fc_name, dtype=fc.dtype)
            elif isinstance(fc,DenseFeat):
                input_features[fc_name] = Input(
                    shape=(None, fc.dimension,), name=prefix + fc_name, dtype=fc.dtype)
            elif isinstance(fc,VarLenSparseFeat):
                input_features[fc_name] = Input(shape=(None, fc.maxlen,), name=prefix + fc_name,
                                                dtype=fc.dtype)
                if not mask_zero:
                    input_features[fc_name + "_seq_length"] = Input(shape=(
                        1,), name=prefix + 'seq_length_' + fc_name)
                    input_features[fc_name + "_seq_max_length"] = fc.maxlen
            elif isinstance(fc,VarLenSparseMultiFeat):
                input_features[fc_name] = Input(shape=tuple([None]+list(fc.dimension)), name=prefix + fc_name,
                                                dtype=fc.dtype)
            else:
                raise TypeError("Invalid feature column type,got",type(fc))
    else:
        raise TypeError("Invalid fc_type")
    return input_features



def encode_features(features, feature_columns,
                    mode=tf.estimator.ModeKeys.TRAIN,
                    scope=None, fc_type='context'):

  cols_to_tensors = OrderedDict()
  for fc in feature_columns:
    cols_to_tensors[fc] = features[fc]
  return cols_to_tensors


def encode_listwise_features(features,
                             context_feature_columns,
                             example_feature_columns,
                             input_size=None,
                             mode=tf.estimator.ModeKeys.TRAIN,
                             scope=None):

  context_features = {}
  if context_feature_columns:
      context_features = encode_features(features, context_feature_columns)

  example_features = {}
  if example_feature_columns:
    example_features = encode_features(features, example_feature_columns)

  return context_features, example_features


def make_transform_fn():
    """Returns a transform_fn that converts features to dense Tensors."""
    def _transform_fn(features, mode):
        """Defines transform_fn."""
        context_features, example_features = encode_listwise_features(
        features,
        context_feature_columns=context_fc_name,
        example_feature_columns=example_fc_name,
        mode=mode,
        scope="transform_layer")
        return context_features, example_features
    return _transform_fn




"""

  Step3: Score_fn

"""

def make_score_fn():
  """Returns a scoring function to build `EstimatorSpec`."""
  model = DIN(example_fc+context_fc, hist_len_max=100, dnn_use_bn=True,
              l2_reg_dnn=1e-5, l2_reg_embedding=1e-5, dnn_dropout=0.7)
  model.load_weights('./DIN_weights.h5')
  score = Model(inputs=model.input, outputs=model.get_layer("DENSE_logit").output)

  def _score_fn(context_features, group_features, mode, params, config):
    """Defines the network to score a group of documents."""
    # context_features: [batch_size, ....]
    # group_features: [batch_size, group_size, ...]

    for example_fea in group_features:
        group_features[example_fea] = tf.compat.v1.layers.flatten(group_features[example_fea])

    inputs_list = list(group_features.values()) + list(context_features.values())

    logits = score(inputs_list, training=(mode == tf.estimator.ModeKeys.TRAIN))
    update_ops = score.get_updates_for(inputs_list)
    # Hack to add BatchNorm update ops to graph
    for op in score.get_updates_for(inputs_list):
        if "batch_normalization" in op.name:
            tf.compat.v1.add_to_collection(name=tf.compat.v1.GraphKeys.UPDATE_OPS, value=op)
    return logits
  return _score_fn




"""
  Step4: Train & Evaluate
"""

def train_and_eval():
  """Train and Evaluate."""
  Train_data_path = './DATA'
  train_file_list = os.listdir(Train_data_path)
  train_file_list = [Train_data_path + '/' + i for i in train_file_list]

  train_input_fn = make_input_fn(train_file_list, batch_size=32, parsing_fn=parsing_fn)

  eval_input_fn = make_input_fn(train_file_list, batch_size=32, parsing_fn=parsing_fn,
                                randomize_input=False, num_epochs=1)
  
  optimizer = tf.compat.v1.train.AdagradOptimizer(
      learning_rate=0.00001)

  def _train_op_fn(loss):
    """Defines train op used in ranking head."""
    update_ops = tf.compat.v1.get_collection(tf.compat.v1.GraphKeys.UPDATE_OPS)
    minimize_op = optimizer.minimize(
        loss=loss, global_step=tf.compat.v1.train.get_global_step())
    train_op = tf.group([minimize_op, update_ops])
    return train_op

  ranking_head = tfr.head.create_ranking_head(
      loss_fn=tfr.losses.make_loss_fn("pairwise_logistic_loss",
          weights_feature_name="",
          lambda_weight=tfr.losses.create_ndcg_lambda_weight()),
      eval_metric_fns=eval_metric_fns(),
      train_op_fn=_train_op_fn)

  estimator = tf.estimator.Estimator(
      model_fn=tfr.model.make_groupwise_ranking_fn(
          group_score_fn=make_score_fn(),
          group_size=1,
          transform_fn=make_transform_fn(),
          ranking_head=ranking_head),
      model_dir="./out",
      config=tf.estimator.RunConfig(save_checkpoints_steps=1000).replace(session_config=session_config))

  train_spec = tf.estimator.TrainSpec(
      input_fn=train_input_fn, max_steps=100000)

  # exporters = tf.estimator.LatestExporter(
  #     "saved_model_exporter", serving_input_receiver_fn=make_serving_input_fn())

  eval_spec = tf.estimator.EvalSpec(
      name="eval",
      input_fn=eval_input_fn,
      steps=1,
      # exporters=exporters,
      start_delay_secs=0,
      throttle_secs=15)

  # Train and validate.
  tf.estimator.train_and_evaluate(estimator, train_spec, eval_spec)


`

**Comment by fly12357** [comment]
> @fly12357 : Can you share a minimal reproducible code snippet? Not adding update_ops will still run, but not have the effect of batch normalization.
> 
> This can also be an issue caused by tf.data based data reader. Take a look at this StackOverflow [issue](https://stackoverflow.com/questions/56612386/defining-the-input-function-for-tensorflow-pre-made-estimator/56615591#56615591).

## Input_fn
"""
  Step4: Train & Evaluate
"""

def train_and_eval():
  """Train and Evaluate."""
  Train_data_path = './DATA'
  train_file_list = os.listdir(Train_data_path)
  train_file_list = [Train_data_path + '/' + i for i in train_file_list]

  train_input_fn = make_input_fn(train_file_list, batch_size=32, parsing_fn=parsing_fn)

  eval_input_fn = make_input_fn(train_file_list, batch_size=32, parsing_fn=parsing_fn,
                                randomize_input=False, num_epochs=1)
  
  optimizer = tf.compat.v1.train.AdagradOptimizer(
      learning_rate=0.00001)

  def _train_op_fn(loss):
    """Defines train op used in ranking head."""
    update_ops = tf.compat.v1.get_collection(tf.compat.v1.GraphKeys.UPDATE_OPS)
    minimize_op = optimizer.minimize(
        loss=loss, global_step=tf.compat.v1.train.get_global_step())
    train_op = tf.group([minimize_op, update_ops])
    return train_op

  ranking_head = tfr.head.create_ranking_head(
      loss_fn=tfr.losses.make_loss_fn("pairwise_logistic_loss",
          weights_feature_name="",
          lambda_weight=tfr.losses.create_ndcg_lambda_weight()),
      eval_metric_fns=eval_metric_fns(),
      train_op_fn=_train_op_fn)

  estimator = tf.estimator.Estimator(
      model_fn=tfr.model.make_groupwise_ranking_fn(
          group_score_fn=make_score_fn(),
          group_size=1,
          transform_fn=make_transform_fn(),
          ranking_head=ranking_head),
      model_dir="./out",
      config=tf.estimator.RunConfig(save_checkpoints_steps=1000).replace(session_config=session_config))

  train_spec = tf.estimator.TrainSpec(
      input_fn=train_input_fn, max_steps=100000)

  eval_spec = tf.estimator.EvalSpec(
      name="eval",
      input_fn=eval_input_fn,
      steps=1,
      start_delay_secs=0,
      throttle_secs=15)

**Comment by ramakumar1729** [comment]
@fly12357 : Can you try with the following line inside _score_fn? 
```
score = Model(inputs=model.input, outputs=model.get_layer("DENSE_logit").output)
```

tf.Estimator API assumes all model related logic is defined inside the `model_fn`.

**Comment by fly12357** [comment]
> @fly12357 : Can you try with the following line inside _score_fn?
> 
> ```
> score = Model(inputs=model.input, outputs=model.get_layer("DENSE_logit").output)
> ```
> 
> tf.Estimator API assumes all model related logic is defined inside the `model_fn`.

Thanks for your help. That works~

**Comment by fly12357** [comment]
> @fly12357 : Can you try with the following line inside _score_fn?
> 
> ```
> score = Model(inputs=model.input, outputs=model.get_layer("DENSE_logit").output)
> ```
> 
> tf.Estimator API assumes all model related logic is defined inside the `model_fn`.

By the way, did my example update the batch_normalization?

**Comment by ramakumar1729** [comment]
@fly12357 : This migration guide has details on using Keras model to write a custom `model_fn`. (https://www.tensorflow.org/guide/migrate#using_a_custom_model_fn)

This is what you should use:
```
update_ops = score.get_updates_for(inputs_list) + scores.get_updates_for(None)
```

**Comment by fly12357** [comment]
> @fly12357 : This migration guide has details on using Keras model to write a custom `model_fn`. (https://www.tensorflow.org/guide/migrate#using_a_custom_model_fn)
> 
> This is what you should use:
> 
> ```
> update_ops = score.get_updates_for(inputs_list) + scores.get_updates_for(None)
> ```

Thanks a lot.
