### ISSUE TITLE
the training is slow because of the input processing

### ISSUE THREAD

**Issue by ChaosCY** [tensorflow/ranking#147]
Hello, I got a problem, I use the Dataset from_generator to read data from files, but maybe I have to construct a dict like the example. This part is too slow because of the transformation, I have no idea how to increase the speed, I have tried the parallel_interleave but useless.

**Comment by ramakumar1729** [comment]
@ChaosCY: You can take a look at tf.data performance guide.
https://www.tensorflow.org/guide/data_performance

**Comment by ChaosCY** [comment]
thanks
