### ISSUE TITLE
adding multiple features to example_feature_spec

### ISSUE THREAD

**Issue by kshitij91** [tensorflow/ranking#149]
Hi,

I am not able to add multiple features to example_feature_spec, can you help me out here?

` example_feature_spec = tf.feature_column.make_parse_example_spec(
        list(example_feature_columns().values()) + [label_column])`

should i go ahead and add my features here like :

`example_feature_spec = tf.feature_column.make_parse_example_spec(
        list(example_feature_columns().values()) + [label_column] + [feature_1] +[feature_2])`

Is this the correct approach or something else need to be done?

**Comment by ramakumar1729** [comment]
@kshitij91 : Please add new features to example_feature_columns. It will automatically parse them via example_feature_spec.

Let me know if you have any questions.

**Comment by kshitij91** [comment]
here is the code which i tried:
`def example_feature_columns():
  """Returns the example feature columns."""
  sparse_column = tf.feature_column.categorical_column_with_vocabulary_file(
      key="document_tokens",
      vocabulary_file=_VOCAB_PATH)
  document_embedding_column = tf.feature_column.embedding_column(
      sparse_column, _EMBEDDING_DIMENSION)
entropy_clicks = tf.feature_column.numeric_column(
        "entropy_clicks", dtype=tf.float32) 
  return {"document_tokens": document_embedding_column,"entropy_clicks":entropy_clicks}`


but it gives me this error:

`{{function_node __inference_Dataset_map_<class 'functools.partial'>_31613}} Name: <unknown>, Feature: clicks_entropy (data type: float) is required but could not be found.
	 [[{{node ParseExample/ParseExample}}]]
	 [[IteratorGetNext]]`

I have the field entropy_clicks in my ELWC tf record as an example feature. WHat i am doing wrong?

**Comment by ramakumar1729** [comment]
@kshitij91 : This looks like an error due to missing feature value. Using [default_value](https://www.tensorflow.org/api_docs/python/tf/feature_column/numeric_column?version=stable#args_2) field in feature column definition should do the trick.

**Comment by kshitij91** [comment]
@ramakumar1729 thanks, default_value field was missing, works fine now
