### ISSUE TITLE
Support for tensorflow gpu 

### ISSUE THREAD

**Issue by davemssavage** [tensorflow/ranking#15]
Currently the bazel build hardcodes the tensorflow dependency to the cpu version, it would be nice if this was configurable to support gpu builds.

Also I'm interested to know if you've benchmarked this library on tensorflow gpu and what the performance characteristics look like for different size data sets.

**Comment by davemssavage** [comment]
See https://github.com/tensorflow/ranking/pull/16

**Comment by ramakumar1729** [comment]
Hi Dave,

We have run using GPU and CPU versions, but haven't done the kind of benchmarking you have pointed out, which is definitely interesting to know. 

The dependency on tensorflow vs tensorflow-gpu occurs in the setup.py file. 
The way to support both GPU and CPU versions would be to have `tensorflow_ranking` and `tensorflow_ranking-gpu` packages installable via pip, each having a separate setup.py.

**Comment by NarasimhaM3101** [comment]
Could you clarify what changes we should do in tensorflow_ranking/tools/pip_package/build_pip_package.sh file along with setup.py?

**Comment by n3011** [comment]
@NarasimhaM3101  just change this lone https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/tools/pip_package/setup.py#L35 to `tensorflow-gpu >= 1.12.0`

**Comment by ramakumar1729** [comment]
Thanks for the fix, Ishant! We are planning to remove the dependency on tensorflow in the package, and ask the user to explicitly install tensorflow (or tensorflow-gpu). This will allow us to maintain one package on PyPI.

**Comment by ramakumar1729** [comment]
The user is expected to install `tensorflow` or `tensorflow-gpu` manually before installing `tensorflow-ranking`.The README is updated to reflect this. Closing this for now. Please feel free to reopen if they are any issues.

**Comment by iamhere1** [comment]
I installed tensorflow-gpu(v1.13.1)  and tensorflow ranking by pip command. But when I run the training process,  the GPU is actually not used.  The code I used is as following, is there any problem?
  config_proto = tf.ConfigProto(log_device_placement=False,
                                  allow_soft_placement=False)
    config_proto.gpu_options.per_process_gpu_memory_fraction = 0.6
    run_config = tf.estimator.RunConfig(model_dir=config.model_dir,
                                        save_summary_steps=config.log_steps,
                                        save_checkpoints_steps=config.checkpoints_steps,
                                        keep_checkpoint_max=config.keep_checkpoint_max,
                                        session_config=config_proto,
                                        log_step_count_steps=config.log_steps
                                        )
    return tf.estimator.Estimator(
        model_fn=tfr.model.make_groupwise_ranking_fn(
            group_score_fn=make_score_fn(),
            group_size=config.group_size,
            transform_fn=None,
            ranking_head=ranking_head),
        config=run_config,
        params={'hidden_units': hidden_units_list,
                'drop_out': config.drop_out,
                'drop_rates': drop_rates_list,
                'group_size': config.group_size,
                'num_features': config.num_features,
                'l2_reg': config.l2_reg,
                'batch_norm': config.batch_norm}
    )

**Comment by mulangonando** [comment]
hi @iamhere1 , did you get any solution to this problem? I have tried to install the library by all means but still, my nvidia-smi command does not list my process id
