### ISSUE TITLE
Understanding prediction scores

### ISSUE THREAD

**Issue by felipeacunago** [tensorflow/ranking#150]
Hi everyone,

First of all thanks for this great library. I have been struggling trying to understand how prediction scores work.

For example I just edited the jupyter "handling_sparse_features" and added these lines of code:

````
_EVAL_DATA_PATH = "/tmp/eval.tfrecords"

ELWC = text_format.Parse(
    """
    context {
      features {
        feature {
          key: "query_tokens"
          value { bytes_list { value: ["this", "is", "a", "relevant", "question"] } }
        }
      }
    }
    examples {
      features {
        feature {
          key: "document_tokens"
          value { bytes_list { value: ["this", "is", "a", "relevant", "answer"] } }
        }
        feature {
          key: "relevance"
          value { int64_list { value: 1 } }
        }
      }
    }
    examples {
      features {
        feature {
          key: "document_tokens"
          value { bytes_list { value: ["irrelevant", "data"] } }
        }
        feature {
          key: "relevance"
          value { int64_list { value: 0 } }
        }
      }
    }""", input_pb2.ExampleListWithContext())


with tf.io.TFRecordWriter(_EVAL_DATA_PATH) as writer:
    for elwc in [ELWC]:
        print(elwc)
        writer.write(elwc.SerializeToString())

predictions = ranker.predict(input_fn=lambda: predict_input_fn("/tmp/eval.tfrecords"))
predict_data = predict_input_fn("/tmp/eval.tfrecords")

x = next(predictions)
print(x)
````

And I'm getting this:

[-6.055792  -7.013752   0.4728475  0.4728475  0.4728475  0.4728475
  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475
  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475
  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475
  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475
  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475
  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475
  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475  0.4728475
  0.4728475  0.4728475]

Does that mean that the document with this info:
value { bytes_list { value: ["this", "is", "a", "relevant", "answer"] } }
has a score of -6.055792
and the one with
value { bytes_list { value: ["irrelevant", "data"] } }
has a score of -7.013752

My intuition would be that the first document should have a positive value, and the second one a negative, so this result doesn't make sense and I'm doing something wrong.
Or maybe is it because it's simply not generalizing?. Besides that, why I'm getting on the padding data some positive value?

You can check this in this colab https://colab.research.google.com/drive/1tRwyzL7sssS8xxbLvBpxDuDwQr9tauxA.
Thanks!, sorry for the newbish question :)

**Comment by ramakumar1729** [comment]
@felipeacunago : If you look the scoring function, it does not force the scores to be non-negative. You can add this constraint by passing the final scores through a sigmoid transformation. 

The scores for padded entries should be neglected. They are based on default feature values. This is a good point, and we will look at what an appropriate default value is.

**Comment by felipeacunago** [comment]
> @felipeacunago : If you look the scoring function, it does not force the scores to be non-negative. You can add this constraint by passing the final scores through a sigmoid transformation.
> 
> The scores for padded entries should be neglected. They are based on default feature values. This is a good point, and we will look at what an appropriate default value is.

Thanks!, got it now :)

**Comment by ramakumar1729** [comment]
Glad to help! Closing this for now.
