### ISSUE TITLE
AttributeError: 'ParallelInterleaveDataset' object has no attribute 'output_types'

### ISSUE THREAD

**Issue by nscozzaro** [tensorflow/ranking#152]
I get an error when I run the notebook:
`AttributeError: 'ParallelInterleaveDataset' object has no attribute 'output_types'`

![image](https://user-images.githubusercontent.com/15185105/71773330-73baad80-2f29-11ea-9228-68ed826b9c23.png)

**Comment by lyyanlely** [comment]
I had the same problem.
It appears to be because of the deprecation of the output_types property of the Dataset class in TF 2.x
Replacing `dataset.output_types` on line 803 in data.py with `tf.compat.v1.data.get_output_types(dataset)` might let it work for now.

**Comment by ramakumar1729** [comment]
@lyyanlely : Thanks for the suggestion, that should address the problem. I'll send out a commit for this.

**Comment by ramakumar1729** [comment]
This issue is fixed in [release v0.2.2](https://github.com/tensorflow/ranking/releases/tag/v0.2.2).
