### ISSUE TITLE
Can't install on macOS 

### ISSUE THREAD

**Issue by siamakz** [tensorflow/ranking#155]
Hi,

I am not able to install TensorFlow Ranking (error: no matching distribution). My specifications:

macOS Catalina (10.15.2)
TensorFlow 2.1.0
Python 3.6.8

Is it compatible with TF 2.1?

**Comment by Wentong-DST** [comment]
Hi @siamakz ,
TensorFlow 2.1.0 was released after TensorFlow Ranking 0.2.1 (the latest version), so I think they wouldn't be compatible.
Maybe you can try TensorFlow 2.0.0 instead, or wait for the next release of the TensorFlow Ranking package.
Hope it helps.

**Comment by ramakumar1729** [comment]
@siamakz : We have released TFR v0.2.2, which is compatible with TF 2.1.0. Can you try installing again?

**Comment by siamakz** [comment]
Hi @Wentong-DST and @ramakumar1729 

Actually I was able to install TFR v0.2.1 with with TF 2.0.0 within PyCharm Community Edition. I will look into upgrading to 0.2.2 too. 

Thanks for your response!

**Comment by Wentong-DST** [comment]
Hi @siamakz ,

Glad it helps 😃 . The authors released new version pretty fast 👍

**Comment by ramakumar1729** [comment]
Glad it works, and thanks everyone for the discussion! Closing this issue. Feel free to reopen if there are any further issues with installation on macOS.
