### ISSUE TITLE
Slow training due to tf.gather

### ISSUE THREAD

**Issue by eladBenedict** [tensorflow/ranking#160]
Hi,

We, at Taboola, are working on implementing a learning-to-rank model, with your framework, for our large scale production environment.

For small batch sizes (e.g. 32) the number of steps/sec during training is reasonable. However, it seems to grow significantly as the batch size grows. For example, processing a single batch of size 256 takes a few seconds(!).

Running profiling, it seems that the issue is in [tf.gather] (https://github.com/tensorflow/ranking/blob/a6fcfa2ab5a17e3e112dceb18e628ab1593385ba/tensorflow_ranking/python/model.py#L364)

Attached are:
1. The profiling json (renamed from .json to .txt due to upload restrictions)
2. A screenshot of the presumably problematic op in the profiling session

The profiling screenshot:
![image (5)](https://user-images.githubusercontent.com/11731485/73085519-7e88b280-3ed7-11ea-9377-c7cb76b1a4cb.png)

The profiling timeline:
[timeline-560-128.txt](https://github.com/tensorflow/ranking/files/4109481/timeline-560-128.txt)

Just for some context, in this scenario list_size=4 and group_size=1.

Is this a known issue?
Please advise.

Cheers, and thanks for the great framework!
Elad

**Comment by xuanhuiwang** [comment]
@eladBenedict Thanks for providing this feedback to us and spot a problem. I am wondering whether replacing the gather by the following ops would resolve your issue.

# Constructs the multiples [1, num_groups, 1, ...].
multiples = tf.tensor_scatter_nd_update(tf.ones_like(tf.shape(value), tf.int32), [[1]], [num_groups])
# Use tf.tile to duplicate.
value = tf.tile(input=value, multiples=multiples)

Let use know if you have any updates. If this works, we should incorporate this change in our code.

**Comment by eladBenedict** [comment]
Thanks a lot @xuanhuiwang, that works!
100 batches now take <4 seconds and not >200 as before. 

BTW, if you're going to incorporate this, any chance you can do so to previous versions as well?
I'm asking since we're building against 0.1.5.

Thanks again!
Elad

**Comment by xuanhuiwang** [comment]
@eladBenedict, Great to know that helps.

I am not sure how to patch this change to an existing package like 0.1.5. We will update our code and incorporate this change in our future version.

**Comment by xuanhuiwang** [comment]
Looks that tf provide tf.repeat now. You may try this as well.

We have update our code at https://github.com/tensorflow/ranking/commit/2c6d3465e31921b581aedfa118c397ac5b3b24dd. This will be included in the next release.

**Comment by xuanhuiwang** [comment]
Close for now. Feel free to reopen.
