### ISSUE TITLE
Using TFR for Ecommerce data. 

### ISSUE THREAD

**Issue by NidhiRustagi** [tensorflow/ranking#161]
Problem with dataset.map() using functools.partial()
I have created the dataset for TensorFLow ranking in ELWC format and saved the file as .tfrecords file.
Copied get_descriptor_set(), decode_as_serialized_example_list() and parse() method as it is,
Modified context_spec and example_spec as per my dataset.

If I try and parse the dataset simply using a for loop it works:
raw_dataset = tf.data.TFRecordDataset(_FILE_NAME)
    for r in raw_dataset:
        features = parse(r, context_spec, example_feature_spec)
        print(features)

Output:
{'NIA_Paid_Status': <tensorflow.python.framework.sparse_tensor.SparseTensor object at 0x000001CACA6DD7F0>, 'Amount': <tf.Tensor: id=183, shape=(2, 1), dtype=int64, numpy=
array([[   0],
       [2266]], dtype=int64)>, 'Buyerid': <tf.Tensor: id=184, shape=(2, 1), dtype=int64, numpy=
array([[1222],
       [1734]], dtype=int64)>, 'NIA_Commission': <tf.Tensor: id=185, shape=(2, 1), dtype=int64, numpy=
array([[   0],
       [2268]], dtype=int64)>, 'rank': <tf.Tensor: id=186, shape=(2, 1), dtype=int64, numpy=
array([[0],
       [4]], dtype=int64)>}

Problem is
parsing_func = functools.partial(parse, **kwargs)
raw_dataset = tf.data.TFRecordDataset(_FILE_NAME).map(parsing_func)

results in warning
tensorflow:Entity <bound method DescriptorBase.GetOptions of <google.protobuf.descriptor.Descriptor object at 0x000001CAC0F7F550>> could not be transformed and will be executed as-is. Please report this to the AutoGraph team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output. Cause: LIVE_VARS_IN
and the error:
TypeError: in converted code:

    <ipython-input-8-63996b0b1f58>:31 parse  *
        features[k] = utils.reshape_first_ndims(v, 1, [batch_size, cur_list_size])
    C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_ranking\python\utils.py:173 reshape_first_ndims  *
        new_shape = tf.concat([new_shape, tf.shape(input=tensor)[first_ndims:]], 0)
    C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\util\dispatch.py:180 wrapper
        return target(*args, **kwargs)
    C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\ops\array_ops.py:1431 concat
        return gen_array_ops.concat_v2(values=values, axis=axis, name=name)
    C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\ops\gen_array_ops.py:1256 concat_v2
        "ConcatV2", values=values, axis=axis, name=name)
    C:\Users\hp\Anaconda3\lib\site-packages\tensorflow_core\python\framework\op_def_library.py:499 _apply_op_helper
        raise TypeError("%s that don't all match." % prefix)

    TypeError: Tensors in list passed to 'values' of 'ConcatV2' Op have types [<NOT CONVERTIBLE TO TENSOR>, int32] that don't all match.

What am I doing wrong?

**Comment by xuanhuiwang** [comment]
Is this still a problem? Why not use the function provided by the library?

**Comment by xuanhuiwang** [comment]
Closing this now. Feel free to reopen.

**Comment by NidhiRustagi** [comment]
Hi Many Thanks for the response. No I managed to work around the problem.
Sorry I missed  your earlier response.

Best Regards
Nidhi

**Comment by xuanhuiwang** [comment]
No problem. Glad to know that you resolved the issue. Let us know if you have other questions.

Also, if you found TFR useful in your product, we are happy to know your use case! Thanks!
