### ISSUE TITLE
Tensorflow Ranking Workshop (Mountain View, California, March 18th, 2020)

### ISSUE THREAD

**Issue by bendersky** [tensorflow/ranking#162]
Dear Tensorflow Ranking users,

We are pleased to invite you to the first Tensorflow Ranking Workshop on Wednesday, March 18th, 2020 at the Google campus in Mountain View, California. The full-day workshop will center around applications of Tensorflow Ranking in real-life industry and academic settings.  We will also provide a preview of several new capabilities that we have been working on at Google during the past six months for Tensorflow Ranking and for machine learning in general. In addition to speakers from several Google teams, the workshop will feature speakers from a variety of different organizations, including Walmart Labs, Santa Clara University, LinkedIn, GrubHub, Rakuten Institute of Technology, and Stanford.

If you would like to attend, please register using [this form](https://docs.google.com/forms/d/e/1FAIpQLSeijd-UzyySkrff44ms46B1VJUAKkJig-GKO-Nuz14OphGnpw/viewform?usp=sf_link). 

_**Help us spread the word!**_ Forward this announcement to your friends and colleagues who might be interested in attending the event. Seats at the workshop will be allocated on a first-come, first-serve basis.

Warm regards,
Tensorflow Ranking Team
For any questions, email us at tfranking2020@googlegroups.com

Please cut and paste the following link into your browser if you encounter difficulty accessing the registration form page: 
https://docs.google.com/forms/d/e/1FAIpQLSeijd-UzyySkrff44ms46B1VJUAKkJig-GKO-Nuz14OphGnpw/viewform?usp=sf_link

**Comment by bendersky** [comment]
The registration is now closed. Thanks to everyone who signed up, and see you in Mountain View

**Comment by anuragreddygv323** [comment]
is it still on considering the coronavirus ?

**Comment by LiangqunLu** [comment]
Is it possible to attend the workshop online? I mean by then
