### ISSUE TITLE
handling_sparse_features.ipynb doc link url error .

### ISSUE THREAD

**Issue by 283222278** [tensorflow/ranking#164]
ExampleListWithContext protbuffer is defined [here](https:https://github.com/tensorflow/serving/blob/master/tensorflow_serving/apis/input.proto#L72).

this url error

**Comment by ramakumar1729** [comment]
Thanks for pointing this out. I'll send out a fix.

**Comment by ramakumar1729** [comment]
This is fixed now. Please check at [git.io/tf-ranking-demo](git.io/tf-ranking-demo).
