### ISSUE TITLE
GPU utilization is low

### ISSUE THREAD

**Issue by dartrevan** [tensorflow/ranking#165]
tensorflow version: 2.0.0-beta1
cuda version: 10.0
cudnn: 7
ubuntu 18.04
GPU: Nvidia Tesla P40

The GPU utility is very low when I run the tf_ranking_libsvm.py script in the examples directory. 

During running a lot of warning messages is received (examples are provided below)
<img width="1680" alt="Снимок экрана 2020-02-07 в 15 21 25" src="https://user-images.githubusercontent.com/24587263/74031894-bc033a80-49c3-11ea-9a5b-cf1f7e75d764.png">

<img width="1680" alt="Снимок экрана 2020-02-07 в 15 55 10" src="https://user-images.githubusercontent.com/24587263/74031801-85c5bb00-49c3-11ea-87ed-e2b0f2cb1e95.png">
<img width="1680" alt="Снимок экрана 2020-02-07 в 15 57 20" src="https://user-images.githubusercontent.com/24587263/74031813-8eb68c80-49c3-11ea-9616-9631daaaf12b.png">

<img width="1680" alt="Снимок экрана 2020-02-07 в 15 57 43" src="https://user-images.githubusercontent.com/24587263/74031929-ca515680-49c3-11ea-8c55-a6d69c912a2c.png">

Warning in the second and third images arise all the time model_fn is called.

**Comment by ramakumar1729** [comment]
Can you try with [tf_ranking_tfrecord.py](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_tfrecord.py)?

**Comment by xuanhuiwang** [comment]
close due to inactivity. feel free to reopen.
