### ISSUE TITLE
Cannot add AUC in the metrics

### ISSUE THREAD

**Issue by LiangqunLu** [tensorflow/ranking#168]
Hi I am trying to add the metric AUC in the get_eval_metric-fns(). However, it is not working.

```
metric_fns = {}
metric_fns.update({'metric/AUC': tf.keras.metrics.AUC})

# or 
metric_fns.update({'metric/AUC': tf.metrics.auc})
```

This is the error messages:
File "/home/liangqun/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_ranking/python/head.py", line 250, in create_estimator_spec
    for name, metric_fn in six.iteritems(self._eval_metric_fns)
  File "/home/liangqun/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_ranking/python/head.py", line 250, in <dictcomp>
    for name, metric_fn in six.iteritems(self._eval_metric_fns)
TypeError: __init__() got an unexpected keyword argument 'labels'

tf.compat.v1.metrics.auc
File "/home/liangqun/anaconda3/envs/tf/lib/python3.6/site-packages/tensorflow_core/python/util/deprecation.py", line 324, in new_func
    return func(*args, **kwargs)
TypeError: auc() got an unexpected keyword argument 'features'

Is there someone who knows how to add AUC? Thanks!

**Comment by LiangqunLu** [comment]
I got an idea from the ipython notebook example. And I finally solved the issue. In case someone wants to have a look, I paste my code here.

'''python
from tensorflow.python.ops.metrics_impl import auc

def Calculate_AUC(labels, predictions, features):
    is_label_valid = tf.reshape(tf.greater_equal(labels, 0.), [-1, 1])
    #is_label_valid = tf.reshape(tf.cond(tf.greater_equal(labels, 0.), ))
    clean_labels = tf.boolean_mask(tf.reshape(labels, [-1, 1]), is_label_valid)
    clean_pred = tf.boolean_mask(tf.reshape(predictions, [-1, 1]), is_label_valid)
  
    return auc(clean_labels, tf.sigmoid(clean_pred))

metric_fns.update({'metric/AUC': Calculate_AUC})
'''

**Comment by xuanhuiwang** [comment]
Yes, this looks right.
