### ISSUE TITLE
Parsing large Documents (tokens)

### ISSUE THREAD

**Issue by eggie5** [tensorflow/ranking#170]
Wondering if anyone else has come across this: I have a similar setup to the ANTIQUE example w/ sparse features. The only difference is that my documents are MUCH larger, for example most are > 500 words and I am using the `SequenceExample` format. The problem is, when I go to load the data using `tfr.data.build_ranking_dataset` it becomes VERY slow. I ran the TF profiler (see screenshot) and it seems like the pipeline is getting stuck on a `DeserializeSparse` op which corresponds to the `doc` `VarLenFeature` below:

    context_feature_spec = {"query_text": tf.FixedLenFeature((1,), dtype=tf.string)}
    example_feature_spec = {"doc": tf.VarLenFeature(dtype=tf.string),
                            "rel": tf.FixedLenFeature((1,), dtype=tf.int64, default_value=(-1,))}

![chrome___tracing](https://tva1.sinaimg.cn/large/0082zybpgy1gc9d6ob4xnj31ak0k878h.jpg)

One thing I noticed is, that if I change `"doc": tf.VarLenFeature` to `FixedLenFeature` (parse a string of words instead an array of words) and change my feature job to write a string instead of array of tokens in the TF Records, then parsing is very fast (but then I have to tokenize the string using a dataset map which is slow too). Seems like the issue is parsing the a large`VarLenFeature` to a `SparseTensor`.

Of course decreasing my batch size, causes the `DeserializeSparse` to run faster, but I lose overall throughput. 

Any tips on how to speed this up?

**Comment by ramakumar1729** [comment]
@eggie5 : Here are a few suggestions:

1. Better `tf.data` performance: Take a look at this [guide](https://www.tensorflow.org/guide/data_performance).

2. Replace `tf.VarLenFeature` with `tf.FixedLenFeature([seq_length])`, and tune `seq_length` as a parameter for accuracy/ speed trade-off. [BERT's input_fn](https://github.com/google-research/bert/blob/f39e881b169b9d53bea03d2d341b31707a6c052b/run_classifier.py#L514) is a reference for doing this. Also, you can preprocess your tokens to be integer IDs for faster parsing.

Hope this helps. Let me know if you have any questions.

**Comment by eggie5** [comment]
Thanks @ramakumar1729, this was probably the intuition I was looking for: treating sequence length as a hyper parameter. I'll read though that BERT example you sent. 

Also, as you suggested, I considered moving more work to preprocessing and just putting token ids in the dataset. This would probably work, but for my case I want to avoid moving too much logic to the client (for runtime considerations).

**Comment by eggie5** [comment]
Follow-up: using a `FixedLenFeature` w/ a fixed `seq_length` fixes my computation issue.

**Comment by ramakumar1729** [comment]
Sounds great, @eggie5 . Thanks for following up and sharing the solution. Closing this for now.
