### ISSUE TITLE
How to convert from libsvm to tfrecord files?

### ISSUE THREAD

**Issue by LiangqunLu** [tensorflow/ranking#174]
This question may be silly, but I do not actually figure out. When I try to utilize the pipeline script from the new extension folder, the input should be .tfrecord but I used libsvm format all the time. Is there a script that I can generate tfrecord from the libsvm data, just like the conversion between example data train.txt to train_elwc.tfrecord? Thanks!

**Comment by xuanhuiwang** [comment]
You may want to take a look at this example: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/extension/pipeline_test.py#L30.

**Comment by LiangqunLu** [comment]
Thanks to your reply. @xuanhuiwang .
Actually I figured out the step from ELWC to tfrecord in your referred code where [ELWC] was saved into tfrecord files.

Well, the process from the libsvm to ELWC is not straightforward to me. For the example of the following Libsvm format:

![image](https://user-images.githubusercontent.com/10750332/76571292-5ef01e00-6474-11ea-96e8-8a0b41beab14.png)

And the ELWC format:

```python
In [266]: ELWC                                                                                                            
Out[266]: 
examples {
  features {
    feature {
      key: "doc_weight"
      value {
        float_list {
          value: 0.5
        }
      }
    }
    feature {
      key: "document_tokens"
      value {
        bytes_list {
          value: "this"
          value: "is"
          value: "a"
          value: "relevant"
          value: "answer"
        }
      }
    }
    feature {
      key: "relevance"
      value {
        int64_list {
          value: 1
        }
      }
    }
  }
}
examples {
  features {
    feature {
      key: "doc_weight"
      value {
        float_list {
          value: 2.0
        }
      }
    }
    feature {
      key: "document_tokens"
      value {
        bytes_list {
          value: "irrelevant"
          value: "data"
        }
      }
    }
    feature {
      key: "relevance"
      value {
        int64_list {
          value: 0
        }
      }
    }
  }
}
context {
  features {
    feature {
      key: "query_tokens"
      value {
        bytes_list {
          value: "this"
          value: "is"
          value: "a"
          value: "relevant"
          value: "question"
        }
      }
    }
  }
}

```
It is quite difficult for me to convert right now from the LibSVM matrix to ELWC format.
Do you happen to have the script for the conversion? Thanks!

**Comment by LiangqunLu** [comment]
I had quite limited experience on the tfrecord files while it is kind of urgent for my project to generate the tfrecord files and run on the pipeline. So I read the data, data_test, pipeline, piepline_test scripts these days and I think I am close to finish the format conversion between LibSVM and ELWC-tfrecord.

ExampleListWithContext -- ELWC; the format of ELWC is like below.

```python
ELWC = text_format.Parse(
    """
    context {
      features {
        feature {
          key: "query_tokens"
          value { bytes_list { value: ["this", "is", "a", "relevant", "question"] } }
        }
      }
    }
    examples {
      features {
        feature {
          key: "document_tokens"
          value { bytes_list { value: ["this", "is", "a", "relevant", "answer"] } }
        }
        feature {
          key: "relevance"
          value { int64_list { value: 1 } }
        }
        feature {
          key: "doc_weight"
          value { float_list { value: 0.5 } }
        }
      }
    }
    examples {
      features {
        feature {
          key: "document_tokens"
          value { bytes_list { value: ["irrelevant", "data"] } }
        }
        feature {
          key: "relevance"
          value { int64_list { value: 0 } }
        }
        feature {
          key: "doc_weight"
          value { float_list { value: 2.0 } }
        }
      }
    }""", input_pb2.ExampleListWithContext())

#https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb#scrollTo=Wml7IFUP0XoM
"""
examples {
  features {
    feature {
      key: "document_tokens"
      value {
        bytes_list {
          value: "this"
          value: "is"
          value: "a"
          value: "relevant"
          value: "answer"
        }
      }
    }
    feature {
      key: "relevance"
      value {
        int64_list {
          value: 5
        }
      }
    }
  }
}
examples {
  features {
    feature {
      key: "document_tokens"
      value {
        bytes_list {
          value: "irrelevant"
          value: "data"
        }
      }
    }
    feature {
      key: "relevance"
      value {
        int64_list {
          value: 1
        }
      }
    }
  }
}
context {
  features {
    feature {
      key: "query_tokens"
      value {
        bytes_list {
          value: "this"
          value: "is"
          value: "a"
          value: "relevant"
          value: "question"
        }
      }
    }
  }
}
"""
# one example of context feature and example feature lists like this
# https://medium.com/mostly-ai/tensorflow-records-what-they-are-and-how-to-use-them-c46bc4bbb564
"""
context {
  feature {
    key: "Age"
    value {
      int64_list {
        value: 19
      }
    }
  }
  feature {
    key: "Favorites"
    value {
      bytes_list {
        value: "Majesty Rose"
        value: "Savannah Outen"
        value: "One Direction"
      }
    }
  }
  feature {
    key: "Locale"
    value {
      bytes_list {
        value: "pt_BR"
      }
    }
  }
}
feature_lists {
  feature_list {
    key: "Movie Actors"
    value {
      feature {
        bytes_list {
          value: "Tim Robbins"
          value: "Morgan Freeman"
        }
      }
      feature {
        bytes_list {
          value: "Brad Pitt"
          value: "Edward Norton"
          value: "Helena Bonham Carter"
        }
      }
    }
  }
  feature_list {
    key: "Movie Names"
    value {
      feature {
        bytes_list {
          value: "The Shawshank Redemption"
        }
      }
      feature {
        bytes_list {
          value: "Fight Club"
        }
      }
    }
  }
  feature_list {
    key: "Movie Ratings"
    value {
      feature {
        float_list {
          value: 9.0
        }
      }
      feature {
        float_list {
          value: 9.699999809265137
        }
      }
    }
  }
}
"""
```

So I wrote the script like below from LibSVM to data matrix to ELWC to tfrecord files

"""python
import functools
import numpy as np
import pandas as pd
import six

import tensorflow as tf
#from tensorflow.contrib.data.python.ops import interleave_ops
from tensorflow.python.data.ops import dataset_ops
from tensorflow.python.data.ops import readers
from tensorflow.python.framework import dtypes
from tensorflow.python.framework import sparse_tensor
from tensorflow.python.ops import array_ops
from tensorflow.python.ops import control_flow_ops
from tensorflow.python.ops import math_ops
from tensorflow.python.ops import parsing_ops
from tensorflow.python.ops import sparse_ops
from tensorflow.python.estimator.export import export as export_lib


from google.protobuf import text_format
from tensorflow_ranking.python import data as data_lib
from tensorflow_serving.apis import input_pb2
# The document relevance label.
_LABEL_FEATURE = "label"

# Padding labels are set negative so that the corresponding examples can be
# ignored in loss and metrics.
_PADDING_LABEL = -1.



def ReadInput_Groups(path, num_features = 399):
    
    X = []
    Y = []
    qids =[]

    f = open(path, "rt")
    for line in f:
        tokens = line.split("#")[0].split()
        label = int(tokens[0])
        qid = tokens[1].replace("qid:", "")
        kv_pairs = [kv.split(":") for kv in tokens[2:]]
        features = {int(k): float(v) for (k, v) in kv_pairs}
        
        feature_map = {(i+1):0 for i in range(num_features)}
    
        for k, v in feature_map.items():
            
            if k in features:
                feature_map[k] = features[k]
            
        X.append(feature_map.values())
        Y.append(label)
        qids.append(qid)
    
    f.close() 
        
    dfX = pd.DataFrame(X, columns = [ "x" + str(i) for i in range(num_features)] )
    #dfX = np.nan_to_num(dfX)
    dfX = dfX.fillna(0)
    
    dfY = pd.DataFrame(Y)
    
    dfgroup = pd.DataFrame(qids)
    #dfX = np.array(dfX)
    #dfY = np.array(Y).astype(np.int32)
      
    return dfX, dfY, dfgroup
  
def generate_tfrecord(train_path):
  
  dfX, dfY, dfgroup = ReadInput_Groups(train_path)
  filename = train_path.replace(".txt", ".tfrecord")
  
  total = int(dfgroup.iloc[-1, 0])
  serialized = []

  #filename = "test.tfrecord"
  writer = tf.io.TFRecordWriter(filename)
  for start in range(total):

    # get index of documents 
    #i = 0
    index = dfgroup.index[dfgroup.iloc[:, 0] == str(start)].tolist()
    subdfX = dfX.iloc[index, :]
    subdfY = dfY.iloc[index, :]

    context_feature = {
        "query_tokens" : tf.train.Feature(float_list = tf.train.FloatList(value=subdfX.iloc[0, :128]) ) #subdfX.iloc[0, 0]
        }

    context_proto = tf.train.Features(feature=context_feature)

    # item features
    item_features = []
    relevance = []
    #num = 0
    for num in range(subdfX.shape[0]):

      item_feature = tf.train.Feature(float_list=tf.train.FloatList(value=subdfX.iloc[num, 128:])) #
      item_features.append(item_feature)

      rel = tf.train.Feature(float_list = tf.train.FloatList(value=subdfY.iloc[num, :].tolist() ))
      relevance.append(rel)

    item_features =  tf.train.FeatureList(feature=item_features )
    relevance = tf.train.FeatureList(feature=relevance )

    items = tf.train.FeatureLists(feature_list={
      'document_tokens': item_features,
      'relevance': relevance
  })

    # Create the SequenceExample
    example = tf.train.SequenceExample(context=context_proto, feature_lists=items)

    #serialized.append(example.SerializeToString())
    #print(example)
    writer.write(example.SerializeToString())

  writer.close()

#
train_path = "example.txt"
generate_tfrecord(train_path)
"""

However, I found an error when I saved SerializeToString where it looks not right because of question marks. Well, this is confusing to me. 

```python
example.SerializeToString()
Out[210]: b'\n\x1a\n\x18\n\x0cquery_tokens\x12\x08\x12\x06\n\x04\x00\x00\x80?\x12\x9c\x01\nO\n\x0fdocument_tokens\x12<\n\x08\x12\x06\n\x04\x00\x00\x80?\n\x08\x12\x06\n\x04\x00\x00\x80?\n\x08\x12\x06\n\x04\x00\x00\x80?\n\x08\x12\x06\n\x04\x00\x00\x80?\n\x08\x12\x06\n\x04\x00\x00\x80?\n\x08\x12\x06\n\x04\x00\x00\x80?\nI\n\trelevance\x12<\n\x08\x12\x06\n\x04\x00\x00\x80?\n\x08\x12\x06\n\x04\x00\x00\x80?\n\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x08\x12\x06\n\x04\x00\x00\x00\x00\n\x08\x12\x06\n\x04\x00\x00\x00\x00'

```

Is there some one else who has the same issue or help me check out my code? Thanks!

**Comment by hanshuguang-google** [comment]
Based on https://www.tensorflow.org/tutorials/load_data/tfrecord, "_The TFRecord format is a simple format for storing a sequence of binary records_". It just tells the file system to store the data in binary.

ELWC and tf.Example is a protobuf that indicates what the data structure look like. In the case of tf.Example, it tells that my data is stored in {"string": value} mapping. See more details here:
https://www.tensorflow.org/tutorials/load_data/tfrecord.

In your case, I would suggest you using ELWC format (instead of SequenceExample as the Pipeline does not quite support SequenceExample). Please see the following as a templated example 

from tensorflow_serving.apis import input_pb2

elwc = input_pb2.ExampleListWithContext()

context_feature_dict = { 
  'query_tokens': tf.train.Feature(float_list = tf.train.FloatList(value=[1.0, 2.0]))
}
context_feature = tf.train.Example(features=tf.train.Features(feature=context_feature_dict))
elwc.context.CopyFrom(context_feature)

for doc in docs:
  example_feature_dict = {
    'document_tokens': tf.train.Feature(int64_list=tf.train.Int64List(value=[1,2])),
    'relevance': tf.train.Feature(int64_list=tf.train.Int64List(value=[1]))
  }
  example_feature = tf.train.Example(features=tf.train.Features(feature=example_feature_dict)) 
  elwc.examples.add().CopyFrom(d)

# After you got elwc, you can then write the data with
writer.write(elwc.SerializeToString())

**Comment by Pascal-Iv** [comment]
> ```python
> elwc.examples.add().CopyFrom(d)
> ```
What is d? NameError...

**Comment by dazcona** [comment]
> > ```python
> > elwc.examples.add().CopyFrom(d)
> > ```
> 
> What is d? NameError...

I replaced `d` with `example_feature`

**Comment by supercar1** [comment]
Hi @LiangqunLu , thanks for sharing your code of how to convert a libsvm file to tfrecord :)

I was trying to use it, however when I reach the `    context_feature = {
        "query_tokens" : tf.train.Feature(float_list = tf.train.FloatList(value=subdfX.iloc[0, :128]) ) #subdfX.iloc[0, 0]
        }` part, I get the error: `IndexError: single positional indexer is out-of-bounds`, for any number of features that I use.

Did you face the same problem?
