### ISSUE TITLE
How can I use a `tf.feature_column.crossed_column`?

### ISSUE THREAD

**Issue by eggie5** [tensorflow/ranking#175]
How can I use a `tf.feature_column.crossed_column`? I want to cross a sparse context and group feature `query_terms` and `doc_terms` respectively. However, I'm not sure how to model this w/ TFR b/c it breaks features down into 2 groups: context and group/example features. However, this is a context/group feature. I think it boils down to how do I handle it in the `transform_fn`?

```
def make_transform_fn():
    def _transform_fn(features, mode):
        
        context_features, example_features = tfr.feature.encode_listwise_features(
            features=features,
            context_feature_columns=context_feature_columns(),
            example_feature_columns=example_feature_columns(),
            mode=mode,
            scope="transform_layer")

        return context_features, example_features
    return _transform_fn
```
As you can see it only accepts `feature_columns` from context and examples, but not both. The two sparse features I want to cross are each context and example features respectively.

**Comment by eggie5** [comment]
another way to phrase this question:

How to implement the wide & deep model in TFR? Specifically the crossed features for the wide part.

**Comment by xuanhuiwang** [comment]
@eggie5, this is a novel feature. My guess is that you can still put the `cross_column` into `example_feature_columns`. In `tfr.feature.encode_listwise_features`, we apply any column definition on the union `features`. The significance of splitting `context_feature_columns` and `example_feature_columns` is to make sure that we can split the feature Tensors into `context_features` and `example_features` when returning.

**Comment by xuanhuiwang** [comment]
Close this for now. Feel free to reopen.
