### ISSUE TITLE
Ranking pipeline with LibSVM 

### ISSUE THREAD

**Issue by dsl10brc** [tensorflow/ranking#176]
I see that the recently released Ranking pipeline feature recommends TFrecord format. Previous ranking examples that y'all have provided were:

1. TFrecord format -  ANTIQUE, a Question-Answering dataset
2. LibSVM format - LETOR Search dataset

Is there any future plan to release Pipeline feature for LibSVM format? or Do y'all recommend converting LETOR Search dataset (for that matter any Ranking dataset) into TFrecord format to use it with the Pipeline feature?

**Comment by LiangqunLu** [comment]
I have the similar problem when I tried to use the TFR pipeline. I wrote a script to convert between LibSVM and ELWC-tfrecord files. Maybe you can check here #174

**Comment by hanshuguang-google** [comment]
I would suggest converting it to ELWC and write in TFRecord format, this is what we supported right now, and also the universal data format for other TensorFlow models. I wrote some comments on #174, please see whether this makes sense to you.
