### ISSUE TITLE
Ranking with no example features

### ISSUE THREAD

**Issue by anushaj13** [tensorflow/ranking#177]
I'm interested in using TF-Ranking for a scenario where I only have context information in the form of categorical and numeric features and binary relevance labels for a set of items. However tf.data.build_ranking_dataset function explicitly needs example features. I realize this won't cause an issue during training since the relevance labels can be passed in, however  I'm not sure what the right approach would be to structure the data during serving/prediction. I would really appreciate some input in this matter.

**Comment by anushaj13** [comment]
Adding on to this, for the sake of experimentation, I tried adding a simple dummy feature and noticed that the predictions heavily followed the one dummy example feature, over the other 7-8 distinct context features. E.g example feature=1.0 for all data points leads to same score for all features, inspite of the context features having different values for each data vector. Makes me think the context features are not contributing to the learning? For reference, I converted the data to ELWC format, and followed the demo example for code structure.

**Comment by xuanhuiwang** [comment]
I am not sure what is your problem setting. Can you share what are the labels? Are these labels associated with context only, given that you have no example features?

example features are required to formulate a ranking problem to use tf-ranking, in general.

**Comment by anushaj13** [comment]
Heres some more details. So I have a set of items that need to be ranked based on user context information. The content of the item does not matter at all. Hence no example features. The labels for the items are 1 or 0 depending on if the user "liked" or "did not react to it" respectively. Most of the times one single item in the list of items will have label "1" and the rest "0". Somewhat like #110  And yes you're right, the context features i.e. the user features determine the labels. These context features will be collected over multiple timesteps.
Is it possible to use tf-ranking for such a setting? Without any example features? Currently it seems like I can't.

**Comment by xuanhuiwang** [comment]
This fits for tf-ranking. I guess you still know the item ids, even if you think other features do not matter. (I think they matter. :-)). Here is the ELWC

context: {
  user context information.
}
examples: {
  item_id: id1;
  label: liked or not;
  item_feature_1: ...;  // if you want
}
examples: {
  item_id: id2;
  label: liked or not;
  item_feature: ...;  // if you want
}

You can use embedding for item_id and then set up a tf-ranking similarly to the example: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_tfrecord.py.

**Comment by anushaj13** [comment]
Thank you for the response. I agree with you, item features definitely matter, unfortunately in this case I don't have access to them.

**Comment by xuanhuiwang** [comment]
Closing this now. Let me know if you have other questions.
