### ISSUE TITLE
Error in NDCG test case

### ISSUE THREAD

**Issue by reidswanson** [tensorflow/ranking#178]
I've been going through some of the test cases to try to better understand the metrics and losses and believe I have found an error in one of them. The `rank_discount_fn` should be `lambda rank: 1. / rank` and not `rank`, like it is in the test for discounted cumulative gain. Currently, the expected (and actually returned) ndcg for this test is 2.0, while I believe it should be 0.5. I suppose this could be expected behavior if that is the intended discount function, but I also thought the NDCG was supposed to be between 0 and 1.

https://github.com/tensorflow/ranking/blob/2037fe23b708a93db9a2cebd86c34748a2d22d0d/tensorflow_ranking/python/metrics_test.py#L447-L467

**Comment by xuanhuiwang** [comment]
Thanks for pointing this out. Yes, you are right on this. Would you like to send a PR for this?

**Comment by reidswanson** [comment]
Sure, I've never done one before, but this seems like a good time to start.

**Comment by xuanhuiwang** [comment]
@reidswanson, Thanks. No need to worry. We will have a fix soon.

**Comment by xuanhuiwang** [comment]
This should be fixed here: https://github.com/tensorflow/ranking/commit/4c608a858794ae31166711e8d86f93c39d4f9924
