### ISSUE TITLE
Bazel test failed (bazel 2.2.0) Ubuntu 18.04.3 Python 3.6.9

### ISSUE THREAD

**Issue by Daphneitec** [tensorflow/ranking#179]
Bazel test failed on both python & python3, can you help?

bazel 2.2.0
(tfr) root@2121b893bcdf:~# cat /etc/issue
Ubuntu 18.04.3 LTS \n \l
(tfr) root@2121b893bcdf:~# pip3 list
Package                Version
---------------------- ----------
absl-py                0.9.0
astor                  0.8.1
cachetools             4.0.0
certifi                2019.11.28
chardet                3.0.4
gast                   0.2.2
google-auth            1.11.3
google-auth-oauthlib   0.4.1
google-pasta           0.2.0
grpcio                 1.28.0rc3
h5py                   2.10.0
idna                   2.9
Keras-Applications     1.0.8
Keras-Preprocessing    1.1.0
Markdown               3.2.1
numpy                  1.18.2
oauthlib               3.1.0
opt-einsum             3.2.0
pip                    20.0.2
protobuf               3.11.3
pyasn1                 0.4.8
pyasn1-modules         0.2.8
requests               2.23.0
requests-oauthlib      1.3.0
rsa                    4.0
scipy                  1.4.1
setuptools             46.0.0
six                    1.14.0
tensorboard            2.0.2
tensorflow             2.0.0
tensorflow-estimator   2.0.1
tensorflow-ranking     0.2.3
tensorflow-serving-api 2.1.0
termcolor              1.1.0
urllib3                1.25.8
Werkzeug               1.0.0
wheel                  0.34.2
wrapt                  1.12.1

(tfr) root@2121b893bcdf:~/ranking# bazel test //tensorflow_ranking/...
INFO: Analyzed 34 targets (0 packages loaded, 0 targets configured).
INFO: Found 22 targets and 12 test targets...
FAIL: //tensorflow_ranking/extension:pipeline_test (shard 1 of 2) (see /root/.cache/bazel/_bazel_root/d41241327876c139ac970cce2748425b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/extension/pipeline_test/shard_1_of_2/test.log)
FAIL: //tensorflow_ranking/extension/examples:pipeline_example_test (see /root/.cache/bazel/_bazel_root/d41241327876c139ac970cce2748425b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/extension/examples/pipeline_example_test/test.log)
FAIL: //tensorflow_ranking/python:data_test (see /root/.cache/bazel/_bazel_root/d41241327876c139ac970cce2748425b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/python/data_test/test.log)
......
INFO: Build completed, 12 tests FAILED, 14 total actions

**Comment by hanshuguang-google** [comment]
Can you send more details about the error logs from: 
 /root/.cache/bazel/_bazel_root/d41241327876c139ac970cce2748425b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/extension/pipeline_test/shard_1_of_2/test.log ? 

e.g. using "vim /root/.cache/bazel/_bazel_root/d41241327876c139ac970cce2748425b/execroot/org_tensorflow_ranking/bazel-out/k8-fastbuild/testlogs/tensorflow_ranking/extension/pipeline_test/shard_1_of_2/test.log" and see where it breaks?

**Comment by Daphneitec** [comment]
I have figured it out the issues. It's my server CPU AVX/AVX2 features. Thank u.
