### ISSUE TITLE
Windows or Mac? 

### ISSUE THREAD

**Issue by sosososo** [tensorflow/ranking#18]
Hi, what about Windows or Mac? Is there any docs on installation on Windows or Mac?

**Comment by sosososo** [comment]
> I just tried with Mac. After installing bazel based on the bazel site instruction, I can finish the installation. I cannot pass the test (the error looks like some python 2/3 problem), but otherwise I can train a model with it.

I'm trying to make it on Windows, however it will be an error when I try "bazel-bin/tensorflow_ranking/tools/pip_package/build_pip_package /tmp/ranking_pip". It seems there is any file not exist expected in 'build_pip_package.runfiles'. I don't know why.

**Comment by sosososo** [comment]
Oh, I find the error finally, it's the path.

**Comment by bendersky** [comment]
Thank you for your feedback. While we never tested TF-Ranking on Windows or Mac, it is good to know that you can it in these environments.

**Comment by eurydicedha** [comment]
> Oh, I find the error finally, it's the path.

Could you maybe elaborate on this answer? Thanks :)
