### ISSUE TITLE
How can I use a sequence feature input, like 'sequence_categorical_column_with_hash_bucket'

### ISSUE THREAD

**Issue by ChaosCY** [tensorflow/ranking#185]
I want a sequence format feature, but throw exception when I use feature column like 'sequence_categorical_column_with_hash_bucket', what should I do? thx a lot.
My test tf ranking version is 0.1.5.

**Comment by xuanhuiwang** [comment]
Can you share the exception error message? Do you use such a feature_columns in context or examples feature columns?

Also, what is the expect tensor after applying the such a feature column on the input data?

**Comment by xuanhuiwang** [comment]
Close this due to inactivity. Feel free to reopen.
