### ISSUE TITLE
tf_ranking_libsvm.py example prediction issue

### ISSUE THREAD

**Issue by weirencRicky** [tensorflow/ranking#186]
hi, may i know why function 'def _transform_fn' in  tf_ranking_libsvm.py  using encode_pointwise_features() for prediction mode while using encode_listwise_features() for other modes? Cuz when using encode_pointwise_features() and run prediction, it keeps raising errors, after changing to 'encode_listwise_features()' for prediction mode, prediction run successfully. Looking for helps here, thanks!

**Comment by xuanhuiwang** [comment]
Thanks for reporting this problem.

If you use estimator.predict(...) and your input_fn is similar to the input_fn used in training, you should use encode_listwise_features when mode=PREDICT because the input_fn yields serialized ELWC. =

The current code will accept serialized tf.Example when calling estimator.predict(...). You can need to change your input_fn to yield serialized tf.Example.

**Comment by bendersky** [comment]
Closing this for now. Please let us know if there is still a problem.

**Comment by finboost** [comment]
Hello,
i use the same input_fn for .predict() as for .train_and_evaluate(), it gives error: 
'''
ValueError: Cannot reshape a tensor with 3600 elements to shape [36,1] (36 elements) for '{{node transform/encoding_layer/0/Reshape}} = Reshape[T=DT_FLOAT, Tshape=DT_INT32](IteratorGetNext, transform/encoding_layer/0/Reshape/shape)' with input shapes: [36,100,1], [2] and with input tensors computed as partial shapes: input[1] = [36,1].
'''
could you please explain how to change input_fn or where to insert mode flag to make .predict to execute without errors.

**Comment by oapandit** [comment]
Hi @finboost ,

I was facing similar issue. I was able to resolve from the comments of @xuanhuiwang .
In case you are still facing the issue.

To minimal change to run the code for prediction is as follows -
1. In the transform function change pointwise to listwise feature for prediction.
2. Then you can do simple predict on estimator to get the prediction output
preds = estimator.predict(input_fn=test_input_fn, hooks=[test_hook])
assuming you want to get the prediction scores for test data .

best,
Onkar
