### ISSUE TITLE
Confusing default of sloppy_ordering parameter

### ISSUE THREAD

**Issue by PharaonHub** [tensorflow/ranking#188]
Hello, thanks for all efforts contributors invest to this library. It is really helpfull.
Please consider change of default parameter *sloppy_ordering*. Default value is in contradiction with tf.data.experimental.parallel_interleave. Moreover, the function is depricated.

def build_ranking_dataset_with_parsing_fn(file_pattern,
...
                                          sloppy_ordering=True,

**Comment by ramakumar1729** [comment]
This has been fixed in this [commit](https://github.com/tensorflow/ranking/commit/d5904d677ef24935f57eaa685cbb0ab0930dd058). Please take a look. Closing this issue for now. Feel free to reopen or create a new one.
