### ISSUE TITLE
Preparing data from CSV files

### ISSUE THREAD

**Issue by AkbarAlam** [tensorflow/ranking#191]
I have a csv dataset with numerical values. How can I prepare the data set for the model ? in the documentation it has been suggested to follwo [this](https://tensorflow.org/guide/premade_estimators#create_input_functions) documentaion.

I have tried the following code
```
def input_fn(features, labels, training=True, batch_size=100):
    dataset = tf.data.Dataset.from_tensor_slices((dict(features), labels))
    print(dataset)
    if training:
        dataset = dataset.shuffle(1000).repeat()
    return dataset.batch(batch_size)

ranker.train(input_fn= lambda :input_fn(features,labels))
```
Then it say 

> ValueError: not enough values to unpack (expected 2, got 1)

also with

> Use Variable.read_value. Variables in 2.X are initialized automatically both in eager and graph (inside tf.defun) contexts.
> <TensorSliceDataset shapes: ({a1: (), a2: (), a3: ()}, ()), types: ({a1: tf.float64, a2: tf.float64, a3: tf.float64}, tf.int64)>
> INFO:tensorflow:Calling model_fn.
> WARNING:tensorflow:Feature "a1" has invalid feature tensor shape (None,). Expected shape has at least 3 dims: (batch_size, list_size, feature_size).
> WARNING:tensorflow:Feature "a2" has invalid feature tensor shape (None,). Expected shape has at least 3 dims: (batch_size, list_size, feature_size).
> WARNING:tensorflow:Feature "a3" has invalid feature tensor shape (None,). Expected shape has at least 3 dims: (batch_size, list_size, feature_size).

**Comment by bendersky** [comment]
Please see if #174 can be useful to what you're trying to achieve (perhaps you can have your data in libsvm format instead)
