### ISSUE TITLE
Storing multiple queries/documents in ELWC format

### ISSUE THREAD

**Issue by davidmosca** [tensorflow/ranking#194]
I would like to store _multiple_ pairs of queries/documents in ELWC format, i.e:

> [query1, [doc1, doc2, doc3]]
[query2, [doc4, doc5]]
[query3, [doc6, doc7, doc8]]
etc.

The examples I have found, both [here](https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb#scrollTo=ooOmCPHbyd02) and [here](https://github.com/tensorflow/ranking/issues/174#issuecomment-600338167) mention only _one_ pair of query/documents.
What template should I use to store more than one pair of query/documents?
Thanks!

**Comment by xuanhuiwang** [comment]
Just clarify: a single ELWC will store a query and a list of documents. You can use a set of ELWCs to store multiple query/documents.

For your example, I think you can store them in 3 ELWCs TFRecords.

**Comment by davidmosca** [comment]
Thanks.
