### ISSUE TITLE
How to store data as ELWC tfrecord

### ISSUE THREAD

**Issue by Pascal-Iv** [tensorflow/ranking#196]
I have some numpy arrays. How do I store them as ELWC/Where to find documentation on how to do that? I found an example script [(tf_ranking_tfrecord_test.py)](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_tfrecord_test.py#L111), but I can not find information on how to put my data in this string format in the first place:

    """
    context {
      features {
        feature {
          key: "query_tokens"
          value { bytes_list { value: ["this", "is", "a", "relevant", "question"] } }
        }
    ...
    """
I do not know how `input_pb2.ExampleListWithContext()` works or how to find out.

Here is some random data I would like to store as a ELWC tfrecord. How to do that?

    import numpy as np

    # some random data
    label_first_list = np.random.randn(10)
    label_second_list = np.random.randn(15)

    features_context_first_list = np.random.randn(8)
    features_context_second_list = np.random.randn(8)

    features_examples_first_list = np.random.choice(range(10),(20,10))
    features_examples_second_list = np.random.choice(range(10),(20,15))

I also found this somewhere in the issues:

```
from tensorflow_serving.apis import input_pb2
    elwc = input_pb2.ExampleListWithContext()
    context_feature_dict = { 
  'query_tokens': tf.train.Feature(float_list = tf.train.FloatList(value=[1.0, 2.0]))
}
    context_feature = tf.train.Example(features=tf.train.Features(feature=context_feature_dict))
    elwc.context.CopyFrom(context_feature)
    for doc in docs:
  example_feature_dict = {
    'document_tokens': tf.train.Feature(int64_list=tf.train.Int64List(value=[1,2])),
    'relevance': tf.train.Feature(int64_list=tf.train.Int64List(value=[1]))
  }
      example_feature = tf.train.Example(features=tf.train.Features(feature=example_feature_dict)) 
  elwc.examples.add().CopyFrom(d)

# After you got elwc, you can then write the data with
writer.write(elwc.SerializeToString())
```

But this does not help me since it just works for a single query. But the training data for ranking has to contain multiple queries. How to write a tfrecord which I can for example use for tensorflow_ranking/examples/handling_sparse_features.ipynb, which contains multiple queries?

**Comment by azagniotov** [comment]
Hi @Pascal-Iv see if the following helps you:

Define a few functions to wrap your raw values within the `tf.train.Feature` type with the respective types:
```
from tensorflow_serving.apis import input_pb2

def _bytes_feature(value_list):
    """Returns a bytes_list from a string / byte."""
    if isinstance(value, type(tf.constant(0))):
        value = value.numpy() # BytesList won't unpack a string from an EagerTensor.
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=value_list))

def _float_feature(value_list):
    """Returns a float_list from a float / double."""
    return tf.train.Feature(float_list=tf.train.FloatList(value=value_list))

def _int64_feature(value_list):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=value_list))
```

Then, you can use the `tf.io.TFRecordWriter` and write as many `ELWCs` as you want (i.e.: one `ELWC` per query) into the same TF record, e.g. (please note, this is a very rough code, but it should give you an idea how to use `input_pb2.ExampleListWithContext`): 
```
 with tf.io.TFRecordWriter("your_data.tfrecords") as writer:

    context_dict = {}
    context_dict["ctx_f0"] = _int64_feature(<YOUR_CTX_VALUES_LIST>)
    context_proto = tf.train.Example(features=tf.train.Features(feature=context_dict))
         
    ELWC = input_pb2.ExampleListWithContext()
    ELWC.context.CopyFrom(context_proto)
            
    example_features = ELWC.examples.add()

    example_dict = {}
    example_dict["f0"] = _float_feature(<YOUR_EXAMPLE_VALUES_LIST>)
    exampe_proto = tf.train.Example(features=tf.train.Features(feature=example_dict))
    example_features.CopyFrom(exampe_proto)
                
    writer.write(ELWC.SerializeToString())
```

**Comment by Pascal-Iv** [comment]
@azagniotov  Great explanation, thank you so much!

**Comment by ZhouM1118** [comment]
Can spark save dataframe data in ELWC format?
