### ISSUE TITLE
Best representation for textual data

### ISSUE THREAD

**Issue by davidmosca** [tensorflow/ranking#200]
Hi, when creating an `ELWC` object with textual data, what is the best representation for the input text (for both context and examples)? Is it:
- a raw string ('Wallace & Gromit: The Curse of the Were-Rabbit')
- a raw list (['Wallace', '&', 'Gromit', 'The', 'Curse', 'of', 'the', 'Were-Rabbit'])
- a normalised string ('wallace & gromit the curse of the were rabbit')
- a normalised list (['wallace', '&', 'gromit', 'the', 'curse', 'of', 'the', 'were', 'rabbit'])
- or another format?

Thanks.

**Comment by eggie5** [comment]
Some feedback from my experience:

* in-graph tokenization has a cost (con strings)
* in-graph normalization has a cost (con strings)
* deserialization of the `VarLenFeature` has a cost (con lists)

If you have short strings, then all of these costs are marginal. However, if you have large strings the costs are meaningful. 

The fastest format would be a fixed length (padded) list of token ids: no tokenization/normalization costs and no deserialization costs. 

So you can either push all pre-processing upstream (eg spark) or do it downstream in TF. It all depends on how long your strings are and if you are doing online or offline inference.

**Comment by davidmosca** [comment]
Thanks for your answer. When TF tokenises strings, does it also consider substrings (e.g. to catch misspellings such as 'experiance') or does it just split on whitespace? And if raw text is passed to TF, does it tokenise/normalise automatically, or do you have to request it?
Also, in order to create fixed length lists of token ids with text inputs of variable length, do you pad them based on the length of the longest text?

**Comment by eggie5** [comment]
> When TF tokenises strings, does it also consider substrings (e.g. to catch misspellings such as 'experiance') or does it just split on whitespace? And if raw text is passed to TF, does it tokenise/normalise automatically, or do you have to request it?

All of these questions are dependent upon YOUR implement the tokenization and normalization routine. Nothing to do w/ tensorflow or this ranking package per-se. 

> Also, in order to create fixed length lists of token ids with text inputs of variable length, do you pad them based on the length of the longest text?

I can't answer. I guess this depends on what you are trying to achieve or your goals.

**Comment by davidmosca** [comment]
Thanks, in this case I'll try to tokenise with [sentencepiece](https://github.com/google/sentencepiece) - it seems to fit the bill.
