### ISSUE TITLE
Using Tensorflow Ranking with Dense Features

### ISSUE THREAD

**Issue by samuel-wong-taiger** [tensorflow/ranking#203]
Hi, I'm trying to implement the TFR-Bert architecture found in https://arxiv.org/abs/2004.08476. A few questions that I'm kind of stuck with:
1. Does the DNN model accept data without context features? Because in this implementation, the query-documents are paired and represented as dense embeddings from the BERT Model.
2. What format of data will I use? Will it still be ELWC and how to implement that, if there's any reference that would be great.

**Comment by nishathussain** [comment]
1. I think it should work.
2. Use the same ELWC format with an empty context.

**Comment by xuanhuiwang** [comment]
+1 for @nishathussain 

Close this now. Feel free to reopen.
