### ISSUE TITLE
Training with large number of documents

### ISSUE THREAD

**Issue by TalhaAsmal** [tensorflow/ranking#209]
Hi,

I'm trying to run a ranking training experiment with about 500000 training documents, each with 310 numeric features. When trying to run training on a subset of the data (60000 documents) I get an OOM error.

The process I use is as follows:

- Convert CSV to ELWC format and save as tfrecord
- Follow the Keras example in https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/keras/README.md to read in the data and train with batch_size =1 and hidden_layer_dims=[64]

The error I get is
`2020-06-22 12:43:29.289927: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at cwise_ops_common.cc:82 : Resource exhausted: OOM when allocating tensor with shape[1,60000,60000] and type float on /job:localhost/replica:0/task:0/device:CPU:0 by allocator cpu`

I would like to know if there's a way to train without loading the entire dataset into memory? Or perhaps a different training method that would allow me to train with such a large dataset?

**Comment by xuanhuiwang** [comment]
For each context or query, you have 60000 documents? Or in the whole collection, you have 60000 documents? What is the ranking setting specifically?

**Comment by TalhaAsmal** [comment]
I think I misunderstood the ELWC format completely previously. Previously, I was creating one ELWC record with 120 queries in it. Now I'm creating 1 ELWC record per query, so a total of 120 ELWC records, with between 2500 and 5000 documents per query. This now allows me to train. 

My new concern is how to determine the batch size, and how many batches per epoch.

**Comment by xuanhuiwang** [comment]
In general, the larger the batch size, the better. However, in your case, I think you may want to try a smaller batch size due to OOM concerns.

An epoch usually means that you go over the whole data set once. 120 queries is a small data set. You can split them into train and test to see when your training starts overfitting.

**Comment by xuanhuiwang** [comment]
Close this for now. Feel free to reopen.
