### ISSUE TITLE
how to use image features for ranking training

### ISSUE THREAD

**Issue by shioriarie** [tensorflow/ranking#212]
Hi, 

I'm trying to run a ranking training with numerical, categorical, and images features.
How can I use these features instead of context or example features?
I would like to know if there's a way to make dataset for ranking training using different format tfrecord datasets.

**Comment by xuanhuiwang** [comment]
For image features, do you mean some features with >1D shape, like [dim1, dim2]? Can you give an example of the format in your applications?

**Comment by shioriarie** [comment]
Thank you for your reply.
my tfrecord data is like such as following,
{numerical_feature(?, 1), one_hot_feature: (?, n)multi_hot_feature: (?, n), image: (?, width, height, color)}
Does ranknet accept this data?

**Comment by xuanhuiwang** [comment]
I think so. For image, you will need to specifying the feature shape appropriately. Also, in the scoring_fn, you will see [?, width, heights, color] in the group_features.

**Comment by xuanhuiwang** [comment]
Close this for now. Feel free to reopen.
