### ISSUE TITLE
Feature Request - Support per-example sample_weight in Keras API

### ISSUE THREAD

**Issue by yzhangswingman** [tensorflow/ranking#216]
Looks like current TFRanking Keras implementation only supports per-list sample weights in shape (batch_size,).
Support for per-example sample_weight could be very helpful to training and evaluation.

**Comment by yzhangswingman** [comment]
hi @ramakumar1729,  any opinion on this perhaps? Appreciate it!

**Comment by ramakumar1729** [comment]
Hi @yzhangswingman , Keras based training via `model_to_estimator` supports both per-list and per-example sample weights. See this code [example](https://github.com/tensorflow/ranking/blob/99ab8ee062ff632617e09ff0904a840f335e9468/tensorflow_ranking/examples/keras/keras_m2e_tfrecord.py#L216) for how to run this.

This test [case](https://github.com/tensorflow/ranking/blob/99ab8ee062ff632617e09ff0904a840f335e9468/tensorflow_ranking/python/keras/estimator_test.py#L251) demonstrates running the `model_to_estimator` with per-example weights.

**Comment by yzhangswingman** [comment]
@ramakumar1729 gotcha! I guess I will work with what's available in native Keras for now since it seems to be the way that core Tensorflow is going. Thanks

**Comment by ramakumar1729** [comment]
@yzhangswingman Closing this for now. Feel free to reopen or start a new issue. Thanks.
