### ISSUE TITLE
PairwiseLogisticLoss and MRRMetrics does not seem to work on TPU

### ISSUE THREAD

**Issue by vbod** [tensorflow/ranking#217]
I am trying to use TensorFlow-ranking library to train a ranking network. It is basically composed of a ranker that acts as a regression network (it outputs a tensor `(None, 1)` where `None` is due to batching).

I am using standard Keras API, and `tf.data.Dataset`. One line of this dataset is composed of `positive_inputs` and `negative_inputs_i` for i in a given range from 0 to a certain number of negative and labels like `[1, 0, ..., 0]` with as many 0s as negatives (so that the dimension of the labels is `1+num_negatives` for one positive sample for `num_negatives` negatives samples).

The model is fairly simple and trains pretty well on both CPU and GPU. Here is a code stub for the model:

```python
def _build_pairwise_model(num_negatives: int):
    """
    """
    # custom implementation, basically takes for input a sequence of 
    # size TOTAL_SEQUENCE_LENGTH and returns a scalar ranking score
    # (works on batched data so that input is of shape (None, TOTAL_SEQUENCE_LENGTH)
    # and outputs (None, 1)).
    ranker = layers.Ranker()
    inputs = {}

    positive_inputs = tf.keras.layers.Input(
        shape=(TOTAL_SEQUENCE_LENGTH,),
        name='positive_inputs',
        dtype=tf.float32
    )
    inputs.update({'positive_inputs': positive_inputs})
    predictions = ranker(positive_inputs)

    for i in range(num_negatives):
        negative_inputs = tf.keras.layers.Input(
            shape=(TOTAL_SEQUENCE_LENGTH,),
            name='negative_inputs_%d' % i,
            dtype=tf.float32
        )
        inputs.update({'negative_inputs_%d' % i: negative_inputs})
        predictions = tf.concat([predictions, ranker(negative_inputs)], axis=1)
    
    # final_predictions is of same shape as labels, i.e. (None, num_negatives+1) and
    # contains the logits to be ordered and compared to the labels: i.e. the taks is to
    # for each row the first logit higher than all others (as the first logit is the ranking
    # score of the positive sample, and all of the others of the negatives).
    final_predictions = tf.keras.layers.Lambda(
        lambda p: p,
        name='labels'
    )(predictions)

    model = tf.keras.models.Model(
        name='Ranker',
        inputs=inputs,
        outputs=[final_predictions]
    )
    
    optimizer = .... # whatever you want, e.g. Adam
    
    model.compile(
        optimizer=optimizer,
        loss=losses.PairwiseLogisticLoss(),
        metrics=[metrics.MRRMetric(topn=1+num_negatives)]
    )

    return model
```

On TPU though (using Colab and TensorFlow-2.2.0), it fails with:
1. `MRRMetrics` always fails with error:
>  InvalidArgumentError: {{function_node __inference_train_function_210431}} Compilation failure: Detected unsupported operations when trying to compile graph has_valid_nonscalar_shape_true_210282_const_0[] on XLA_TPU_JIT: DenseToDenseSetOperation (No registered 'DenseToDenseSetOperation' OpKernel for XLA_TPU_JIT devices compatible with node {{node has_invalid_dims/DenseToDenseSetOperation}}){{node has_invalid_dims/DenseToDenseSetOperation}}
	 [[has_valid_nonscalar_shape]]
	 [[broadcast_weights_1/assert_broadcastable/is_valid_shape]]
	TPU compilation failed
	 [[tpu_compile_succeeded_assert/_2615835994889621977/_26]]
2. When I remove this metric, the loss still fails with: 
> InternalError: {{function_node __inference_train_function_418876}} Compilation failure: RET_CHECK failure (third_party/tensorflow/compiler/xla/service/dynamic_dimension_inference.cc:862) input_dim_size % output_dim_size == 0
	TPU compilation failed
	 [[{{node tpu_compile_succeeded_assert/_1425100230861709682/_26}}]]

What is weird though with the loss failing is that it works when I have only two negatives but fails otherwise (my basic setup is with 10 negatives).

**Comment by xuanhuiwang** [comment]
Thanks for reporting this issue. We haven't fully tested the Keras version of the code on TPU yet. It maybe possible that some ops used the loss or metrics doesn't work with TPU well.

Do you have any updates on this?

**Comment by vbod** [comment]
@xuanhuiwang Sorry I'm on vacation but I'll try a bit more when I get back and have time. Do you have hints on how to debug on local machine with TPU config (just the graph building of course, I guess it should be feasible) so that I can try to see what really happens? (Because I currently need to connect on Colleen and test without debug to spot things out and it's a bit time consuming)

**Comment by ramakumar1729** [comment]
@vbod : Can you share a minimum working example to reproduce this error. Which I tried to reproduce this, I did not get any compilation error.
```
import tensorflow as tf
! pip install -q tensorflow_ranking
import tensorflow_ranking as tfr

TOTAL_SEQUENCE_LENGTH = 3

def _build_pairwise_model(num_negatives: int):
    """
    """
    # custom implementation, basically takes for input a sequence of 
    # size TOTAL_SEQUENCE_LENGTH and returns a scalar ranking score
    # (works on batched data so that input is of shape (None, TOTAL_SEQUENCE_LENGTH)
    # and outputs (None, 1)).
    ranker = tf.keras.Sequential([tf.keras.layers.Dense(1)])
    inputs = {}

    positive_inputs = tf.keras.layers.Input(
        shape=(TOTAL_SEQUENCE_LENGTH,),
        name='positive_inputs',
        dtype=tf.float32
    )
    inputs.update({'positive_inputs': positive_inputs})
    predictions = ranker(positive_inputs)

    for i in range(num_negatives):
        negative_inputs = tf.keras.layers.Input(
            shape=(TOTAL_SEQUENCE_LENGTH,),
            name='negative_inputs_%d' % i,
            dtype=tf.float32
        )
        inputs.update({'negative_inputs_%d' % i: negative_inputs})
        predictions = tf.concat([predictions, ranker(negative_inputs)], axis=1)
    
    # final_predictions is of same shape as labels, i.e. (None, num_negatives+1) and
    # contains the logits to be ordered and compared to the labels: i.e. the taks is to
    # for each row the first logit higher than all others (as the first logit is the ranking
    # score of the positive sample, and all of the others of the negatives).
    final_predictions = tf.keras.layers.Lambda(
        lambda p: p,
        name='labels'
    )(predictions)

    model = tf.keras.models.Model(
        name='Ranker',
        inputs=inputs,
        outputs=[final_predictions]
    )
    
    optimizer = tf.keras.optimizers.Adam()
    
    model.compile(
        optimizer=optimizer,
        loss=tfr.keras.losses.PairwiseLogisticLoss(),
        metrics=[tfr.keras.metrics.MRRMetric(topn=1+num_negatives)]
    )

    return model

model = _build_pairwise_model(10)
model
```

**Comment by vbod** [comment]
@ramakumar1729 Sorry I was off this latest month. I tested your code and it runs fine indeed. I'm really sorry that I bothered you I guess it all boils down to the `map()` functions I used on my `tf.data.Dataset`. I'll try a bit more but I think it's safe to consider that it's not a TensorFlow ranking issue as I thought at first but a mistake of mine. Sorry for the inconvenience! Do you have any hints by the way on how to debug a TPU error without "A/B-testing" on some pieces of the code (I mean change some small parts and try to spot what fails)? I find it very challenging to understand the error messages I face when it fails...

**Comment by ramakumar1729** [comment]
@vbod Not a problem! You can check if the ops you are using are supported on TPUs. ([link](https://cloud.google.com/tpu/docs/tensorflow-ops))
