### ISSUE TITLE
training is too slow

### ISSUE THREAD

**Issue by kkonevets** [tensorflow/ranking#22]
Ubuntu 18, CPU mode

I have 44 features in libSVM format
I run tf_ranking_libsvm.ipynb example on my dataset
I guess the problem is input_fn function that calls tfr.data.libsvm_generator, because cpu load is minimal

How can I fix it? Is that a problem with tf.data.Dataset.from_generator?

**Comment by xuanhuiwang** [comment]
Can you try to use https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py instead?

**Comment by kkonevets** [comment]
Yes, it helps. Now all CPUs are active. But why are they 60% active? I mean every cpu is loaded only on 60%. My expectation is that they are fully loaded. All data now is in RAM so performance should be maximum. 
My gues is that a nature of the ranking algorithm does not allow this to happen.
In contrast RankLib implementation of LambdaMART has hier cpu load.
Anyway thanks
