### ISSUE TITLE
Predict from in-memory dataset

### ISSUE THREAD

**Issue by davidmosca** [tensorflow/ranking#223]
Hi, currently the `predict_input_fn` in the [demo](https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb#scrollTo=vF-4BiTnDRou) loads the file to be scored form disc (using the specified path); however, in a real life scenario (e.g. web search) this is not realistic - the prediction must be made from a dataset already loaded into memory.

How could the demo code be modified to create a dataset on the fly from a `context` (query) and a set of `examples` (documents, which can be loaded from disc beforehand), and then use this in-memory dataset to make a prediction? Thanks.

**Comment by xuanhuiwang** [comment]
Thanks for the question. We don't have a handy example to predict from the in-memory data. Here is my thought:

I think you may want to construct an input function similarly to https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py#L253, as an input function for prediction.

Another example is like: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/model_test.py#L466. You can feed the dict of features directly using lambda.

**Comment by davidmosca** [comment]
Thanks for the tips. Does the second option (`predictions = self._estimator.predict(input_fn=lambda: (features, None))`) also require to rewrite the tutorial's [estimator](https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb#scrollTo=7aky8RFpH-D0)? If so, how? And how can the features be converted into the correct format (the example shows [a dictionary of arrays of floating numbers](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/model_test.py#L463) but in the Antique dataset the data (answers) are stored as protobuffers.

**Comment by xuanhuiwang** [comment]
I think `features` should be a dict of `{name: Tensor/SparseTensors}` for predict input_fn. Since you mentioned in-memory data, I assumed that the data is already in the dict format. Otherwise, you need converter or parser to prepare the data in the dict format.

I don't think you need to change the estimator.

**Comment by davidmosca** [comment]
Yes the problem is _how_ to build the converter/parser, in order to convert the data from strings/numbers/arrays to Tensors. The code of the example cannot be-reused because (1) the data is read from disk and (2) the context and examples are built simultaneously, whereas in a search context the examples (answers) are known in advance (and can/must therefore be pre-loaded and pre-converted) whereas the context (user question) is only known when the user types it, and must then be converted separately on the fly into the appropriate format.
The conversion into Tensors must follow the same logic as that of the `predict_input_fn` function, but starting from in-memory raw data (text, numbers). The question is: how?

**Comment by xuanhuiwang** [comment]
@davidmosca, have you considered export the model to SavedModel and use the TensorFlow Serving to do the prediction?

The estimator.predict is mainly for offline analysis or debugging purpose, as far as I can tell. For production, you need to export the model and serve it outside of estimator. See https://www.tensorflow.org/tfx/tutorials/serving/rest_simple#serve_your_model_with_tensorflow_serving.

**Comment by davidmosca** [comment]
The Tensorflow Serving example above uses an image vector. It does not show how to pre-process ELWC data (for use by the Serving API), which in the context of a web search with numerous documents must be done separately for _context_ and _examples_, as the examples (= answers in the Antique dataset) must be transformed into the appropriate format and pre-loaded into memory (before the search happens) whereas the context (= question in the Antique dataset) must be transformed/loaded on the fly.
The [TF-Ranking release page](https://ai.googleblog.com/2018/12/tf-ranking-scalable-tensorflow-library.html) says that _"anyone who is interested in building real-world data intensive ranking systems such as web search or news recommendation, can use TF-Ranking as a robust, scalable solution"_ and that _"TF-Ranking is fast and easy to use"_. Is there a "fast, easy to use" functionality to build ranking systems for web search _currently_ available in TF-Ranking (i.e. with online inference for data in ELWC format), or is the presentation above just marketing material?
