### ISSUE TITLE
New feature not recognised in TFRecord example

### ISSUE THREAD

**Issue by davidmosca** [tensorflow/ranking#227]
Hi, in the [Colab](https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb) example based on the Antique dataset, if I add the `document_bert_encoder_outputs` feature to the examples as follows:
```
def example_feature_columns():
  """Returns the example feature columns."""
  sparse_column = tf.feature_column.categorical_column_with_vocabulary_file(
      key="document_tokens",
      vocabulary_file=_VOCAB_PATH)
  document_embedding_column = tf.feature_column.embedding_column(
      sparse_column, _EMBEDDING_DIMENSION)
  bert_embedding_column = tf.feature_column.numeric_column(key='document_bert_encoder_outputs', shape=(1024,))
  return {"document_tokens": document_embedding_column, 'document_bert_encoder_outputs': bert_embedding_column} 
```
I get the following error (in `tf.estimator.train_and_evaluate(ranker, train_spec, eval_spec)`):
```
InvalidArgumentError: Name: <unknown>, Feature: document_bert_encoder_outputs (data type: float) is required but could not be found.
	 [[{{node ParseExample/ParseExampleV2}}]]
	 [[IteratorGetNext]]
```
The Bert encodings, however, are available in the Antique `train.tfrecords` and `test.tfrecords` files, so where does the error come from?

**Comment by xuanhuiwang** [comment]
You need a `default_value` for bert_embedding_column, like tf.feature_column.numeric_column(key='document_bert_encoder_outputs', shape=(1024,), default_value=0)

This is needed because there are varying length for each example list in a batch.

**Comment by davidmosca** [comment]
I'm not sure I understand - I thought the default value was only necessary when the specified feature (`document_bert_encoder_outputs` in this case) was missing for one or more examples. But in the `train.tfrecords` and `test.tfrecords` files, all answers have a `document_bert_encoder_outputs` feature, with the corresponding vector.
By "varying length" you mean that the number of answers per question is not fixed? What effect does the default value then have?

**Comment by xuanhuiwang** [comment]
>By "varying length" you mean that the number of answers per question is not fixed? 
Yes

>What effect does the default value then have?
The convention is to have a -1 in the corresponding labels and they will be ignored in the training.

**Comment by davidmosca** [comment]
OK I see, so this is because the number of answers does not necessarily match the `_LIST_SIZE` and the missing ones get a -1. It is strange though that this requirement for a default value only applies to numerical data - for some reason the `document_embedding_column` does not need a default value.
