### ISSUE TITLE
Minimal example of prediction using TFR-BERT?

### ISSUE THREAD

**Issue by PeterAJansen** [tensorflow/ranking#228]
Would it be possible to have a minimal example that performs prediction (ranking) on an unseen set using TFR-BERT?  

The current example ( tfrbert_example.py ) trains the model and evaluates performance on a development set, but it would be helpful to see a simple example of ranking on an unseen test set, and exporting these {query, document, rank} tuples to (for example) a plain text file for debugging.

**Comment by ramakumar1729** [comment]
Hi @PeterAJansen, the TFR-BERT example would export a SavedModel in the model dir which you can use to score unseen examples in ELWC format. This [https://github.com/tensorflow/ranking/issues/189#issuecomment-629750559](issue comment)describes how to an exported SavedModel and use TF Serving to get scores for a list of candidates represented using ELWC format.

**Comment by PeterAJansen** [comment]
Thanks @ramakumar1729 .  Much of issue 189 seems to be about the mechanics of the serving (the prediction seems to be done with a single call that hides most of the mechanics).  I'm still at the sort of barebones level of being able to generate predictions without the added complexities of the REST API. 

For example, if I add this predict() function to [extension/pipeline.py](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/extension/pipeline.py), that just uses the existing input function for the development set (so there shouldn't be any issues with data formatting):
```
  def predict(self):
    # Prepare input function (here, just the same one used in _train_eval_specs() )
    train_list_size = self._hparams.get("list_size")
    eval_list_size = self._hparams.get("eval_list_size") or train_list_size
    eval_input_fn = self._make_input_fn(
        input_pattern=self._hparams.get("eval_input_pattern"),
        batch_size=self._hparams.get("eval_batch_size"),
        list_size=eval_list_size)

    # Run predictions
    print ("\n\n***  RUNNING PREDICTIONS \n\n")    
    ranker = self._estimator    
    predictions = ranker.predict(input_fn=eval_input_fn)

    # Display predictions
    for i in range(0, eval_list_size):
      print ("\n\n***  PREDICTION (" + str(i) + " / " + str(eval_list_size) + ")\n\n")
      x = next(predictions)    
      print(x)
      print(str(type(x)))

```    

And call predict() after training in [tfrbert.example.py](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/extension/examples/tfrbert_example.py):
```
  metrics, output = bert_ranking_pipeline.train_and_eval(local_training=FLAGS.local_training)

  print("Output: \n")
  print(str(type(metrics)) + "\n")
  print(metrics)

  # Prediction
  bert_ranking_pipeline.predict()

```

My output (debug output) is similar to @azagniotov 's in #189 , where the prediction scores are all identical (though the specific number used does change between runs): 

```
Output: 

<class 'dict'>

{'loss': 54.72035, 'metric/arp': 8.5753975, 'metric/dcg': 17.481949, 'metric/map': 0.9473973, 'metric/mrr': 0.96614575, 'metric/ndcg': 0.8261353, 'metric/ndcg_1': 0.5750001, 'metric/ndcg_10': 0.7681629, 'metric/ndcg_3': 0.62588125, 'metric/ndcg_5': 0.68720114, 'metric/ordered_pair_accuracy': 0.0, 'metric/precision': 0.20020002, 'global_step': 2000}

...

***  PREDICTION (1 / 50)
[0.20995332 0.20995332 0.20995332 0.20995332 0.20995332 0.20995332
 0.20995332 0.20995332 0.20995332 0.20995332 0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.        ]
<class 'numpy.ndarray'>


***  PREDICTION (2 / 50)
[0.20995332 0.20995332 0.20995332 0.20995332 0.20995332 0.20995332
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.        ]
<class 'numpy.ndarray'>

....

***  PREDICTION (49 / 50)
[0.20995332 0.20995332 0.20995332 0.20995332 0.20995332 0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.         0.         0.         0.         0.
 0.         0.        ]
<class 'numpy.ndarray'>
```

I think in #189 the issue was the encoding of the input data, but I'm using the same encoding function as is used in the training/evaluation function, so that shouldn't be an issue.  

I am training only a little bit (2000 epochs on BERT-Mini, to keep iteration time fast while debugging), but even with low amounts of training and a small model I'd still expect that the rankings would be different: 
```
MODEL_DIR=/tmp/output && \
TRAIN=/home/peter/github/tensorflow/ranking/Antique/tf-ranking/ELWC/train.tfrecords && \
TEST=/home/peter/github/tensorflow/ranking/Antique/tf-ranking/ELWC/test.tfrecords && \
rm -rf $MODEL_DIR && \
bazel build -c opt \
tensorflow_ranking/extension/examples/tfrbert_example_py_binary && \
./bazel-bin/tensorflow_ranking/extension/examples/tfrbert_example_py_binary \
    --train_input_pattern=${TRAIN} \
    --eval_input_pattern=${TEST} \
    --bert_config_file=/home/peter/github/tensorflow/ranking/uncased_L-4_H-256_A-4_TF2/bert_config.json \
    --bert_init_ckpt=/home/peter/github/tensorflow/ranking/uncased_L-4_H-256_A-4_TF2/bert_model.ckpt \
    --bert_max_seq_length=128 \
    --model_dir=${MODEL_DIR} \
    --list_size=50 \
    --train_batch_size=1 \
    --learning_rate=1e-04 \
    --num_train_steps=2000 \
    --checkpoint_secs=120 \
    --num_checkpoints=10 \
    --alsologtostderr

```

**Comment by ramakumar1729** [comment]
@PeterAJansen Not sure where the issue is, but can you try running for more training steps? I see the ordered pair accuracy is 0, which indicates it needs more training.

**Comment by PeterAJansen** [comment]
Hi @ramakumar1729 ,

Thanks -- it doesn't appear to be an issue with the number of training steps, or the model (I've tried the various TF2 checkpoints of different sized BERT models). 

I very much appreciate the efforts that have been made to release this code.  I have spent more time than I'm willing to admit trying various approaches to get data in and predictions out of the model, from reusing the existing train/test files, to working to construct toy data in memory in the ELWC format (and convert these to numerical BERT indices using the vocab file) and call the various train/predict functions, to working through the partially specified example in #189 where the TF Serving is used (though tensorflow_model_server always says 'No versions of servable tfrbert found under base path /tmp/output/servetest-model/export/latest_model/1599246704/' -- is this an issue with the model name (tfrbert, I can't seem to find a parameter for this anywhere in the example except for possibly _NETWORK_NAME), the save format, the folder (though I've tried most subfolders in the save directory), etc... -- and even if this works, how does one pack the BERT-encoded query and context vectors?  It seems there's even difficulty replicating #189 in regular TF-Rank without the added complexity of the BERT vectors). 

While the ANTIQUE example provided shows how to load pre-generated binary data, and how to get dev performance numbers out of it (though I'm still having trouble replicating these numbers), my sense of things is that one would still have to have quite advanced Tensorflow and Tensorflow-Ranking knowledge to get data in and predictions out of this example -- and without human-readable prediction output, it's almost impossible to verify the ranker is working as expected.  

If you could provide some minimal end-to-end toy example, my sense is this would be vastly more helpful:

e.g. Query: Where can you purchase cat food?, Documents: [{text: "the pet food store sells cat food", relevance: "2"}, {text: "the grocery store sells cat food", relevance: "2"}, {text: "cats eat cat food", relevance: "1"}, {text: "a bicycle has two wheels", relevance: "0"}, ...]) for ~10 train and ~10 test queries, and demonstrate the full pipeline of:

1. loading them, either from memory or a plain text file
2. converting them into the ELWC format through the BERT vocab
3. training the model, tuning on dev (I think this is already done in pipeline.py:train_and_eval() )
4. generating performance scores (I think this is already done on dev in train_and_eval()), and 
5. generating predictions through some means, whether it be an appropriate input function for the data in (1) piped through the predict() API, or running through TF Serving (what model name should be used?  what path should be used?  how should the BERT data be converted/formatted through whatever API you're demonstrating?)

There is enough different in TFR-BERT compared to TF-Ranking, and enough that's new with minimal documentation, that even 3 days of being knee deep in the code base instrumenting the function calls 5 or 6 layers down hasn't yielded much progress on my end.

**Comment by azagniotov** [comment]
@PeterAJansen apologies for jumping in, just wanted to ask you regarding your issue with model deployment:
```
No versions of servable tfrbert found under base path /tmp/output/servetest-model/export/latest_model/1599246704/'
```

When I deploy my models into the TensorFlow Model server, my Docker command looks as follows (please note that there is no version specified after the `tensorflow_ranking_model`, which is the model export directory name). Also, in the following code example, I am pinning the Docker container version to `v2.1.0`, you may want to set the version you are on:
```
docker run -t --rm -p 8500:8500 -p 8501:8501 \
-v "/home/azagniotov/tensorflow_ranking_model:/models/tensorflow_ranking_model" \
-e MODEL_NAME="tensorflow_ranking_model" tensorflow/serving:2.1.0 &
```

Have you tried something as follows where the version directory is not specified?
```
docker run -t --rm -p 8500:8500 -p 8501:8501 \
-v "/tmp/output/servetest-model/export/latest_model:/models/latest_model" \
-e MODEL_NAME="latest_model" tensorflow/serving:2.1.0 &
```

**Comment by PeterAJansen** [comment]
Thanks @azagniotov , tensorflow_model_server is able to find the model when I use that path instead (it's unintuitive to me that it requires being in an intermediate path to the model, but I'm sure there is a good reason for this). 

If I do figure this out end-to-end, I've already started writing a tutorial for folks such as myself coming into this with minimal Tensorflow experience, to help folks get tfr-bert generating predictions end-to-end with their data.

**Comment by azagniotov** [comment]
@PeterAJansen I am glad I could help. 

Regarding ELWC creation, you may find this closed issue #196 useful. I provided there a code snippet how to create ELWCs programmatically and write them into TF record. I believe that should point you to the right direction when trying to address the:
e.g. Query: Where can you purchase cat food?, Documents: [{text: "the pet food store sells cat food", relevance: "2"}, {text: "the grocery store sells cat food", relevance: "2"}, {text: "cats eat cat food", relevance: "1"}, {text: "a bicycle has two wheels", relevance: "0"}, ...])

**Comment by PeterAJansen** [comment]
Thanks @azagniotov .  I think I'm mostly okay with the ELWC creation from the examples, except as it applies to BERT.   It's not clear to me if the tfr-bert model is expecting just tokenized string input (as in the example below), or whether these need to be converted into BERT token ids.  If the latter is the case, that would seem to break the boundary between the client/server -- the client would need the model (or at least, the vocab file) to transform the tokenized data into indices.

```
# tfrbert_client_example.py

from absl import flags
import tensorflow as tf
import tensorflow_ranking as tfr
import grpc
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc
from tensorflow_serving.apis import input_pb2
from google.protobuf import text_format
from google.protobuf.json_format import MessageToDict

from tensorflow_ranking.extension import tfrbert

# Put together from https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb#scrollTo=eE7hpEBBykVS
def mkToyData():    

    # Query
    CONTEXT = text_format.Parse(
    """
    features {
        feature {
        key: "query_tokens"
        value { bytes_list { value: ["Where", "can", "you", "purchase", "cat", "food", "?"] } }
        }
    }""", tf.train.Example())

    # Documents
    EXAMPLES = [
    text_format.Parse(
    """
    features {
        feature {
        key: "document_tokens"
        value { bytes_list { value: ["The", "pet", "store", "sells", "cat", "food"] } }
        }
        feature {
        key: "relevance"
        value { int64_list { value: 3 } }
        }
    }""", tf.train.Example()),
    text_format.Parse(
        """
    features {
        feature {
        key: "document_tokens"
        value { bytes_list { value: ["Bicycles", "have", "two", "tires"] } }
        }
        feature {
        key: "relevance"
        value { int64_list { value: 1 } }
        }
    }""", tf.train.Example()),    
    text_format.Parse(
        """
    features {
        feature {
        key: "document_tokens"
        value { bytes_list { value: ["The", "grocery", "store", "sells", "cat", "food"] } }
        }
        feature {
        key: "relevance"
        value { int64_list { value: 3 } }
        }
    }""", tf.train.Example()),
    text_format.Parse(
        """
    features {
        feature {
        key: "document_tokens"
        value { bytes_list { value: ["Cats", "eat", "cat", "food"] } }
        }
        feature {
        key: "relevance"
        value { int64_list { value: 2 } }
        }
    }""", tf.train.Example()),    

    ]    

    # Pack as ELWC
    ELWC = input_pb2.ExampleListWithContext()
    ELWC.context.CopyFrom(CONTEXT)
    for example in EXAMPLES:
        example_features = ELWC.examples.add()
        example_features.CopyFrom(example)

    # (Debug) Print ELWC structure
    print(ELWC)

    # Return the fake data
    return ELWC


#
#   Main
#

# Make example data
EXAMPLE_LIST_WITH_CONTEXT_PROTO = mkToyData()

# From https://github.com/tensorflow/ranking/issues/189
example_list_with_context_proto = EXAMPLE_LIST_WITH_CONTEXT_PROTO.SerializeToString()
tensor_proto = tf.make_tensor_proto(example_list_with_context_proto, dtype=tf.string, shape=[1])

timeout_in_secs = 3
request = predict_pb2.PredictRequest()
request.inputs['input_ranking_data'].CopyFrom(tensor_proto)
request.model_spec.signature_name = 'serving_default'   # 'serving_default' instead of 'predict', as per saved_model_cli tool (see https://medium.com/@yuu.ishikawa/how-to-show-signatures-of-tensorflow-saved-model-5ac56cf1960f )
request.model_spec.name = 'tfrbert'

channel = grpc.insecure_channel("0.0.0.0:8500")
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)                            

grpc_response = stub.Predict(request, timeout_in_secs)
unpacked_grpc_response = MessageToDict(grpc_response, preserving_proto_field_name = True)

print("\n")
print("Ranking output:")
print(unpacked_grpc_response['outputs']['output']['float_val'])

```

Output:
```
Ranking output:
[1.1444027, 1.1444027, 1.1444027, 1.1444026]

```

I suspect it's giving identical ranks because it's either expecting lexicon indices for the tokens (instead of the string tokens themselves), or some other feature formatting issue (or, that it's missing the [CLS] and [SEP] tokens for BERT, if those are user supplied instead of supplied by a downstream transformation somewhere in the model). Unless both of those are handled by the model that's loaded,in which case it's likely another issue. Lots of tfr-bert questions, and I'm still digging...

**Comment by azagniotov** [comment]
Hi @PeterAJansen ,

Unfortunately I still have not dabbled with TFR-Bert myself, so I cannot help here, but I am looking forward to your learnings! 

Peter, I do have a question for you based on what I see in your code: you are invoking `serving_default` signature instead of the `predict`, why?  Are you confident that the `serving_default` maps to Predict API? 

For example, the following is the output from running the `saved_model_cli` against one of my models. You can see from the output that the `serving_default` signature maps to `tensorflow/serving/regress` method. In other words, if I would make gRPC requests to `serving_default` signature, I would be actually invoking Regress API. In my case, this is not what I want.

Therefore, I am being explicit by setting the `request.model_spec.signature_name` to be the `predict` in order to guarantee that the Predict API is invoked (i.e.: method `tensorflow/serving/predict`)

I really do not know why `serving_default` signature maps to `tensorflow/serving/regress` method by default, when I generate my `serving_input_receiver_fn` (https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/g3doc/api_docs/python/tfr/data/build_ranking_serving_input_receiver_fn.md)


```
MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['predict']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_ranking_data'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: input_ranking_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1)
        name: groupwise_dnn_v2/accumulate_scores/div_no_nan:0
  Method name is: tensorflow/serving/predict

signature_def['regression']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: input_ranking_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['outputs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1)
        name: groupwise_dnn_v2/accumulate_scores/div_no_nan:0
  Method name is: tensorflow/serving/regress

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['inputs'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: input_ranking_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['outputs'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1)
        name: groupwise_dnn_v2/accumulate_scores/div_no_nan:0
  Method name is: tensorflow/serving/regress
```

**Comment by PeterAJansen** [comment]
@azagniotov , it's a good question.  Choosing the 'predict' signature name from your example in #189 was giving an error, so I checked the signature definition of the tfr-bert model and it appears to expose 'predict' only through 'serving_default', so I'm using that:

```
>saved_model_cli show --dir /tmp/output/servetest-model/export/latest_model/1599260930/ --all
2020-09-04 16:50:43.026553: I tensorflow/stream_executor/platform/default/dso_loader.cc:48] Successfully opened dynamic library libcudart.so.10.1

MetaGraphDef with tag-set: 'serve' contains the following SignatureDefs:

signature_def['serving_default']:
  The given SavedModel SignatureDef contains the following input(s):
    inputs['input_ranking_data'] tensor_info:
        dtype: DT_STRING
        shape: (-1)
        name: input_ranking_tensor:0
  The given SavedModel SignatureDef contains the following output(s):
    outputs['output'] tensor_info:
        dtype: DT_FLOAT
        shape: (-1, -1)
        name: functional_1/tfrbert/Squeeze:0
  Method name is: tensorflow/serving/predict

```

And, the other piece of the puzzle -- in this hacked-together example, it does look like it's expecting pre-bert-encoded features to be served, so both the client /and/ the server would have to have access to the vocabulary file (and, model length) to do this.  

```
# tfrbert_client_example.py

from absl import flags
import tensorflow as tf
import tensorflow_ranking as tfr
import grpc
from tensorflow_serving.apis import predict_pb2
from tensorflow_serving.apis import prediction_service_pb2_grpc
from tensorflow_serving.apis import input_pb2
from google.protobuf import text_format
from google.protobuf.json_format import MessageToDict

from tensorflow_ranking.extension import tfrbert

# Put together from https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb#scrollTo=eE7hpEBBykVS
# and based on the unit test at https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/extension/examples/tfrbert_example_test.py    
def mkToyDataBert():
    # Query
    CONTEXT = text_format.Parse(
    """
    features {
        feature {
            key: "query_tokens"
            value { bytes_list { value: ["Where", "can", "you", "purchase", "cat", "food", "?"] } }
        }
        feature: {
            key: "input_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 3, 4, 0]) + """ } }
        }
        feature: {
            key: "input_mask"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 1, 1, 0]) + """ } }
        }
        feature: {
            key: "segment_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([0, 0, 0, 0]) + """ } }
        }        
    }""", tf.train.Example())


    # Documents
    EXAMPLES = [
    text_format.Parse(
    """
    features {
        feature {
            key: "document_tokens"
            value { bytes_list { value: ["The", "pet", "store", "sells", "cat", "food"] } }
        }
        feature {
            key: "relevance"
            value { int64_list { value: 3 } }
        }
        feature: {
            key: "input_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 4, 3, 0]) + """ } }
        }
        feature: {
            key: "input_mask"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 1, 1, 0]) + """ } }
        }
        feature: {
            key: "segment_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([0, 0, 0, 0]) + """ } }
        }        
    }""", tf.train.Example()),
    text_format.Parse(
        """
    features {
        feature {
            key: "document_tokens"
            value { bytes_list { value: ["Bicycles", "have", "two", "tires"] } }
        }
        feature {
            key: "relevance"
            value { int64_list { value: 1 } }
        }
        feature: {
            key: "input_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([2, 5, 8, 9]) + """ } }
        }
        feature: {
            key: "input_mask"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 1, 1, 1]) + """ } }
        }
        feature: {
            key: "segment_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([0, 0, 0, 0]) + """ } }
        }        
    }""", tf.train.Example()),    
    text_format.Parse(
        """
    features {
        feature {
            key: "document_tokens"
            value { bytes_list { value: ["The", "grocery", "store", "sells", "cat", "food"] } }
        }
        feature {
            key: "relevance"
            value { int64_list { value: 3 } }
        }
        feature: {
            key: "input_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 4, 2, 3]) + """ } }
        }
        feature: {
            key: "input_mask"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 1, 1, 1]) + """ } }
        }
        feature: {
            key: "segment_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([0, 0, 0, 0]) + """ } }
        }        
    }""", tf.train.Example()),
    text_format.Parse(
        """
    features {
        feature {
            key: "document_tokens"
            value { bytes_list { value: ["Cats", "eat", "cat", "food"] } }
        }
        feature {
            key: "relevance"
            value { int64_list { value: 2 } }
        }
        feature: {
            key: "input_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 7, 5, 0]) + """ } }
        }
        feature: {
            key: "input_mask"
            value: { int64_list: { value: """ + mkStaticLengthStrList([1, 1, 1, 0]) + """ } }
        }
        feature: {
            key: "segment_ids"
            value: { int64_list: { value: """ + mkStaticLengthStrList([0, 0, 0, 0]) + """ } }
        }        

    }""", tf.train.Example()),    

    ]   

    # Pack as ELWC
    ELWC = input_pb2.ExampleListWithContext()
    ELWC.context.CopyFrom(CONTEXT)
    for example in EXAMPLES:
        example_features = ELWC.examples.add()
        example_features.CopyFrom(example)


    #return elwc_example
    return ELWC

def mkStaticLengthStrList(values, staticLengthInElems = 128):    
    outStr = "[ "

    length = len(values)
    strList = [str(elem) for elem in values]
    if (len(strList) > staticLengthInElems):
        strList = strList[:staticLengthInElems]

    outStr += ", ".join(strList)

    if (length < staticLengthInElems):
        outStr += ", "
        outStr += ", ".join(["0"] * (staticLengthInElems - length))
    
    outStr += " ]"

    return outStr




#
#   Main
#

# Make example data
EXAMPLE_LIST_WITH_CONTEXT_PROTO = mkToyDataBert()

# From https://github.com/tensorflow/ranking/issues/189
example_list_with_context_proto = EXAMPLE_LIST_WITH_CONTEXT_PROTO.SerializeToString()
tensor_proto = tf.make_tensor_proto(example_list_with_context_proto, dtype=tf.string, shape=[1])

timeout_in_secs = 3
request = predict_pb2.PredictRequest()
request.inputs['input_ranking_data'].CopyFrom(tensor_proto)
request.model_spec.signature_name = 'serving_default'   # 'serving_default' instead of 'predict', as per saved_model_cli tool (see https://medium.com/@yuu.ishikawa/how-to-show-signatures-of-tensorflow-saved-model-5ac56cf1960f )
request.model_spec.name = 'tfrbert'

channel = grpc.insecure_channel("0.0.0.0:8500")
stub = prediction_service_pb2_grpc.PredictionServiceStub(channel)                            

grpc_response = stub.Predict(request, timeout_in_secs)
unpacked_grpc_response = MessageToDict(grpc_response, preserving_proto_field_name = True)

print("\n")
print("Ranking output:")
print(unpacked_grpc_response['outputs']['output']['float_val'])

```

Output:
```
Ranking output:
[1.1729077, -0.069805615, 1.1316329, 1.3779966]

```

The input/output is just nonsense here (since the 'input_ids' are just toy, and don't relate to the document tokens), but the output values (I think these should be interpreted as scores that could be used to rank the documents), but the documents that have more of the same token_ids as the query have higher scores (1.17, 1.13, 1.37) than the document without any of the same token_ids (-0.06), suggesting there's at least a vague notion of similarity guiding the output ranks, so this might be the way to go.  

I can likely extrapolate from your examples how to assemble the ELWC structure programatically, and the unit test ( https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/extension/examples/tfrbert_example_test.py#L101 ) looks to just be dumping the internally-generated data to files to ease the training/tuning, so if I take that approach then there should be a clear path to make things work end-to-end!

**Comment by azagniotov** [comment]
@PeterAJansen yes, the output values are the scores that could be used to rank the documents. 

By the way, I came across an interesting gotcha related to the output scores and the fact that TFR does padding:
Let's say your model expects to see per query 10 documents, but at inference time, your query has 8. The model will respond to you with 10 output scores where the two bottom ones would be two padded dummy scores. 

What I noticed that the padded scores are not always the smallest in the output values (sometimes they were the largest!). So, it is very important to first truncate them, before ranking the documents in desc order based on the output values desc order.

Just fun fact, I thought I would share

**Comment by PeterAJansen** [comment]
@azagniotov very helpful, thanks!

Upon more investigation, it looks like there's actually a helper function in TFRBertUtil() called convert_to_elwc() that does most of the work for encoding from text to BERT ELWC -- this is basically most of the work.  I'm not sure why it's not used in the example, or mentioned in the documentation. 

The negative is that the client side does need the vocab file, and certain model parameters (token length limit, cased/uncased setting), but otherwise it does appear to produce ranking predictions easily:

```
def create_tfrbert_util_with_vocab(bertMaxSeqLength, bertVocabFile, do_lower_case):
    return tfrbert.TFRBertUtil(
            bert_config_file=None,
            bert_init_ckpt=None,
            bert_max_seq_length=bertMaxSeqLength,
            bert_vocab_file=bertVocabFile,
            do_lower_case=do_lower_case)

bertVocabFilename = "/home/peter/github/tensorflow/ranking/uncased_L-4_H-256_A-4_TF2/vocab.txt"
do_lower_case = True
bert_helper = create_tfrbert_util_with_vocab(128, bertVocabFilename, do_lower_case)

context = "Where can you buy cat food?"
documents = ["The pet food store", "Bicycles have two wheels", "The grocery store", "Cats eat cat food"]
labels = [3, 1, 3, 2]
label_name = "relevance"
elwcOut = bert_helper.convert_to_elwc(context, documents, labels, label_name)

print(elwcOut)

# Make example data
EXAMPLE_LIST_WITH_CONTEXT_PROTO = elwcOut
...

```

**Comment by azagniotov** [comment]
Hi @PeterAJansen that's really good stuff!

**Comment by PeterAJansen** [comment]
Update:

I've put together a tutorial in the form of a blog post and forked repository that help illustrate getting TFR-BERT working end-to-end: 

http://cognitiveai.org/2020/09/08/using-tensorflow-ranking-bert-tfr-bert-an-end-to-end-example/

Hopefully this is useful to folks not familiar with Tensorflow Ranking who are hoping to get up and running with TFR-BERT as quickly as possible.

**Comment by xuanhuiwang** [comment]
@PeterAJansen, this is awesome!
