### ISSUE TITLE
Non-textual features in TFR-Bert

### ISSUE THREAD

**Issue by davidmosca** [tensorflow/ranking#230]
Hi, in the "traditional" TF-Ranking, it is possible to have in the context and/or examples:
- numerical features (in addition to the textual features), e.g. an array of floating numbers
- more than one textual feature (per context or example)

Is this possible TFR-Bert as well?
Thanks.

**Comment by HongleiZhuang** [comment]
Hi @davidmosca 

The vanilla [`TFRBertRankingNetwork`](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/extension/tfrbert.py#L32) only takes BERT-related features as input. However, you can always subclass it to create your own ranking network which is capable of taking numerical features. You can essentially rewrite the [`score`](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/extension/tfrbert.py#L92-L116) method to include numerical features and decide how you want them to be incorporated into the model. 

Similarly, if you want to support multiple textual features, you can create a subclass of `TFRBertRankingNetwork`. In your `score` method, you may introduce another set of inputs for your additional textual feature and perhaps feed them into the same BERT encoder, and come up with the model structure to combine them together. 

Let me know if this answers your questions.

Thank you!

**Comment by davidmosca** [comment]
Thanks for the explanation.

**Comment by TPF2017** [comment]
Hi @HongleiZhuang 

I want to know how to add context features in the tutorial [tfr_bert.ipynb](https://github.com/tensorflow/ranking/blob/master/docs/tutorials/tfr_bert.ipynb)，is there a convenient way? Thanks!
