### ISSUE TITLE
Regarding Version 0.1.2 and lower.

### ISSUE THREAD

**Issue by sdeepaknarayanan** [tensorflow/ranking#231]
Hi,

The versions 0.1.2 and lower are currently available on PyPi, however I cannot find their releases on this repository. Are those versions still supported? Can you share the list of dependencies if they are supported?

Thanks

**Comment by ramakumar1729** [comment]
@sdeepaknarayanan : We do not have a release snapshot for the versions before 0.1.3. Any reason you want to use the older versions instead of the latest ones? We have significantly updated the capabilities since v0.1.3.

**Comment by ramakumar1729** [comment]
Closing this issue. Feel free to reopen.
