### ISSUE TITLE
Custom object required to load a TFR model?

### ISSUE THREAD

**Issue by pentney** [tensorflow/ranking#237]
I saved a TF ranking model compiled as follows:

        network = tfr.keras.canned.DNNRankingNetwork(
            context_feature_columns=context_feature_columns,
            example_feature_columns=example_feature_columns,
            hidden_layer_dims=[num_hiddens],
            activation=tf.nn.relu,
            activity_regularizer=tf.keras.regularizers.L2(l2),
            use_batch_norm=True,
            batch_norm_moment=0.999,
            dropout=0.3, name='dnn_ranking_network')
        return tfr.keras.model.create_keras_model(
            network, tfr.keras.losses.PairwiseHingeLoss(),
            metrics, adam, None)

What specific custom objects must I add when using load_model to load this? Right now I'm getting

ValueError: Unable to restore custom object of type _tf_keras_metric currently. Please make sure that the layer implements `get_config`and `from_config` when saving. In addition, please use the `custom_objects` arg when calling `load_model()`.

when I try to load the saved model.

**Comment by ramakumar1729** [comment]
@pentney : Can you check if this is still an issue? We have added serialization [support](https://github.com/tensorflow/ranking/blob/019a7db68d83959b8774bc77bfb6905180504216/tensorflow_ranking/python/keras/metrics.py#L180) for all keras metrics and losses. You do not need `custom_objects` anymore.

**Comment by ramakumar1729** [comment]
@pentney : closing this for now. Please reopen if the solution in the previous comment does not work for you.
