### ISSUE TITLE
code for MARCO Passage Ranking

### ISSUE THREAD

**Issue by tangzhy** [tensorflow/ranking#240]
Hi, I've just come across your amazing results in MARCO passage ranking task and related paper.

But I see neither tutorial nor any example code on how to incorporate BERT in your framework.

Will you release codes for passage ranking task? 

Any suggestion for my purpose will be much appreciated, thanks~

**Comment by HongleiZhuang** [comment]
Hi @tangzhy, 

Please refer to [TFR-BERT](https://github.com/tensorflow/ranking/tree/master/tensorflow_ranking/extension#tfr-bert-extension) for how to incorporate BERT into TF-Ranking. The submission our team member produced for the MSMARCO passage ranking task basically includes multiple runs of this model with different configurations etc.
