### ISSUE TITLE
Current handle_sparse_features.ipynb TF version incompatible with tensorflow-serving-apis

### ISSUE THREAD

**Issue by franckjay** [tensorflow/ranking#245]
I have tried getting the notebook to run in Colab for the last few days with little luck. I finally managed to get all of the packages imported by making the following changes:

1. Colab was setting the default Python interpreter to 2, while 3 is required
2. TF version 2.1.0 is not compatible the version of `tensorflow-serving-apis` when using `pip install` 
3. Changing the TF version to 2.4.1 seemed to work
4. Comment out the grpc uninstall, install .

**Comment by ramakumar1729** [comment]
PR #243 fixes this. Feel free to reopen this if you are still facing an issue.
