### ISSUE TITLE
Filtering

### ISSUE THREAD

**Issue by eggie5** [tensorflow/ranking#249]
From the code below, it is clear that I only want impressions from `cbsa=Phoenix-Mesa-Chandler AZ`. Needless-to-say unbatching just to use filter function is not an acceptable solution. 

What's the right way to do arbitrary filtering?

```
    dataset = tfr.data.build_ranking_dataset(
        pattern,
        tfr.data.SEQ,
        batch_size,
        context_feature_spec=context_feature_spec,
        example_feature_spec=example_feature_spec,
        list_size=list_size
    )

    dataset = dataset.unbatch()
    dataset = dataset.filter(lambda features: features['cbsa']=="Phoenix-Mesa-Chandler AZ")
    dataset = dataset.batch(batch_size)
```

PS. Thanks for all your hard work and for open sourcing this work -- it's powering the rankings on the grubhub front page!

**Comment by ramakumar1729** [comment]
@eggie5 : For batched datasets, I do not see a way without unbatching: See [https://www.tensorflow.org/guide/data#datasets_sampling](https://www.tensorflow.org/guide/data#datasets_sampling). A more efficient approach might be to do the filtering before `dataset.batch` in [build_ranking_dataset_with_parsing_fn](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/g3doc/api_docs/python/tfr/data/build_ranking_dataset_with_parsing_fn.md#tfrdatabuild_ranking_dataset_with_parsing_fn).

**Comment by eggie5** [comment]
@ramakumar1729 yes, it seems i'd have to swap the order of this `batch` 
https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/data.py#L955 
with the subsequent `map` which follows it. 

This would effectively be `map(parse) > filter > batch` instead of `batch > map(parse)` and hope that I don't loose too much pipeline throughput by parsing (mapping) across examples instead of batches.

I'm worried that if patch the function it'll break compatibility for future upgrades/api changes.

**Comment by ramakumar1729** [comment]
Right. tf.data transformations are designed to be functional, so you can compose them in any order in your custom dataset builder. Another approach is to use map over batched data, but apply filtering by setting the filtered feature values to zero and generating a "feature mask".

**Comment by eggie5** [comment]
@ramakumar1729 thanks, I'll have think about this feature mask idea a bit more...

**Comment by ramakumar1729** [comment]
@eggie5 : any updates on this issue? Feel free to close this one.

**Comment by eggie5** [comment]
@ramakumar1729 no updates and I've had to move on to other priorities.

**Comment by ramakumar1729** [comment]
Thanks @eggie5 . Closing this issue.
