### ISSUE TITLE
tf-ranking for distributed training

### ISSUE THREAD

**Issue by 2012060010010** [tensorflow/ranking#25]
can you provide a distributed training demo on multi-GPU or multi-Machines?

**Comment by lasclocker** [comment]
Please refer to [tf_ranking_libsvm.py](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py),  TF-Ranking is made by [Estimator](https://www.tensorflow.org/guide/estimators), so when you use **train_and_evaluate**, this utility function provides consistent behavior for both local
  (non-distributed) and distributed configurations.

**Comment by ramakumar1729** [comment]
Thanks @lasclocker for the details. Please take a look at [Distributed Training in TensorFlow](https://www.tensorflow.org/guide/distribute_strategy) for more details on this.

**Comment by rkonowk** [comment]
I have followed the articles and links provided and tried to support distributed ranking using multi-GPU. However, when using any of the tf.distribute strategies, let's say tf.contrib.distribute.MirroredStrategy, and try to use it in the example as follows in get_estimator.

` strategy = tf.contrib.distribute.MirroredStrategy()
  config = tf.estimator.RunConfig(train_distribute=strategy)
  return tf.estimator.Estimator(
      model_fn=tfr.model.make_groupwise_ranking_fn(
          group_score_fn=make_score_fn(),
          group_size=1,
          transform_fn=None,
          ranking_head=ranking_head,),
      config = config,
      params=hparams)`

Then it fails during training giving the following error:
> ValueError: dataset_fn() must return a tf.data.Dataset when using a tf.distribute.Strategy.

I have tried to change input_fn to return a  tf.dataset instead, but if I do this, then training will finish just after the first step.

Could you provide some hints or directions on how should input_fn be modified such that train can consume it correctly and at the same time, make the distributed strategy happy? :) Thanks!

**Comment by nishathussain** [comment]
@rkonowk 
dataset_fn() should return either tf.data.Dataset or a function.. wrap it to make it a function. 

def dataset_fn()
     def func1():
         <Your existing code>
         return <your existing return from dataset_fun>
return func1

**Comment by Vniex** [comment]
@nishathussain  after warp the dataset_fn, the transform_fn will output the error since it only accepts the features in input_fn
