### ISSUE TITLE
Saved model gives different predictions

### ISSUE THREAD

**Issue by yzhangswingman** [tensorflow/ranking#252]
I did a sanity check on saved model of my own implementation trying to ensure training/serving consistency by comparing the predictions on the same inputs from the trained model in memory and deserialized keras model. The test failed.

I also tried the sanity test on `antique_kfp_kin` example model, `ModelTrainAndEvaluateTest.test_train_and_eval_no_use_din` passed but `ModelTrainAndEvaluateTest.test_train_and_eval_use_din` failed. 

Simple test code as below.
```python
  # Saved model sanity check
  saved_model = tf.keras.models.load_model(saved_model_path)

  # check predictions are identical
  pred_inputs, _ = next(iter(train_dataset))
  pred = model(pred_inputs, training=False)
  pred2 = saved_model(pred_inputs, training=False)

  tf.debugging.assert_equal(pred, pred2)
```

BTW, in testing my own model, saved model have identical weights, while in `test_train_and_eval_use_din`, reloaded weights are different from in memory.

Any idea as to why? Is it an issue in custom layer implementation, e.g., my custom layer, `tfr.keras.layers.DocumentInteractionAttention` (or its underlying tf-models SelfAttention layer? Or KPL layers? Or something bigger in core tf? 

Looking forward to your reply.
I hope it's just user error, otherwise I guess I need to seriously consider switching to some other deep learning frameworks. 

Thanks.

**Comment by ramakumar1729** [comment]
@yzhangswingman : `DocumentInteractionAttention` layer has been updated to fix this issue. Take a look at `antique_kpl_din_test.py` in this [commit](https://github.com/tensorflow/ranking/commit/09a338c6910d7f838d5be14e1b0fa865e09d56e3), which ensures predictions match after saving/loading a SavedModel. Apologies for the delay, this issue was quite involved with a lot of discussion with Keras and SavedModel teams.

**Comment by yzhangswingman** [comment]
@ramakumar1729 Awesome! Thanks! Can you also shed some light on the general cause of such issue so that I can avoid the pitfalls with my own custom layers. Thank you!

**Comment by ramakumar1729** [comment]
@yzhangswingman : The issue has to do with building layers with custom signatures (such as MultiHeadAttention) when loading back from SavedModel. From my understanding, this arises only with `tf.keras.model.load_model()`, but not if you use the lower level SavedModel loading APIs such as `tf.saved_model.load()`.

Let me know if you have any further questions.

**Comment by ramakumar1729** [comment]
Closing this issue as it has been addressed in this [commit](https://github.com/tensorflow/ranking/commit/09a338c6910d7f838d5be14e1b0fa865e09d56e3). Thanks @yzhangswingman for identifying this: this is a subtle bug and addressing this has helped improve our code and udnerstanding.
