### ISSUE TITLE
Any example code to use tf.dataset API to read data in  tensorflow-ranking?

### ISSUE THREAD

**Issue by 2012060010010** [tensorflow/ranking#26]
I have a big data in libsvm format just like dummy data, but I can not put it in RAM. So,  tf-ranking-example is not suite for big data.

**Comment by ramakumar1729** [comment]
The example code does use tf.data API for reading data, in conjunction with [libsvm_generator](https://github.com/tensorflow/ranking/blob/55d9e2c7fdf85afd82865b9a3eb1f4769cd992ed/tensorflow_ranking/python/data.py#L427). This generator groups all datapoints with the same query ID to generate a listwise datapoint: with query features and all related document features. Hence this would scale for datasets that do not fit in memory.  

You can also look at the [python script](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py) for libsvm data, which should work for datasets that do not fit in memory.

**Comment by kkonevets** [comment]
I played with tf_ranking_libsvm.ipynb example which uses libsvm_generator you mentioned, but I can tell that performance was really poor when I did that - [see it](https://github.com/tensorflow/ranking/issues/22)
Is there a better way to load data? Ideally tfrecord format is wanted.

**Comment by 2012060010010** [comment]
def decode_line(line):
    # Decode the csv_line to tensor.
    record_defaults = [[0.0] for _ in range(feat_num)]
    items = tf.decode_csv(line, record_defaults, field_delim=",")
    features = items[1:]
    label = items[0]
    label = tf.cast(label, tf.int64)
    return features, label
filenames = ["hdfs_path/train_mq.csv"]
dataset = tf.data.TextLineDataset(filenames).skip(1)
dataset = dataset.map(decode_line)
print("DATASET_1", dataset)

this is my code, my data is stored in hdfs, can not use "with open" to read data, but param (feature, labels) input in get_train_inputs() is a dict and an array.

**Comment by 2012060010010** [comment]
> The example code does use tf.data API for reading data, in conjunction with [libsvm_generator](https://github.com/tensorflow/ranking/blob/55d9e2c7fdf85afd82865b9a3eb1f4769cd992ed/tensorflow_ranking/python/data.py#L427). This generator groups all datapoints with the same query ID to generate a listwise datapoint: with query features and all related document features. Hence this would scale for datasets that do not fit in memory.
> 
> You can also look at the [python script](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py) for libsvm data, which should work for datasets that do not fit in memory.

my data is stored in hdfs, can not use "with open" to read data.

**Comment by kkonevets** [comment]
I am not an expert, but as far as I know, the fastest way to load data is tfrecord file (with multithreading out of the box). You can always transform hdfs to tfrecord. The question is who will write efficient data transformer from libsvm format to tfrecord. If your data is sparse libsvm format will be fine because it supports sparsity.

**Comment by ramakumar1729** [comment]
> def decode_line(line):
> # Decode the csv_line to tensor.
> record_defaults = [[0.0] for _ in range(feat_num)]
> items = tf.decode_csv(line, record_defaults, field_delim=",")
> features = items[1:]
> label = items[0]
> label = tf.cast(label, tf.int64)
> return features, label
> filenames = ["hdfs_path/train_mq.csv"]
> dataset = tf.data.TextLineDataset(filenames).skip(1)
> dataset = dataset.map(decode_line)
> print("DATASET_1", dataset)
> 
> this is my code, my data is stored in hdfs, can not use "with open" to read data, but param (feature, labels) input in get_train_inputs() is a dict and an array.

@2012060010010 : Can you try tf.gfile.Open instead of open?

**Comment by ramakumar1729** [comment]
> I am not an expert, but as far as I know, the fastest way to load data is tfrecord file (with multithreading out of the box). You can always transform hdfs to tfrecord. The question is who will write efficient data transformer from libsvm (de facto ranking standard format) format to tfrecord. If your data is sparse, libsvm format will be just fine because it supports sparsity.

It makes sense to use TFRecord for storing large amounts of data, particularly in cases where it does not fit in memory. This is not particular to tensorflow ranking; you can look at how to create TFRecords and how to read [TFRecords](https://www.tensorflow.org/guide/datasets#consuming_tfrecord_data) using tf.data piepline for more details on this.

**Comment by ramakumar1729** [comment]
Closing this for now. Please reopen if there are any further issues.

**Comment by AStupidBear** [comment]
@ramakumar1729 The following line is In the [code](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py): "WARNING: All data sets are loaded into memory in this sample code. It is for small data sets whose sizes are < 10G". So why did you say "should work for datasets that do not fit in memory" ?
