### ISSUE TITLE
MultiTaskModelBuilder seems to be missing

### ISSUE THREAD

**Issue by richardimms** [tensorflow/ranking#262]
The [MultiTaskPipeline](https://github.com/tensorflow/ranking/blob/77f280075e220946d0935b44b64770f4dabb37d0/tensorflow_ranking/python/keras/pipeline.py#L751) references a `MultiTaskModelBuilder` in doc string but there is no `MultiTaskBuilder`, has this been omitted from the release or is something being released in the future?

**Comment by lyyanlely** [comment]
`MultiTaskModelBuilder` is not defined. It can be constructed by `ModelBuilder` with a `MultiTaskScorer`, please check the unit test `test_pipeline_with_multi_task` in `pipeline_test.py`.
