### ISSUE TITLE
How to do prediction using ranker object written in sample notebook?

### ISSUE THREAD

**Issue by Anticsss** [tensorflow/ranking#27]

**Comment by ramakumar1729** [comment]
The ranker is a tf.estimator.Estimator object, and hence support [predict](https://www.tensorflow.org/api_docs/python/tf/estimator/Estimator#predict) function. This would look similar to ranker.evaluate, except that the input_fn can generate only features and no labels.

**Comment by eggie5** [comment]
```
for x in ranker.predict(input_fn=lambda: input_fn_eval(test_path)):
    print(x)
```
