### ISSUE TITLE
Bug in tfr.data.build_ranking_serving_input_receiver_fn

### ISSUE THREAD

**Issue by CYL586309** [tensorflow/ranking#276]
There is a bug in tfr.data.build_ranking_serving_input_receiver_fn. Since the features(data_format=tfr.data.SEQ) in my dataset are all sparse, I utilize tf.feature_column.embedding_column to transform them as embeddings. However, I meet an error while I save the pb model by using tfr.data.build_ranking_serving_input_receiver_fn in tf.estimator.

```sh
File "**/tensorflow_ranking/python/data.py", line 660, in parse
    example_sizes = tf.stack([sizes[k] for k in sorted(sizes.keys())], axis=1)
  File "**/tensorflow/python/util/dispatch.py", line 201, in wrapper
    return target(*args, **kwargs)
  File "**/tensorflow/python/ops/array_ops.py", line 1405, in stack
    value_shape = ops.convert_to_tensor(values[0], name=name)._shape_tuple()  # pylint: disable=protected-access
IndexError: list index out of range
```
The error indicates that  the variable `sizes` may be **null**. Therefore, I check the data.py and find the variable `sizes`, which is derived from output dict of tf.io.parse_sequence_example. The meaning of `sizes` is the lengths of any dense feature_list features ([tf.io.parse_sequence_example](https://tensorflow.google.cn/api_docs/python/tf/io/parse_sequence_example?hl=en)). The features in my dataset are all sparse,  so `sizes` is null. 
Finally, I add if-else  in line 660 of data.py as follows:
```python
if sizes:
  example_sizes = tf.stack([sizes[k] for k in sorted(sizes.keys())], axis=1)
  sizes = tf.reduce_max(input_tensor=example_sizes, axis=1)
else:
  sizes = 0
```
which is able to solve the bug. I look forward to the bug will be solved by the tfr team in the future, and appreciate it.

**Comment by rjagerman** [comment]
Should be fixed in v0.4.1 with commit 716c7db1ec223749a63fb7f465b4753ba38de3f4.
