### ISSUE TITLE
approx_ndcg_loss loss is not detected

### ISSUE THREAD

**Issue by NarasimhaM3101** [tensorflow/ranking#28]
hi, 

I want to downloaded latest repo and test approx_ndcg_loss. But the key is not picked up from the losses package, for some reason. 

I tried debugging and found that "key_to_fn" doesn't list "RankingLossKey.APPROX_NDCG_LOSS" in debug mode. Not sure why. 

Could someone please fix this or guide ASAP? 

Thanks,
Narasimha

**Comment by NarasimhaM3101** [comment]
This issue was caused because the tensorflow-ranking package did not get updated properly when I built it again.... 

While the package info was updated, the internal files in /python folder (including losses.py) did not get updated. 

You can close this issue. Also it would be nice if there is robust check..

**Comment by ramakumar1729** [comment]
Glad that you were able to use this. I'm not sure why the build didn't update properly. We will try to reproduce this on our side. Let us know if you face any related issues. 

Closing this issue for now.
