### ISSUE TITLE
Anyone tried to train with compressed ELWC tfrecords?

### ISSUE THREAD

**Issue by vitalyli** [tensorflow/ranking#286]
Anyone tried to train with compressed ELWC tfrecords?
Strangely it's not understanding that the data was GZIP compressed by TFRecordWriter.

**Comment by rjagerman** [comment]
You probably need to specify that you are reading gzip compressed files in the `TFRecordReader`. If you are using `tensorflow_ranking.data.build_ranking_dataset`, you can specify reader-specific arguments via the `reader_args` keyword argument.

For example you could do something like this:

```python
build_ranking_dataset(
    ...,
    reader_args=dict(compression_type="GZIP"))
```
