### ISSUE TITLE
How to use embedding vectors in lambdamart

### ISSUE THREAD

**Issue by NarasimhaM3101** [tensorflow/ranking#29]
How to use embedding vectors ? An example or two could go a long way in using the package. 

Regards,
Narasimha

**Comment by ramakumar1729** [comment]
Please take a look at this [unit test](https://github.com/tensorflow/ranking/blob/55d9e2c7fdf85afd82865b9a3eb1f4769cd992ed/tensorflow_ranking/python/feature_test.py#L175) on how to use embedding vectors.

**Comment by ramakumar1729** [comment]
Created an issue #31 to track support for a demo on sparse/dense/embedded features usage. Closing this for now.
