### ISSUE TITLE
[Feature Request] Building ranking models using Keras.

### ISSUE THREAD

**Issue by ramakumar1729** [tensorflow/ranking#32]

**Comment by daanvdn** [comment]
Hi @ramakumar1729, is there a timeline / as to when it will be possible to write idiomatic TF 2.0 code with TF-ranking? Or is this already possible?

**Comment by bduclaux** [comment]
This would be a great feature !

**Comment by ELind77** [comment]
I see it's been a month since this issue was assigned.  Are there any updates?

**Comment by dynamicwebpaige** [comment]
See also [#25445](https://github.com/tensorflow/tensorflow/issues/25445).

**Comment by ramakumar1729** [comment]
We now provide support for building ranking models using Keras APIs. See announcement #180 . Thank you all for your patience.
