### ISSUE TITLE
Groupwise ranking data generator example for group_size =2 or >1

### ISSUE THREAD

**Issue by NarasimhaM3101** [tensorflow/ranking#35]
Could you please share an example for what format the input_fn or tf.data.Dataset.from_generator should be generated for group wise ranking functions? Assume group_size = 2 would suffice for majority of the cases. 

Thanks,
Narasimha

**Comment by ramakumar1729** [comment]
The data looks the same, irrespective of group size. The output of input_fn is a 2-D tensor for each context feature and a 3-D for each per-example (or say, per-document) features.
The `group_size` is a hyperparameter that the user can set.

**Comment by eggie5** [comment]
As far as I can tell, the output of the libsvm `input_fn` is a size 2 tuple, where the first element is a dictionary w/ `_NUM_FEATURES` keys, where each key is a key is a tensor `[batch_size, list_size, features_size]. Are these the 3D document/example tensors you describe above? What is the 2D context/query tensor in the libsvm output?

**Comment by xuanhuiwang** [comment]
There is no 2-D tensor for libsvm data.

**Comment by xuanhuiwang** [comment]
Closing this one.

**Comment by korosig** [comment]
Have you solved the issue? Do you have a simple example of the mentioned task? I want to create a ranking model for ranking students by their achievements (in each class), where each class contains 20 students.
