### ISSUE TITLE
v0.5.3 not available on pypi

### ISSUE THREAD

**Issue by JackGammack** [tensorflow/ranking#352]
Hi, I'm trying to `pip install tensorflow-ranking==0.5.3`, but running into issues because v0.5.3 [isn't available on pypi](https://pypi.org/simple/tensorflow-ranking/). Is it possible to publish this version to pypi?

**Comment by lyyanlely** [comment]
Thanks for the question. The pypi is now updated. Please give a try.

**Comment by JackGammack** [comment]
Perfect, thanks!
