### ISSUE TITLE
Who can add AUC metrics to metrics.py?

### ISSUE THREAD

**Issue by 2012060010010** [tensorflow/ranking#36]

**Comment by ramakumar1729** [comment]
Please take a look at  [AUC metrics function](https://www.tensorflow.org/api_docs/python/tf/metrics/auc) in Tensorflow. You can add pass this metric to the estimator, similar to how it is done in the [demo](https://github.com/tensorflow/ranking/blob/d7008f2360b4a98a94aada910194503803dcce5a/tensorflow_ranking/examples/tf_ranking_libsvm.py#L254) code.

**Comment by ramakumar1729** [comment]
Closing this for now.

**Comment by eggie5** [comment]
Is Ordered Pair Accuracy the same as binary AUC like in the BPR paper? Where you take all pairs of labels and scores and make sure the order is preserved? 

For example in the Ordered Pair Accuracy test:

https://github.com/tensorflow/ranking/blob/d7008f2360b4a98a94aada910194503803dcce5a/tensorflow_ranking/python/metrics_test.py#L367-L375

Taking every pair of labels and giving a +1 where the order is preserved:

For the first batch of labels [0,0,1], there are 3 pairs:
0,0=0
0,1=1
0,1=0
     =`1/3` (but the test case says it should be `1/2`

and then for the second batch: [0,1,2]
0,1=1
0,2=1
1,2=1
     =`3/3=1` (order is perfectly preserved and matches the test case)

(1/3+3/3 )/ 2= `.666` (the two scored averaged)

However, the test case says it should be equal to this:

(1. + 3.) / (2. + 3.) = `0.8`

**Comment by mbw314** [comment]
Revisiting this... I've been thinking about just how OPA and AUC are different. Looking back at the BPR paper (section 4.1.1), I see that AUC only considers pairs where one item is "positive" and the other is "negative"; indeed, the [LightFM documentation for AUC score](http://lyst.github.io/lightfm/docs/lightfm.evaluation.html#lightfm.evaluation.auc_score) says this:

```
Measure the ROC AUC metric for a model: the probability that a randomly 
chosen positive example has a higher score than a randomly chosen negative 
example. A perfect score is 1.0.
```

We can take "positive" to mean relevance label of 1 or more, and "negative" to mean relevance label of 0. In the example above, the AUC is `(1/2 + 2/2)/2 = 0.75` (each query has a pair with equal relevance that gets discarded).

The [Ordered Pair Accuracy documentation](https://github.com/tensorflow/ranking/blob/8769d07fe88c77e4d010e39d3437818e35c7b135/tensorflow_ranking/python/metrics.py#L550) says this:

``` 
Computes the percentage of correctedly ordered pair. [sic]

For any pair of examples, we compare their orders determined by `labels` and
`predictions`. They are correctly ordered if the two orders are compatible.
That is, labels l_i > l_j and predictions s_i > s_j and the weight for this
pair is the weight from the l_i.
```

So, pairs with equal relevance are not considered. This means if we restrict to binary relevance, then OPA and AUC compute the same score for a single query. However, AUC averages these scores across all queries, whereas OPA does not: it calculates `# correctly ordered pairs / # comparable pairs` across the entire dataset.

I think the reason for this difference is that AUC is expecting one query per user, with that user's (training or validation) positive items appearing exactly once in that query, whereas a dataset for TF-Ranking can be much more general: the same user can appear many times with different combinations of positive items.

@eggie5, does this make sense?

@ramakumar1729, I think the original request for AUC is reasonable and I'd like to add my support for that feature. (I'm not sure that the AUC function linked above is applicable here.)
