### ISSUE TITLE
is there any example to send raw text to the ranker ?

### ISSUE THREAD

**Issue by tiru1930** [tensorflow/ranking#4]
Is there any example where i can send raw text qurey and document with their relevance score (i,e 0,1) so that i can train ranker

**Comment by ramakumar1729** [comment]
Hi, we do show how to deal with sparse features, using feature columns in a test case within ranking/python/feature_test.py. You can see it at https://github.com/tensorflow/ranking/blob/ad3414264945b5613a6aa8ff732cc415b89db0e4/tensorflow_ranking/python/feature_test.py#L175.

We do not have an example for raw text yet; we are planning to upload one.

**Comment by eggie5** [comment]
@ramakumar1729 after the call to `test_encode_listwise_features` you get back two dictionaries for context and example. Then what are you supposed to do with it? What do you pass it to? In other words, I see the unit tests, but how do you use `encode_listwise_features`?

**Comment by ramakumar1729** [comment]
@eggie5 : Sorry I just saw this. I guess you have figured this already, or would you like me to elaborate?

**Comment by eggie5** [comment]
@ramakumar1729 all good ✌️
