### ISSUE TITLE
Losses & Metrics Ignore Negative Numbers?

### ISSUE THREAD

**Issue by eggie5** [tensorflow/ranking#40]
The ranking metrics in TF Ranking seem to ignore negative numbers, which I think is a nice thing, is this a feature? Where is this in the code?

```
#the ranking metrics seem to ignore -1s....
labels = [[-1, 1., 0.]]
scores = [[3, 1., 0.]]

weights_feature_name = 'weights'
features = {weights_feature_name: weights}
dcg = tfr.metrics.make_ranking_metric_fn(tfr.metrics.RankingMetricKey.DCG)
val, op = dcg(labels, scores, None)

with tf.Session() as sess:
    sess.run(tf.global_variables_initializer())
    sess.run(tf.local_variables_initializer())
    print(sess.run(op))
```
```
1.0
```

For example, a common DGC implementation will not ignore negatives:

```
labels=[[-1, 1., 0.]]
r = np.asarray(labels)
dcg = lambda r: np.sum(r/np.log2(np.arange(2, r.size+2)))
dcg2 = lambda r: np.sum((np.power(2,r)-1)/np.log2(np.arange(2, r.size+2)))
dcg(r), dcg2(r)
```

```
(-0.36907024642854247, 0.13092975357145753)
```

I just want to confirm, b/c I want to use this behavior to generate libsvm data for queries where I only have implicit judgements from clickthrough data. For example, the query:

```
A
B
C (clicked)
D
E
```

Means that C should be ranked above B and A, but we can't make any judgements about D and E. Encoded in libsvm format:

```
0 qid:1 [features] #A
0 qid:1  [features] #B
1 qid:1  [features] #C
-1 qid:1  [features] #D
-1 qid:1 [features] #E
```

If we use the Pairwise Logistic loss I should be able to learn `C>B` and `C>A` and then use the ranking metrics to evaluate my ranker against queries in my test set.

**Comment by xuanhuiwang** [comment]
Yes, all negative labels are assumed to be invalid. You can follow the call path from here: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/metrics.py#L222.
