### ISSUE TITLE
Thanks a lot for your share. Would you please give some examples for LTR methods implemented in this project, such as RankNet, ListNet and LambdaMART

### ISSUE THREAD

**Issue by whuissyxa** [tensorflow/ranking#43]

**Comment by eggie5** [comment]
👍

**Comment by robertwt7** [comment]
Yeah would love to see some of the tree implementation of LTR in the scoring function :)

**Comment by bendersky** [comment]
For a complete list of supported LTR methods see https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/losses.py
which contains definitions of supported losses.

1/ RankNet can be implemented "pairwise_logistic_loss" function  (l. 639 in losses.py)
2/ ListNET -- from this family of listwise LTR algorithms we support the position-aware ListMLE (l. 862 in losses.py) which was found to improve upon ListNET in prior work (https://dl.acm.org/citation.cfm?id=3020798)
3/ LambdaMART -- at this point the package is mostly focused on "neural LTR" algorithms. We do not have current plans to support tree-based algorithms. There are several of high-quality open-sources alternatives you could consider including LightGBM, XGBoost and others.
