### ISSUE TITLE
libSVM Parser Shuffles Documents

### ISSUE THREAD

**Issue by eggie5** [tensorflow/ranking#44]
Using the libsvm parser I noticed my documents were getting shuffled. I found this code:

https://github.com/tensorflow/ranking/blob/d7008f2360b4a98a94aada910194503803dcce5a/tensorflow_ranking/python/data.py#L411

Why would one shuffle the documents? Doesn't the order (position) of your relevance labels imply meaning? Wouldn't this throw off DCG? 

DCG for reference: 

![DCG = \sum^n_{i=1} \frac{rel_i}{\log(i+1)}](https://latex.codecogs.com/gif.latex?DCG%20%3D%20%5Csum%5En_%7Bi%3D1%7D%20%5Cfrac%7Brel_i%7D%7B%5Clog%28i&plus;1%29%7D)

```
dcg = lambda r: np.sum(r/np.log2(np.arange(2, r.size+2)))
```

**Comment by ramakumar1729** [comment]
Learning to rank algorithms ideally do not depend on the input order of the list of documents. DCG and other measures are over the ranking induced by the scores for the documents, and the position/rank of relevance labels within this. 

Let me know if you have any further questions.

**Comment by eggie5** [comment]
Is there any particular reason `tf_ranking_libsvm.py` (the non-notebook example) doesn't shuffle?

https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py#L116

**Comment by xuanhuiwang** [comment]
Since we only keep the `list_size` number of documents, shuffling makes us select a random set of `list_size` documents for every call. Otherwise, we only keep the top `list_size` documents.

Personally, I prefer to non-shuffling version.
