### ISSUE TITLE
Model export

### ISSUE THREAD

**Issue by nzhiltsov** [tensorflow/ranking#46]
Could you please give a code example of how to export a model for TensorFlow Serving? No luck with `estimator.export_saved_model` or `tf.estimator.BestExporter`. I must be doing something wrong with feature_spec.

**Comment by eggie5** [comment]
👍 I'll be trying this soon and looking for any best practices. It's straight forward to export `Estimators` in general, but any special cases for "TF Ranking" estimators?

**Comment by ramakumar1729** [comment]
[tf.estimator.EvalSpec](https://www.tensorflow.org/api_docs/python/tf/estimator/EvalSpec) takes in exporters as an input. You can specify the exporter there. 

`export_saved_model` should also work. @nzhiltsov : Can you share your code?

**Comment by nzhiltsov** [comment]
Thanks for the quick reaction. I think I've figured it out:
```
def serving_input_receiver_fn():
    feature_names = ["{}".format(i + 1) for i in range(FLAGS.num_features)]
    feature_columns = [tf.feature_column.numeric_column(
          name, shape=(1,), default_value=0.0) for name in feature_names]
    feature_spec = tf.feature_column.make_parse_example_spec(feature_columns)

    return  tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()

estimator.export_savedmodel(FLAGS.output_dir + '/export', serving_input_receiver_fn)
```

Does it make sense?

**Comment by ramakumar1729** [comment]
> Thanks for the quick reaction. I think I've figured it out (assuming this is executed in examples/tf_ranking_libsvm.py):
> 
> ```
> def serving_input_receiver_fn():
>     feature_names = ["{}".format(i + 1) for i in range(FLAGS.num_features)]
>     feature_columns = [tf.feature_column.numeric_column(
>           name, shape=(1,), default_value=0.0) for name in feature_names]
>     feature_spec = tf.feature_column.make_parse_example_spec(feature_columns)
> 
>     return  tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()
I'm not sure if the last brackets are needed. Rest of the code looks fine. 
> 
> estimator.export_savedmodel(FLAGS.output_dir + '/export', serving_input_receiver_fn)
> ```
> Does it make sense?

**Comment by eggie5** [comment]
I ran the export on my ranker: it only has 1 input, a sparse id and group size 1. 

I thought the output shape was interesting. I would do my scoring using the `predict` signature right? It has a (-1, -1) shape. What does this mean? 

```
$ saved_model_cli show --dir . --tag_set serve --signature_def predict
The given SavedModel SignatureDef contains the following input(s):
  inputs['examples'] tensor_info:
      dtype: DT_STRING
      shape: (-1)
      name: input_example_tensor:0
The given SavedModel SignatureDef contains the following output(s):
  outputs['output'] tensor_info:
      dtype: DT_FLOAT
      shape: (-1, -1)
      name: groupwise_dnn_v2/accumulate_scores/truediv:0
Method name is: tensorflow/serving/predict
```

**Comment by mayank953** [comment]
> Thanks for the quick reaction. I think I've figured it out (assuming this is executed in examples/tf_ranking_libsvm.py):
> 
> ```
> def serving_input_receiver_fn():
>     feature_names = ["{}".format(i + 1) for i in range(FLAGS.num_features)]
>     feature_columns = [tf.feature_column.numeric_column(
>           name, shape=(1,), default_value=0.0) for name in feature_names]
>     feature_spec = tf.feature_column.make_parse_example_spec(feature_columns)
> 
>     return  tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()
> 
> estimator.export_savedmodel(FLAGS.output_dir + '/export', serving_input_receiver_fn)
> ```
> 
> Does it make sense?

Hi @nzhiltsov, May I know a way through which I can load the saved model in python. I tested the model by saved_model_cli & this appears to be working. 
I have a saved model.pb file with variables folder which I want to use to make a prediction on multiple documents on a server & thus want to create a predict function which I am working on. Have you created any such function yet? 

Thanks

**Comment by nzhiltsov** [comment]
I'd recommend using TF-serving:
1) Run a TF server, preferably, using Docker (because you can switch easily between TF versions and CPU/GPU), e.g.:
_docker run --runtime=nvidia -p 8500:8500 --mount type=bind,source=/data/naics-similarity-ltr/results/prod-ndcg-loss/export/best_exporter,target=/models/ltr --mount type=bind,source=/home/ubuntu/batching.conf,target=/models/batching.conf -e MODEL_NAME=ltr -t tensorflow/serving:latest-gpu --batching_parameters_file=/models/batching.conf --enable_batching_

2) Access it via TF Serving gRPC API:
```
from tensorflow_serving.apis import predict_pb2
from grpc.beta import implementations
from tensorflow_serving.apis import prediction_service_pb2
from tensorflow.contrib.util import make_tensor_proto

def make_request(test_data):
    request = predict_pb2.PredictRequest()
    d = test_data.as_matrix()
    for i, c in enumerate(test_data.columns):
        request.inputs[c].CopyFrom(make_tensor_proto(d[:,i], dtype=tf.float32, shape=(test_data.shape[0],1)))
    request.model_spec.signature_name = 'predict'
    request.model_spec.name = 'ltr'
    return request

channel = implementations.insecure_channel(tf_serve_host, tf_serve_port)
stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
result = predict_stub.Predict(make_request(test_data), timeout_in_secs)
predictions = np.array(result.outputs['output'].float_val)
```

**Comment by mayank953** [comment]
> I'd recommend using TF-serving:
> 
> 1. Run a TF server, preferably, using Docker (because you can switch easily between TF versions and CPU/GPU), e.g.:
>    _docker run --runtime=nvidia -p 8500:8500 --mount type=bind,source=/data/naics-similarity-ltr/results/prod-ndcg-loss/export/best_exporter,target=/models/ltr --mount type=bind,source=/home/ubuntu/batching.conf,target=/models/batching.conf -e MODEL_NAME=ltr -t tensorflow/serving:latest-gpu --batching_parameters_file=/models/batching.conf --enable_batching_
> 2. Access it via TF Serving gRPC API:
> 
> ```
> from tensorflow_serving.apis import predict_pb2
> from grpc.beta import implementations
> from tensorflow_serving.apis import prediction_service_pb2
> from tensorflow.contrib.util import make_tensor_proto
> 
> def make_request(test_data):
>     request = predict_pb2.PredictRequest()
>     d = test_data.as_matrix()
>     for i, c in enumerate(test_data.columns):
>         request.inputs[c].CopyFrom(make_tensor_proto(d[:,i], dtype=tf.float32, shape=(test_data.shape[0],1)))
>     request.model_spec.signature_name = 'predict'
>     request.model_spec.name = 'ltr'
>     return request
> 
> channel = implementations.insecure_channel(tf_serve_host, tf_serve_port)
> stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
> result = predict_stub.Predict(make_request(test_data), timeout_in_secs)
> predictions = np.array(result.outputs['output'].float_val)
> ```

@nzhiltsov  Thanks a lot for the quick reply. 

So Meanwhile, I was actually working on a similar way by using docker to serve the tf-serving by following [link](https://medium.com/devseed/technical-walkthrough-packaging-ml-models-for-inference-with-tf-serving-2a50f73ce6f8). I was actually facing the issue to call my hosted image on the port as the input was not of the expected form. 

My input is of the form in LibSVM data

> 2 qid:1040 2:0.5443037974683544 3:0.625 4:84.56539398862714 5:1.7103 6:760 8:1 12:1
0 qid:1040 2:0.3333333333333333 4:50 5:1.9323 6:800 12:1
0 qid:1040 2:0.8584615384615385 3:0.9130434782608695 4:50 5:2.0581 6:999 10:1 12:1
0 qid:1040 2:0.6785714285714286 3:0.8 4:50 5:2.7594 6:823 12:1

where I'm passing it by removing qid & the first column i.e. relevance_flag. While using the serving function I was able to predict using 

```
> saved_model_cli run \
    --dir ./ \
    --tag_set serve \
    --signature_def predict \
    --input_examples 'examples=[{"2":[0.5348837209302325],"3":[0.75],"4":[33.68298368298368],"5":[14.4054],"6":[1707.0],"8":[1.0],"11":[1.0],"14":[1.0],"15":[1.0]},{"2":[0.3409090909090909],"4":[50.0],"5":[0.8047000000000001],"6":[833.0],"12":[1.0]}]'
```
But I'm getting the error when passing in the same format in testing the output using curl GET for the hosted docker image. 

In your given solution,I haven't used batching & does not have batching.conf file, how can I use it without having that? Further, should we pass test_data in LibSVM format as given in examples/data/text.txt as it was showing error 

`ValueError: could not convert string to float: '1 qid:0 2:0.6842105263157895 4:29.1951604418727 5:1.4356 6:1346 8:1 11:1 14:1 15:1'
`
Also, I think it should be "stub.Predict" in result instead of "predict_stub.Predict" in result. 

Request you to kindly help me through it.
Thanks

**Comment by mayank953** [comment]
@nzhiltsov 
So I was able to host my model using tf-serving & Docker. 
`
docker run -p 8500:8500 --mount type=bind,source=/tmp/tfserving/serving/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu,target=/models/half_plus_two -e MODEL_NAME=half_plus_two -t TensorFlow/serving &
`
I have changed the name based on tutorial so that can be ignored. I have saved the model using the serving_input_receiver_fn only. Now When hosted I was not able to predict as it was showing the error in test_data format I guess.  
I got the tf_serve_host by docker inspect <container id> | grep "IPAddress" & tf_serve_port as 8500 for gRPC.
I have shared my data format in the above post. Request you to kindly guide me that how could I pass that to make the predictions as I was able to do with saved_model_cli.

**Comment by mayank953** [comment]
@nzhiltsov Request you to kindly help me with the test_data format, I have still not been able to run the code solution provided by you.

**Comment by mayank953** [comment]
@ramakumar1729  In continuation of our discussion on #101 Can you suggest how can I call the function using the client-server style mechanism as suggested by @nzhiltsov, I have been able to hit the hosted model image but still gets an error & am unable to call gprc. 
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 562, in __call__
    return _end_unary_response_blocking(state, call, False, None)
  File "/usr/local/lib/python3.5/dist-packages/grpc/_channel.py", line 466, in _end_unary_response_blocking
    raise _Rendezvous(state, None, None, deadline)
grpc._channel._Rendezvous: <_Rendezvous of RPC that terminated with:
        status = StatusCode.INVALID_ARGUMENT
        details = "input tensor alias not found in signature: A. Inputs expected to be in the set {examples}."
        debug_error_string = "{"created":"@1566287030.631272582","description":"Error received from peer ipv4:172.17.0.2:8500","file":"src/core/lib/surface/call.cc","file_line":1041,"grpc_message":"input tensor alias not found in signature: A. Inputs expected to be in the set {examples}.","grpc_status":3}"
```

I think it has to do with serialized tf.Example but I'm not able to still figure out my test_data format. My input data is in libSVM format as you can see above & I'm not using tf_ranking_libsvm.ipynb without sparse-features. I have tried passing the test_data as suggested in https://github.com/tensorflow/ranking/issues/101#issuecomment-522699676 but still no luck. Further, I have generated the saved_model with serving function by a method provided above. 

> Thanks for the quick reaction. I think I've figured it out (assuming this is executed in examples/tf_ranking_libsvm.py):
> 
> ```
> def serving_input_receiver_fn():
>     feature_names = ["{}".format(i + 1) for i in range(FLAGS.num_features)]
>     feature_columns = [tf.feature_column.numeric_column(
>           name, shape=(1,), default_value=0.0) for name in feature_names]
>     feature_spec = tf.feature_column.make_parse_example_spec(feature_columns)
> 
>     return  tf.estimator.export.build_parsing_serving_input_receiver_fn(feature_spec)()
> 
> estimator.export_savedmodel(FLAGS.output_dir + '/export', serving_input_receiver_fn)
> ```
> 
> Does it make sense?

Actually, I am writing a tutorial too on how to use tf-Ranking for production or in large scale & thus require to host it & call it correctly. 
Thanks.

**Comment by ramakumar1729** [comment]
Can you share the client code, and how you invoke the server?

**Comment by mayank953** [comment]
So I initially used tf-serving with docker. 
``` docker run -p 8500:8500 --mount type=bind,source=/tmp/tfserving/serving/tensorflow_serving/servables/tensorflow/testdata/saved_model_half_plus_two_cpu,target=/models/half_plus_two -e MODEL_NAME=half_plus_two -t tensorflow/serving & ```

I replaced the saved_model.pbi & checkpoints file in the half_plus_two model with that produced by tfr export_savedmodel. The name won't make any difference though. The model was thus hosted using docker. 

Now for client side code is as follows:- 
``` 
import pandas as pd
from tensorflow_serving.apis import predict_pb2
from grpc.beta import implementations
from tensorflow_serving.apis import prediction_service_pb2
from tensorflow.contrib.util import make_tensor_proto
import tensorflow as tf

def make_request(test_data):
    request = predict_pb2.PredictRequest()
    d = test_data.as_matrix()
    for i, c in enumerate(test_data.columns):
        request.inputs[c].CopyFrom(make_tensor_proto(d[:,i], dtype=tf.float32, shape=(test_data.shape[0],1)))
    request.model_spec.signature_name = 'predict'
    request.model_spec.name = 'half_plus_two'
    return request

tf_serve_host ="172.17.0.2"    # obtained from docker inspect <container id> | grep "IPAddress"
tf_serve_port = 8500     # port for grpc
timeout_in_secs = 100    #timeout for calling prediction

channel = implementations.insecure_channel(tf_serve_host, tf_serve_port)
stub = prediction_service_pb2.beta_create_PredictionService_stub(channel)
result = stub.Predict(make_request(test_data), timeout_in_secs)
predictions = np.array(result.outputs['output'].float_val)
```
I get the error as mentioned above in the result line. My test data is of the form ;
``` 
0 qid:0 2:0.6153846153846154 3:1 4:37.63664757938574 5:7.2545 6:2396 8:1 11:1 14:1 15:1
0 qid:0 2:0.4347826086956522 3:1 4:59.08433734939759 5:8.735799999999999 6:1698 8:1 11:1 14:1 15:1
0 qid:0 2:0.5348837209302325 3:0.75 4:33.68298368298368 5:14.4054 6:1707 8:1 11:1 14:1 15:1
1 qid:1 2:0.8424242424242424 3:0.3846153846153846 4:61.46730462519936 5:2.9413 6:1208 8:1 10:1 12:1
0 qid:1 2:0.8584615384615385 3:0.9130434782608695 4:50 5:1.3062 6:999 12:1
```
I need to get prediction on these data. I was able to get the same by using saved_model_cli as I discussed above.
Thanks

**Comment by biggestT** [comment]
@mayank953 I struggled a bit with this as well I found it helpful to check the saved model's `signature_def` like this:
```
saved_model_cli show --dir [dir with exported model] --all
```
In my case (based on  `examples/tf_ranking_libsvm.py`) the serving model had an input named `examples` with dtype string. It also says in the example code comments:
>      # We expect tf.Example as input during serving.
I found [this post](https://towardsdatascience.com/working-with-tfrecords-and-tf-train-example-36d111b3ff4d) helpful to understand how to feed a list of serialized Examples via the protobuf setup. My code looks like this now:
```python
def _float_feature(value):
    return tf.train.Feature(float_list=tf.train.FloatList(value=[value]))

def create_example(data):
    feature = { f'{i}': _float_feature(data[i]) for i in range(0, FLAGS.num_features) }
    example_proto = tf.train.Example(features=tf.train.Features(feature=feature))
    return example_proto

def make_request(x):
    request = predict_pb2.PredictRequest()
    example_protos = []
    for row in x:
        example_proto = create_example(row).SerializeToString()
        example_protos.append(example_proto)
    proto = make_tensor_proto(example_protos, dtype=tf.string)
    request.inputs['examples'].CopyFrom(proto)
    request.model_spec.signature_name = 'predict'
    request.model_spec.name = 'rank'
    return request
```

Pretty new to this so not sure if it is correct but at least it's able to make some kind of predictions now :)

**Comment by ramakumar1729** [comment]
@biggestT : Thanks for sharing a minimal working example, this looks like the right direction. @mayank953 : Can you see if this works for you?

**Comment by mayank953** [comment]
@biggestT The code is showing error in 

> feature = { f'{i}': _float_feature(data[i]) for i in range(0, FLAGS.num_features) }

Further, can you also mkae it clear on how my data x /test_data should be if my test/train data is of the form of LibSVM data with label & qid;
```
0 qid:0 2:0.6153846153846154 3:1 4:37.63664757938574 5:7.2545 6:2396 8:1 11:1 14:1 15:1
0 qid:0 2:0.4347826086956522 3:1 4:59.08433734939759 5:8.735799999999999 6:1698 8:1 11:1 14:1 15:1
0 qid:0 2:0.5348837209302325 3:0.75 4:33.68298368298368 5:14.4054 6:1707 8:1 11:1 14:1 15:1
1 qid:1 2:0.8424242424242424 3:0.3846153846153846 4:61.46730462519936 5:2.9413 6:1208 8:1 10:1 12:1
0 qid:1 2:0.8584615384615385 3:0.9130434782608695 4:50 5:1.3062 6:999 12:1
```
While using ranker.predict I used to read the libSVM using pd.read_csv. Should I do the same with case of the tf-serving in this method while calling 
> result = stub.Predict(make_request(test_data), timeout_in_secs) 

Thanks.

**Comment by biggestT** [comment]
@mayank953 sorry not sure what error you are getting but sorry `x`/`test_data` is a numpy array with shape `[num_samples, num_features]` so it won't work if you're passing a Pandas DataFrame. Perhaps you can just pass it `[your_dataframe].values`. Btw I used SciKitLearn for writing to LibSVM files perhaps you can use e.g https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_svmlight_file.html if `pd.read_csv` doesn't work.

**Comment by mayank953** [comment]
@biggestT  The error is the basic syntax error in python. I'm also not sure why this is coming. It's majorly in f'{i}' i guess. I am also debugging it.

> SyntaxError: invalid syntax

Yeah, I will be checking with numpy too although I don't think that will be an issue. Further, I will also try the ScikitLearn for writing LibSVM once. 
Meanwhile, Can you please help me with the error. 

Thanks a lot.

**Comment by biggestT** [comment]
@mayank953 you can email me at adress in my profile here https://github.com/biggestT

**Comment by ramakumar1729** [comment]
Closing this for now. Please open a new issue with more specific details as several issues are being mixed up here and that can be confusing.
