### ISSUE TITLE
How to use tensorflow ranking for prediction ?

### ISSUE THREAD

**Issue by vertika-19** [tensorflow/ranking#48]
As per my understanding from sample dataset, libsvm generator is assuming that relevance level will be present. 
 
I am using sample 
Can you suggest what changes to make so that I can use my trained model later for prediction of relevance levels/ranking based on features and document list for a query.

**Comment by eggie5** [comment]
This package uses the Tensorflow Estimators API, so accordingly your mode has a `predict` function. You can use this to rank documents in a query:

```
for x in ranker.predict(input_fn=lambda: input_fn_eval(test_path)):
    print(x)
```

**Comment by tomleung1996** [comment]
> This package uses the Tensorflow Estimators API, so accordingly your mode has a `predict` function. You can use this to rank documents in a query:
> 
> ```
> for x in ranker.predict(input_fn=lambda: input_fn_eval(test_path)):
>     print(x)
> ```

For each iteration, it outputs a (100,) array for a single query, do you know how to interpret this result? Thanks!

**Comment by sbruch** [comment]
Vertika - Apologies for the delayed response. Alex is correct; you will need to invoke the learned model in predict mode to obtain per-document score. You may then sort documents by their score to obtain a ranked list.

Tom - generally speaking, the per-query output is a Tensor of relevance scores where the i^{th} score corresponds to the i^{th} document in the input Tensor. Note that during training, the dimension of the input Tensor that corresponds to the number of documents per query is fixed to "list-size" (in your case, it appears to be 100). If there are fewer than list-size documents available for your a query, its Tensor is padded.

Please let us know if you have additional questions.
