### ISSUE TITLE
GSOC project proposal

### ISSUE THREAD

**Issue by Tahsin-Mayeesha** [tensorflow/ranking#49]
Hi, 

Tensorflow is participating in GSOC(Google Summer of Code) this year and the students were told they can make their own project proposals based on issues that has "contributions welcome" label. Based on this issue opened by Paige Bailey I'm drafting my project proposal and I've picked up some learning-to-rank related concepts already. 

Would it be okay? I thought I should talk to the project owners before going ahead with the proposal. Please let me know if there's some important change or expectations around library migration.

https://github.com/tensorflow/tensorflow/issues/25445 

![image](https://user-images.githubusercontent.com/17886829/55487928-df958000-5650-11e9-9e81-efebc883fe2e.png)

**Comment by bendersky** [comment]
Tahsin, thank you for your interest in our package. Some of features in Paige's issue are currently being worked on by the team (see https://github.com/tensorflow/ranking/issues/32), so I am not sure if this would be the best choice for your GSOC proposal.

**Comment by Tahsin-Mayeesha** [comment]
I actually applied to other projects in tensorflow guide. I'll mark this issue as closed.
