### ISSUE TITLE
How to interpret the predict output?

### ISSUE THREAD

**Issue by tomleung1996** [tensorflow/ranking#50]
I'm new to learning to rank, and I need some help on understanding the model's output.
Using the sample code and data, for each iteration, it outputs a (100,) array for a single query, but how to interpret this result?

Does it indicate the relevance score of the first 100 "document" (order by document_id)? If so, how can I find the corresponding document in the dataset? (it seems we don't specify an document_id in the dataset)

Thanks!

**Comment by eggie5** [comment]
are you using the `predict` function? It will output the scores for each document in the query. You can then sort the documents by the score to get your ranking.

**Comment by tomleung1996** [comment]
> are you using the `predict` function? It will output the scores for each document in the query. You can then sort the documents by the score to get your ranking.

Yes, I am using the `predict` function. However, if my dataset has 10 lines of a single query ( a query-document features pair each line, do I get it right?) and my `_LIST_SIZE` is set to 5, the output will be (5,) array for each query, how do I find corresponding document for these 5 score? Or the `_LIST_SIZE` must be set to some given number?

**Comment by sjhermanek** [comment]
Follow-on to @eggie5 , what is the desired ordering? How to interpret the result of the arrays?

**Comment by eggie5** [comment]
Assuming a `group_size` of `1`, or point-wise scoring, the scoring function has a scalar output. This is the score for document in the query. To rank a query, you score all the documents and rank them in descending order; meaning the highest score is the most relevant.

**Comment by sjhermanek** [comment]
@eggie5  - thank you for your answer.

To confirm with you:
- I set `_LIST_SIZE=50` and `_BATCH_SIZE=32`, and I'm working on the `MQ2008` dataset 
- I have got a `ranker` to the iPython Notebook that's provided as an example. I then train the `ranker` and evaluate it.
- I then try to predict new data as such: 
`results = ranker.predict(input_fn=lambda: input_fn(_TEST_DATA_PATH_2))`
- I ran into two problems / challenges / lack of my understanding:
1. When I try to run below snippet, I will run into an infinite loop (presumably) and print without an end. There are definitely repetitions in there, but basically it'll print without an end:
`for x in ranker.predict(input_fn=lambda: input_fn(_TEST_DATA_PATH_2)): print(x)`
2. As you may know, the `MQ2008` dataset is formatted using standard LibSVM format, e.g.: `0 qid:18219 1:0.0001 feature_num:feature_value #docid=XYZ. 
- How would I go about preserving the docid? 
- Can I assume that all docs for `qid:18219` will be in order in the array of scalars?

Thank you so much for helping, @eggie5 , you're amazing!

**Comment by tomleung1996** [comment]
> @eggie5 - thank you for your answer.
> 
> To confirm with you:
> 
> * I set `_LIST_SIZE=50` and `_BATCH_SIZE=32`, and I'm working on the `MQ2008` dataset
> * I have got a `ranker` to the iPython Notebook that's provided as an example. I then train the `ranker` and evaluate it.
> * I then try to predict new data as such:
>   `results = ranker.predict(input_fn=lambda: input_fn(_TEST_DATA_PATH_2))`
> * I ran into two problems / challenges / lack of my understanding:
> 
> 1. When I try to run below snippet, I will run into an infinite loop (presumably) and print without an end. There are definitely repetitions in there, but basically it'll print without an end:
>    `for x in ranker.predict(input_fn=lambda: input_fn(_TEST_DATA_PATH_2)): print(x)`
> 2. As you may know, the `MQ2008` dataset is formatted using standard LibSVM format, e.g.: `0 qid:18219 1:0.0001 feature_num:feature_value #docid=XYZ.
> 
> * How would I go about preserving the docid?
> * Can I assume that all docs for `qid:18219` will be in order in the array of scalars?
> 
> Thank you so much for helping, @eggie5 , you're amazing!

You can write you own `input_fn` which has no `repeat()`, you can see there's a `repeat()` inside the example code for the training purpose.

**Comment by eggie5** [comment]
You are using the provided `input_fn` which has a `repeat` stage, so it will iterate infinitely. Trying setting `steps` to limit that or write another input function which only iterates the dataset once.

What do you mean preserve the doc_id? It's a comment, it should be ignored by the parser. Do you want to include it in your dataset generator?

The order of the docs in predict function follows the order of your input. It is not sorted. You must sort them on your own.

**Comment by sjhermanek** [comment]
Thank you, to both @eggie5  and @tomleung1996 , it makes total sense now :)
Can't believe I missed the `repeat` in the `input_fn`.

**Comment by bendersky** [comment]
@eggie5 Thanks for your help in answering these issues! The TF-Ranking team really appreciates your help! Closing this for now, as it seems to be resolved.
