### ISSUE TITLE
How do you calculate tf of query and Document in LETOR dataset?

### ISSUE THREAD

**Issue by Dinesh-Mali** [tensorflow/ranking#59]
Hi,
while calculating Term Frequency (TF) and Inverse Document Frequency(IDF) of a document in LETOR dataset you used,
1) How did you calculate tf-idf?  Suppose I have 100 tokens in a document then I will have 100 Tf's for all the tokens then are you using average TF for a document?
Is it like avg_tf = (tf1 + tf2 + ....+ tf100)/ (Total number of tokens in the document ..100 here)..? 
2) Also as per the definition of Tf..whether you are using only frequency of each term or dividing it by total number of tokens?
is it like tf(t,d) = number of times t occurs in document d...? Or
 tf(t,d) = number of times t occurs in document d/ total number of tokens in the document d
3) How tf of a query has calculated? Are you considered query text itself or with respect to all the documents related to the query?
4)  Same question for IDF as question 1.

**Comment by bendersky** [comment]
I think your question is regarding feature computation, which is not something that is inherently done by TF-Ranking. See this paper https://arxiv.org/ftp/arxiv/papers/1306/1306.2597.pdf for general descriptions of the features used in LETTOR collection.

In particular, it is useful to keep in mind that your training examples are <query,document> pairs. So for most of the features in the table in the paper I've cited above you should think of them.  as measuring the match between query and document. So, for example feature 1: 1 TF(Term frequency) of body, would be the count of the number of times that the query terms are occurring in the document body (and so on for other features).

Hope this helps!

**Comment by Dinesh-Mali** [comment]
Thanks bendersky!

**Comment by bendersky** [comment]
Closing this for now, as the main question seems to have been addressed.
