### ISSUE TITLE
Make export type configurable

### ISSUE THREAD

**Issue by ebernhardson** [tensorflow/ranking#6]
Currently when saving a trained estimator the default ranking head uses tf.estimator.export.RegressionOutput, but this limits the saved model to string inputs. The ranking head can be extended, but it might be more convenient for downstram users if this was a providable option. This would allow downstream users to choose how they will feed the models. In our system the models execute in the same process that calculates the features, making a serialization step undesirable.

**Comment by xuanhuiwang** [comment]
Thanks for the comments. This is a feature that we can consider to have. Meanwhile, there is some workaround by re-define the model_fn to override the export_outputs before feeding into tf.estimator.Estimator.

def redefined_model_fn(...):
  original_model_fn = tfr.model.make_groupwise_ranking_fn(...)
  estimator_spec = original_model_fn(...) # call the model_fn to return estimator_spec
  if mode == model_fn.ModeKeys.PREDICT:
        return model_fn.EstimatorSpec(
            mode=mode,
            predictions=estimator_spec.predictions,
            export_outputs={
                # your key: # your output object
            })
  return estimator_spec

**Comment by xuanhuiwang** [comment]
We will evaluate this and possibly include it in future version. Feel free to reopen if the above solution does not work.
