### ISSUE TITLE
[Feature Request] Metrics don't accept sparse inputs 

### ISSUE THREAD

**Issue by mkfilipiuk** [tensorflow/ranking#60]
Currently I'm developing a DNN for collaborative filtering. I'd like to validate my model using various metrics like NDCG but it doesn't support sparse tensors as input. Is there a chance that it would be implemented?

**Comment by xuanhuiwang** [comment]
You are right -- only dense Tensors are supported in metrics and losses. We don't have plan to support sparse Tensors for them.

Can you share why SparseTensors are needed in you use case?

**Comment by mkfilipiuk** [comment]
I have a sparse matrix with around 0.5% nonzero values and casting to dense just to compute the NDCG wouldn't make any sense in terms of performance (which is of course crucial for my project). At the moment, I'm forced to get a huge dense output matrix (only expected values are in sparse matrix) back to CPU and calculate NDCG using scipy and numpy.

**Comment by xuanhuiwang** [comment]
Are you using the metrics outside of the training or during the training?

What is the maximum list size to compute NDCG? How many queries are in your sparse matrix? Can you use mini-batches and accumulate the NDCG over multiple batches?

**Comment by mkfilipiuk** [comment]
I'm evaluating my model after each epoch. I have 10 000 users and over 20 000 items in matrix

I could use mini-batches, but it would affect the performance.

I've managed to implement somehow NDCG on sparse on GPU by myself, but due to lack of proper sparse matrix operations kernels (I'd like to do tf.minimum and then tf.reduce_sum) I'm forced to cast matrix to dense.

**Comment by xuanhuiwang** [comment]
I am closing this now. We will follow up with providing more examples for different use cases in the future.
