### ISSUE TITLE
How to predict ?

### ISSUE THREAD

**Issue by zxyscz** [tensorflow/ranking#65]
now，i train a model，but i dont know how to predict a sample?

**Comment by Dinesh-Mali** [comment]
use ranker.predict()  for prediction, with your inference data set.

**Comment by xuanhuiwang** [comment]
Hi, 

Can you be more specific about what are the errors in tf-serving? Also, it will be helpful if you can share more about your config such as group_size, feature columns, etc.

**Comment by xuanhuiwang** [comment]
Can you see whether this issue helps: https://github.com/tensorflow/ranking/issues/68

**Comment by bendersky** [comment]
Closing this for now. Please let us know if you still have any issues.
