### ISSUE TITLE
How to compute scores for multiple queries?

### ISSUE THREAD

**Issue by Dinesh-Mali** [tensorflow/ranking#71]
Hi,

During prediction using ranker.predict() I am passing inference data which contains two queries and  20 documents for each so there is 40 query-doc pairs in libsvm format.

When I analysed my scores I am getting an array for 20 scores only but it should give me 40 scores corresponding for each (query - 20_doc pair). Does it takes only single query for inference or can support multiple queries. Please clear this doubt?

If it supports multiple queries then should we pass all the queries at once or individually for inference or prediction?
Thank you!

**Comment by prakhar2811** [comment]
@Dinesh-Mali ranker.predict() outputs a generator object. how to print the or save the predictions in an array?

**Comment by Dinesh-Mali** [comment]
Hi Prakhar,

You should give input to the predict function in libsvm format only.
What I have followed to save predictions score in array is as follows:

result = ranker.predict(input_fn = lambda:input_fn_prediction('path_to_inference_data') )
scores = [score for score in result]...scores contains other information as well

when you want only numeric values then again iterate the scores 
score_val = [score for score in scores[0]]
Hope this helps!

**Comment by prakhar2811** [comment]
Thanks for reventing back @Dinesh-Mali. I still have an issue. 
The line ranker.predict(input_fn = lambda:input_fn_prediction('path_to_inference_data') ) throws an error saying "name 'input_fn_prediction' is not defined".

**Comment by Dinesh-Mali** [comment]
This is how I named my input function for prediction.
Please your function for the same.

**Comment by prakhar2811** [comment]
Is it possible for you to share your input function? It would be quite helpful. 
Thanks in advanced!
