### ISSUE TITLE
Train end to end 

### ISSUE THREAD

**Issue by vdv1g16** [tensorflow/ranking#74]
Is that possible to train end to end with tf ranking and is there any document that describes how to train end - to -end with tf ranking?
Thank you

**Comment by ramakumar1729** [comment]
Hi, 

Can you give more details on what you mean by end-to-end? What are your input features and target labels?

**Comment by prakhar2811** [comment]
@ramakumar1729  i've already implemented LetoR on my query data and obtained an increment in the NDCG value for the test data. But i'm unable to obtain prediction on the test data (libsvm format). Could you please help me out with creating the input_fn_predict() function for ranker.predict()?

**Comment by bendersky** [comment]
Does #78  addresses your question?
