### ISSUE TITLE
'import tensorflow_ranking as tfr' error

### ISSUE THREAD

**Issue by currylym** [tensorflow/ranking#76]
```
>>> import tensorflow_ranking as tfr
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/luyiming/anaconda3/envs/deep/lib/python3.6/site-packages/tensorflow_ranking/__init__.py", line 20, in <module>
    from tensorflow_ranking.python import *  # pylint: disable=wildcard-import
  File "/home/luyiming/anaconda3/envs/deep/lib/python3.6/site-packages/tensorflow_ranking/python/__init__.py", line 23, in <module>
    from tensorflow_ranking.python import head
  File "/home/luyiming/anaconda3/envs/deep/lib/python3.6/site-packages/tensorflow_ranking/python/head.py", line 30, in <module>
    _DEFAULT_SERVING_KEY = tf.saved_model.DEFAULT_SERVING_SIGNATURE_DEF_KEY
AttributeError: module 'tensorflow._api.v1.saved_model' has no attribute 'DEFAULT_SERVING_SIGNATURE_DEF_KEY'
```

**Comment by ramakumar1729** [comment]
Can you share the commands you ran to replicate this error?

What is the version of tensorflow you are using?

**Comment by mathemakitten** [comment]
For the record, I've had this exact same issue on multiple machines, with both `tensorflow==1.12.0` (local on Mac OSX, no GPU) and `tensorflow==1.12.1` (server-side, no GPU). However, it did work on a different Linux server with `tensorflow-gpu==1.13.1`. This happens when running `import tensorflow_ranking` in a Python shell.

**Comment by fangkuann** [comment]
> For the record, I've had this exact same issue on multiple machines, with both `tensorflow==1.12.0` (local on Mac OSX, no GPU) and `tensorflow==1.12.1` (server-side, no GPU). However, it did work on a different Linux server with `tensorflow-gpu==1.13.1`. This happens when running `import tensorflow_ranking` in a Python shell.

I also met this problem, then configs below worked for me 
```
tensorflow-estimator               1.10.12
tensorflow-gpu                     1.12.0
tensorflow-ranking                 0.1.2
```

**Comment by bendersky** [comment]
Thanks for the update @fangkuann ! @ramakumar1729 -- we should probably update our documentation to specify the verified configurations for TF-Ranking to work correctly.
