### ISSUE TITLE
Prediction Issue (Conflicting results between estimator.predict v.s. using predictor from saved model)

### ISSUE THREAD

**Issue by Xilun-Chen** [tensorflow/ranking#77]
Thanks the authors for providing the tf_ranking_libsvm.py example, it is very helpful.

However, I encounter some inference/prediction issue, I'm not sure if I have done things correctly.

Currently I tried 2 ways of prediction.

- Using `estimator.predict(input_fn=test_input_fn, hooks=[test_hook])` right after all training is done,  which created a generator object and use loop to iterate through results.  This methods only worked without make_transform_fn(), if transform_fn is given, then error will be thrown out (using test data comes in repo, lisze_size = 100)

> ValueError: Cannot reshape a tensor with 900 elements to shape [9,1] (9 elements) for 'transform/encoding_layer/1/Reshape' (op: 'Reshape') with input shapes: [9,100,1], [2] and with input tensors computed as partial shapes: input[1] = [9,1].

I guess the reason is that transform_fn creates a tensor of shape(100, 1) for each query, and then in the test data, there are 9 queries, so the total element in that generator becomes 900, but however, it tries to reshape to have each query only a single score. If we do not give transform_fn, then we can iterate the generator and each line of results have 100 numbers there. There is some kind of mismatch somewhere...

- Also, I tried to export model and restored in a different tf session
```
tf.saved_model.loader.load(sess, [tf.saved_model.tag_constants.SERVING], exported_path)
predictor = tf.contrib.predictor.from_saved_model(exported_path)

model_input = tf.train.Example(features=tf.train.Features(feature=feature_dict))
model_input = model_input.SerializeToString()
output_score = predictor({"inputs": [model_input]})
```

However, it is giving me completely different scores as directly doing estimator.predict()

So, I'm not sure about the inference process now. If anyone can help me on this, I would really appreciate it :)

Thanks

**Comment by xuanhuiwang** [comment]
@Xilun-Chen, for estimator.predict, you need to feed the instance 1 by 1 I think. In #69, they used a lambda function. Can you take a look?

For the saved_model prediction, I didn't see anything suspicious in your code. Can you make sure that your feature_dict uses the right feature name as you defined in example_feature_columns()?

**Comment by Xilun-Chen** [comment]
@xuanhuiwang Thanks for the reply!

Yes, I'm basically using the same input_function
```
features_test, labels_test = load_data(FLAGS.test_path, FLAGS.list_size)
test_input_fn, test_hook = get_eval_inputs(features_test, labels_test)
```
and this function is then passed to estimator.predict()

```
feature_dict = dict()
for index in range(45):
    feature_dict[str(index)] = tf.train.Feature(float_list=tf.train.FloatList(value=[float(row[index])]))
```
This is how I feed the features, and then pass it to the predictor, output_dict contains a single score for each query-doc pair.

```
model_input = tf.train.Example(features=tf.train.Features(feature=feature_dict))
model_input = model_input.SerializeToString()
output_dict = predictor({"inputs": [model_input]})
```

Do I make a mistake on the feature_dict part?

Thanks!

**Comment by xuanhuiwang** [comment]
This looks weird. I would say that the one using tf.train.Example is more trustable to me given that it has a single example. 

The other one that uses load_data may introduce some randomness since you may have multiple examples and multiple queries. The order of the examples in a query may be changed when loading the data. This is only my guess...

**Comment by xuanhuiwang** [comment]
@Xilun-Chen do you have some similar issue as https://github.com/tensorflow/ranking/issues/78?

**Comment by bendersky** [comment]
Closing this for now, as this seems to be similar to #78
