### ISSUE TITLE
an example with embeddings?

### ISSUE THREAD

**Issue by ypopkov** [tensorflow/ranking#79]
Any chance someone could add an example where a mixture of embedded and non-embedded features are used for ranking? (where the embeddings for high cardinality features are estimated as a part of the model training - a very common use case in personalization)

Thanks!

**Comment by eggie5** [comment]
Here is an example: https://colab.research.google.com/github/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb
