### ISSUE TITLE
Using TF-Ranking with Sparse features

### ISSUE THREAD

**Issue by mulangonando** [tensorflow/ranking#82]
How Can I use TF ranking with sparse representation

**Comment by ramakumar1729** [comment]
This interactive [demo](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/handling_sparse_features.ipynb) is designed for using TF-Ranking with sparse features. Please take a look. 

Closing this for now, please reopen if you face any issues.

**Comment by mulangonando** [comment]
Hi 
So am coming back to this task. I see the Example in Example representation.
My questions are:
1. How do I represent the question ID in the tfrecords format e.g I have two queries as follows in LibSVM;
   9   qid:1   3:1   1:7   6:14
   6   qid:1  10:17   1:2   5:7   8:11
   0   qid:1   3:10   12:17  
   9   qid:2   7:2   
   7   qid:2   8:6   12:1   3:14
   etc (I have added extra spaces for clarity)
In lib SVM the qid stays here so the algotithm can tell the list size and actually tell which examples are being compared to against ecah other.

How do we represent this QID in the tfrecords format (For classification it's quite straight forward since we don't need a list to rank)  ----- OR should I be giving this in the Context? i.e. the question as the context?

2. Does tf ranking take an array as a value?
