### ISSUE TITLE
Problem with array_ops.squeeze(weights)

### ISSUE THREAD

**Issue by robertosolargallardo** [tensorflow/ranking#84]
I was testing your library and I have some problems. I tested with 1 sample (top-32) for training and 1 sample (top-32) for validation and the library fails (ValueError: Shapes () and (1,) are incompatible). I tracked the error (line 1193 in https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/losses.py) and my question is: Why do you use squeeze instead of reshape?
(I'm not a tensorflow expert)
Best regards, 
Roberto

**Comment by ramakumar1729** [comment]
This question might be more appropriate on Tensorflow issues.

You can write an equivalent for squeeze visa reshape. Note that there might be performance considerations, as both tf.squeeze and tf.reshape are backed by C++ ops.

**Comment by bendersky** [comment]
Closing this for now. @robertosolargallardo please let us know if you have any further issues.
