### ISSUE TITLE
How to serve the model using tf.serving & containerize it using docker ?

### ISSUE THREAD

**Issue by mayank953** [tensorflow/ranking#86]
Thanks a lot for providing the library. I was able to train & predict on my dataset of choice. I was working with @prakhar2811 we are trying to serve the TensorFlow model so that we can make a container through docker. #53 & #46  do provide an idea but still, I was not able to implement the same. Can someone please help/guide me with this?

**Comment by mayank953** [comment]
@xuanhuiwang  Can you please how can one build a serving function. I see various function defined in data.py in python folder but am unable to get how to use them.
Thanks

**Comment by xuanhuiwang** [comment]
@mayank953 what is your input format? I am not familiar with docker serving.

If it is tf.Example, we have example here: https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/examples/tf_ranking_libsvm.py#L227.

**Comment by mayank953** [comment]
Hi, 
So I'm using data in the libsvm format as kept in examples/data. The data must be getting converted further to tf.records/tf.example I guess? 
Does this serving function take multiple queries or only expect a single query data in input format?

**Comment by ramakumar1729** [comment]
Closing this for now. Please feel free to open a specific issue if needed.
