### ISSUE TITLE
how can I put both context and example feature in the LIBSVM  file

### ISSUE THREAD

**Issue by DeepColin** [tensorflow/ranking#88]
@ramakumar1729

**Comment by DeepColin** [comment]
can you offer more example to make it more practical for usage

**Comment by ramakumar1729** [comment]
For LIBSVM format, each line corresponds to a features for a query-document pair. This means that context features are replicated as an example feature (for each example).

I would suggest using Example in Example (EIE) format. This [demo](git.io/tf-ranking-demo) shows how to create data in EIE format.

**Comment by bendersky** [comment]
Closing for now. Feel free to open a separate issue if there are any specific questions after you ran through the demo that @ramakumar1729 pointed out.
