### ISSUE TITLE
tensorflow_ranking evaluation metrics in tensorboard

### ISSUE THREAD

**Issue by working-estimate** [tensorflow/ranking#93]
In the libsvm example code, the metrics used are only available when evaluation completes. And the metrics themselves are generated as functions, so they cannot be added to tensorboard as summaries. Is there a way to visualize metrics (like ndcg) in tensorboard while evaluation is in the process of running? When there are many samples to evaluate, not having any progress on what the metrics are looking like is frustrating.

**Comment by eggie5** [comment]
I don't see this behavior. When I run the code, tensorboard updates every 100 training steps....

**Comment by working-estimate** [comment]
> I don't see this behavior. When I run the code, tensorboard updates every 100 training steps....

I clearly mention that I am talking about evaluation metrics, not training.

**Comment by eggie5** [comment]
Sorry, I misunderstood your question. Yes, I had that concern too. I like to run my val-set evaluation after every epoch of the train-set. To do this I had to modify my training loop like this:

```
#initial eval
ranker.evaluate(input_fn=lambda: input_fn_val(name="val")

for epoch in range(EPOCHS):
    ranker.train(input_fn=lambda: input_fn_train(name="train)
    ranker.evaluate(input_fn=lambda: input_fn_val(name="val")

#final eval
ranker.evaluate(input_fn=lambda: input_fn_textl(name="test")
```
Note: The train loop above requires you modify the `input_fn`'s to run for 1 epoch.

Alternatively you can use `tf.estimator.train_and_evaluate` which has some good patterns around this same idea.

**Comment by working-estimate** [comment]
That approach would work with regular tensorflow metrics, but the [tensorflow_ranking's builtin metrics ](https://github.com/tensorflow/ranking/blob/master/tensorflow_ranking/python/metrics.py)do not post to tensorboard.

**Comment by eggie5** [comment]
They do work for me, as I use the OPA & MRR metrics from TFR and they post to tensor board after each epoch.

**Comment by bendersky** [comment]
Thanks for answering this issue, @eggie5! @working-estimate I am closing this for now, since we can't recreate this behavior. Please let us know if you still have any specific issues.
