### ISSUE TITLE
ANTIQUE tokenization technique 

### ISSUE THREAD

**Issue by eggie5** [tensorflow/ranking#95]
In the new "Tutorial: TF-Ranking for sparse features" notebook an interesting QA dataset, ANTIQUE, is introduced. I was inspecting the proto TFRecords and saw an interesting tokenization routine was used. For example, consider an original query from the dataset and the tokenized version:

Original: `why do human beeing hv to belive in god ?`
Tokenized: `['why' 'do' 'human' 'bee' '##ing' 'h' '##v' 'to' 'bel' '##ive' 'in' 'god' '?']`

`#` characters are inserted, words are split, etc. What is this technique called?

**Comment by rbrackney** [comment]
I suspect this is WordPiece tokenization, similar to how they did it in BERT. https://arxiv.org/pdf/1810.04805.pdf

I think your question points to a larger need: example code of how the raw ANTIQUE dataset was converted to TFrecords in the first place.

**Comment by eggie5** [comment]
@rbrackney thanks for the lead on WordPiece!

They do provide descriptions in the ANTIQUE notebook on how to create `tf.Example`s however, not how to create an EIE. If anyone is wondering, EIE (Example in Example) is an `Example` with two features called `serialized_context` and `serialized_examples`. 

I and now working on an example that writes `EIE` `tfrecord`s Spark.

**Comment by rbrackney** [comment]
@eggie5 I'd love to see your EIE example if you post it anywhere.

**Comment by rbrackney** [comment]
@eggie5 : I did a little more digging. It looks like the the ANTIQUE tf records are in fact using BERT encodings. Below an example of (abridged) deserialized document features straight from the .tfrecords. It's a bit concerning that there's such a big deviation from what the example notebook says the records look like, and how they are actually represented. 

features {
  feature {
    key: "document"
    value {
      bytes_list {
        value: "Pit bulls are a lot of things - loyal, friendly, active - but they\'re not naturally aggressive toward people. Since they were bred to fight other animals, it was important that they not snap at their human handlers. You\'ve fallen for a common myth."
      }
    }
  }
  feature {
    key: "document_bert_encoder_outputs"
    value {
      float_list {
        value: -0.8004763722419739
        value: -0.8821240067481995
        ..
        value: 0.8017302751541138
        value: -0.5942857265472412
      }
    }
  }
  feature {
    key: "document_id"
    value {
      bytes_list {
        value: "3971195_0"
      }
    }
  }
  feature {
    key: "document_input_ids"
    value {
      int64_list {
        value: 101
        value: 6770
        ..
        value: 0
        value: 0
      }
    }
  }
  feature {
    key: "document_input_mask"
    value {
      int64_list {
        value: 1
        value: 1
        ..
        value: 0
        value: 0
      }
    }
  }
  feature {
    key: "document_segment_ids"
    value {
      int64_list {
        value: 0
        value: 0
        ..
        value: 0
        value: 0
      }
    }
  }
  feature {
    key: "document_tokens"
    value {
      bytes_list {
        value: "pit"
        value: "bulls"
        ..
        value: "myth"
        value: "."
      }
    }
  }
  feature {
    key: "relevance"
    value {
      int64_list {
        value: 2
      }
    }
  }
}

**Comment by eggie5** [comment]
@rbrackney I don't think there is any discrepancy here. As you can see one of the features from your proto above is `document_tokens` and this is the same feature that the `categorical_column_with_vocabulary_file` function looks for in the ANTIQUE notebook.

Maybe the confusion comes from the fact that you have to deserialize the `EIE` twice to get what you pasted above. The first deserialization gives you two features: `serialized_context` and `serialized_examples` which are both serialized proto `Example`s. The output you posted above look like they are from deserializing the `serialized_examples` right?

**Comment by eggie5** [comment]
Also, here's some code to create `EIE` for python:

```
import tensorflow as tf

#helpers
def _bytes_feature(values):
    """Returns a bytes_list from a string / byte."""
    return tf.train.Feature(bytes_list=tf.train.BytesList(value=values))

def _int64_feature(values):
    """Returns an int64_list from a bool / enum / int / uint."""
    return tf.train.Feature(int64_list=tf.train.Int64List(value=values))

def make_eie(context:dict, examples:dict) -> str:
    """make example-in-example proto for TFR"""
    context_feature = {
      'qid': tf.train.Feature(bytes_list=tf.train.BytesList(value=[context["qid"].encode('ascii')])),
      'uid': tf.train.Feature(bytes_list=tf.train.BytesList(value=[context["uid"].encode('ascii')])),
    }
    context_proto = tf.train.Example(features=tf.train.Features(feature=context_feature))
    serialized_context = context_proto.SerializeToString()
    
    serialized_examples=[]
    for example in examples:
        example_feature = {
          'rid': tf.train.Feature(int64_list=tf.train.Int64List(value=[example["rid"]])),
          'rel': tf.train.Feature(int64_list=tf.train.Int64List(value=[example["rel"]])),
        }

        example_proto = tf.train.Example(features=tf.train.Features(feature=example_feature))
        serialized_example = example_proto.SerializeToString()
        serialized_examples.append(serialized_example)
        
        
    #put context and examples in container
    eie_features={
        "serialized_context": tf.train.Feature(bytes_list=tf.train.BytesList(value=[serialized_context])),
        "serialized_examples": tf.train.Feature(bytes_list=tf.train.BytesList(value=serialized_examples)),
    }
    
    eie_proto = tf.train.Example(features=tf.train.Features(feature=eie_features))
    return eie_proto
    
context = {"qid": "asdf", "uid": "fdsa"}
examples = [{"rid": 1, "rel": 1}]
eie = make_eie(context, examples)
print(eie)
print(eie.SerializeToString())

```
features {
  feature {
    key: "serialized_context"
    value {
      bytes_list {
        value: "\n\"\n\017\n\003qid\022\010\n\006\n\004asdf\n\017\n\003uid\022\010\n\006\n\004fdsa"
      }
    }
  }
  feature {
    key: "serialized_examples"
    value {
      bytes_list {
        value: "\n\034\n\014\n\003rid\022\005\032\003\n\001\001\n\014\n\003rel\022\005\032\003\n\001\001"
      }
    }
  }
}

b'\n{\n>\n\x12serialized_context\x12(\n&\n$\n"\n\x0f\n\x03qid\x12\x08\n\x06\n\x04asdf\n\x0f\n\x03uid\x12\x08\n\x06\n\x04fdsa\n9\n\x13serialized_examples\x12"\n \n\x1e\n\x1c\n\x0c\n\x03rid\x12\x05\x1a\x03\n\x01\x01\n\x0c\n\x03rel\x12\x05\x1a\x03\n\x01\x01'

```

**Comment by rbrackney** [comment]
@eggie5 you're right, the tokenization at the end is the right format. My mistake. Thanks for the code!

**Comment by ramakumar1729** [comment]
As @rbrackney rightly pointed out, the data in the tutorial uses BERT's tokenizer to create word pieces. 

Here is how you can create and store TFRecords in EIE format:

```
def _example_in_example(context, examples):
  """Returns an Example in Example."""
  example_in_example = tf.train.Example()
  example_in_example.features.feature[
      "serialized_context"].bytes_list.value.append(context.SerializeToString())
  for ex in examples:
    example_in_example.features.feature[
        "serialized_examples"].bytes_list.value.append(ex.SerializeToString())
  return example_in_example

serialized_example_in_examples = [_example_in_example(
    CONTEXT, EXAMPLES).SerializeToString()] * 100 . # dummy example.

data_file = "/tmp/data.tfrecord"
if tf.io.gfile.exists(data_file):
  tf.io.gfile.remove(dummy_data_file)

with tf.io.TFRecordWriter(data_file) as writer:
  for s in serialized_example_in_examples:
        writer.write(s)
```

**Comment by bendersky** [comment]
Seems like this issue has been resolved. Please re-open if there are any additional questions.

**Comment by graviraja** [comment]
Hi @eggie5 @rbrackney @ramakumar1729  How are you deserializing the ANTIQUE  tfrecords data?
