### ISSUE TITLE
Train TF-Ranking on AWS Sagemaker

### ISSUE THREAD

**Issue by mayank953** [tensorflow/ranking#96]
I want to train the library on AWS-Sagemaker using my own data as it provides the benefit of training on GPU,A/B testing, parallel training etc. but I am unable to find the way to train TF-Ranking. 
I have trained the model locally as well as used it to predict on my test data. I have converted my data to LibSVM. I want to use Sagemaker Instance to train the same & host it as a Endpoint for further Prediction to Standardize it. Can someone please help/guide me to migrate the library to Sagemaker?

Thanks

**Comment by nalin-mathur-oyo** [comment]
Hi Mayank! I am looking towards doing the exact same thing that you are, that is, importing my current training script onto Sagemaker. 

However, I am facing an issue regarding using the saved model to predict on my test data. I used to sample script provided by tf-ranking to train a model with some data I had (examples/tf_ranking_libsvm.py). It saved the model in a .pb file. However, I am facing issues with using this file to make predictions on new test data. Can you please guide me towards using this saved model to make predictions on new data?

**Comment by eggie5** [comment]
AWS gave 3 day seminar on SageMaker to our group early last year. From what I understand there are 2 ways to use it: either w/ the pre-made estimators or w/ Docker. I think your first step would be setting up your training routine to run in a docker image, then you can launch it on SageMaker w/ little modifications. 

Be warned thought, sagemaker inference (serving your model) costs ($) are high. The nice part of TF Ranking is that is built on the TF Estimators API which provides some nice patterns for training and deployment. For example, if you export your model using the SaveModel API, then you can run inference on your model on any platform w/ the TF runtime. For example, you can deserialize and host your model in a Java backend or serve it w/ TF serving or just wrap it in a Flask web api.

**Comment by mayank953** [comment]
@eggie5 Thanks a lot for your Insight. I was actually trying to do that by transforming the code into [this](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/advanced_functionality/tensorflow_bring_your_own). But the issue was of transforming the code into the required format of /cifar10/cifar10.py.  The other way is by making a docker image for which [this](https://towardsdatascience.com/building-fully-custom-machine-learning-models-on-aws-sagemaker-a-practical-guide-c30df3895ef7) is a pretty good tutorial. The main issue is that the code has dependencies & converting it into a compatible format. 
Fortunately, Cost is not an issue, I need to train my model using SM GPU. I was able to transform some of my custom models to Sagemaker but was facing difficulties in this library in particular. 
Exporting the trained model & using docker to host it I was especially facing the [issue](https://stackoverflow.com/questions/57357722/correct-payload-for-tensor-flow-serving-api-using-docker). It would be great if somehow you are able to help me with it.

Will surely update on the same if I'm able to figure it out. Meanwhile, let me know if you are able to deduce anything.

**Comment by bendersky** [comment]
Closing this for now.
